; Generated by tools.grammar; edit grammar/lexicon.coda and tree-sitter.coda.
(integer_literal) @number
(decimal_literal) @number.float
(string_literal) @string
(identifier) @variable
(type_identifier) @type
"(" @punctuation.bracket
")" @punctuation.bracket
"," @punctuation.delimiter
"{" @punctuation.bracket
"}" @punctuation.bracket
"[" @punctuation.bracket
"]" @punctuation.bracket
":" @operator
";" @punctuation.delimiter
"." @punctuation.delimiter
"=" @operator
"+" @operator
"-" @operator
"*" @operator
"/" @operator
"$" @punctuation.delimiter
"#" @operator
"&" @operator
"^" @operator
"@" @punctuation.delimiter
"!" @operator
"?" @operator
"??" @operator
"~" @operator
"=>" @operator
"==" @operator
"~=" @operator
"<=" @operator
">=" @operator
"<" @operator
">" @operator
"'*" @operator
"'/" @operator
"'+" @operator
"'-" @operator
"'==" @operator
"'~=" @operator
"'<=" @operator
"'>=" @operator
"'<" @operator
"'>" @operator
"type" @keyword
"alias" @keyword
"Type" @type.builtin
"struct" @keyword
"variant" @keyword
"enum" @keyword
"package" @keyword
"import" @keyword
"as" @keyword
"implicit" @keyword
"init" @keyword
"match" @keyword
"spawn" @keyword
"true" @boolean
"false" @boolean
"this" @variable.builtin
"mut" @keyword
"abort" @keyword.return
"return" @keyword.return
"resolve" @keyword
(doc_comment) @comment.documentation
(comment) @comment
(name_expr (identifier) @module "$")
(name_type (identifier) @module "$")
(header_decl "package" (identifier) @module)
(import_decl (identifier) @module)
(func_callee "." (identifier) @variable.member)
(app (name_type) "." (identifier) @variable.member)
(body_field . (identifier) @variable.member)
(field_arg . (identifier) @variable.member)
(constructor_field_arg . (identifier) @variable.member)
[(unbraced_verb_call (func_callee (primary (name_expr (identifier) @function.call .)))) (block_call (func_callee (primary (name_expr (identifier) @function.call .))))]
[(unbraced_verb_call (primary (name_expr (identifier) @function.method.call .))) (block_call (primary (name_expr (identifier) @function.method.call .)))]
[(unbraced_verb_call (func_callee "." (identifier) @function.method.call)) (block_call (func_callee "." (identifier) @function.method.call))]
(block_decl (ret_type) . (identifier) @function . "(")
(simple_decl (ret_type) . (identifier) @function . "(")
(simple_decl_braced (ret_type) . (identifier) @function . "(")
(param . (identifier) @variable.parameter)
(constructor_field . (identifier) @variable.parameter)
