; extends
; Generated by tools.grammar; edit grammar/tree-sitter.coda.
((name_expr . (identifier) @variable.parameter .) (#zane-bound? @variable.parameter))
((field_arg . (identifier) @variable.parameter .) (#zane-bound? @variable.parameter))
