; extends
; Generated by tools.grammar; edit grammar/tree-sitter.coda.
((primary . (identifier) @variable.parameter .) (#zane-bound? @variable.parameter))
((primary_braced "init" (identifier) @variable.parameter . ";") (#zane-bound? @variable.parameter))
