-- Generated by tools.grammar.
vim.filetype.add({ extension = { ["zn"] = "zane", ["zane"] = "zane" } })
vim.api.nvim_create_autocmd("FileType", {
  pattern = "zane",
  callback = function() vim.treesitter.start() end,
})
