-- Generated by tools.grammar.
vim.filetype.add({ extension = { ["zn"] = "zane", ["zane"] = "zane" } })
vim.api.nvim_create_autocmd("FileType", {
  pattern = "zane",
  -- A missing parser must not stop the buffer from opening.
  callback = function(args) pcall(vim.treesitter.start, args.buf, "zane") end,
})
