-- Generated by tools.grammar.
vim.filetype.add({ extension = { ["zn"] = "zane", ["zane"] = "zane" } })

-- Nodes that bind a name with their first named child (tree-sitter.coda
-- `binders`), and the node types that can hold one as a direct child, which
-- the generator derives from the grammar.
local binders = { constructor_field = true, param = true }
local containers = { abort_ret_type = true, block_decl = true, enum_map_decl = true, expr = true, expr_braced = true, simple_decl = true, simple_decl_braced = true, type_expr = true }

-- (#zane-bound? @name) holds when a binder of the captured name is a child of
-- one of the name's ancestors. Zane forbids a local from shadowing a parameter
-- (docs/design/semantics.md D14), so that binder is the one the name refers to.
--
-- The walk goes down from the root rather than up from the name: finding a
-- node's parent searches from the root each time, and a binder's siblings are
-- only scanned in a container, never in a long statement list.
vim.treesitter.query.add_predicate("zane-bound?", function(match, _, source, predicate)
  for _, node in ipairs(match[predicate[2]] or {}) do
    local name = vim.treesitter.get_node_text(node, source)
    local bound = false
    local scope = node:tree():root()
    while scope and not scope:equal(node) and not bound do
      if containers[scope:type()] then
        for child in scope:iter_children() do
          local binder = binders[child:type()] and child:named_child(0)
          if binder and vim.treesitter.get_node_text(binder, source) == name then
            bound = true
            break
          end
        end
      end
      scope = scope:child_with_descendant(node)
    end
    if not bound then
      return false
    end
  end
  return true
end, { force = true })

vim.api.nvim_create_autocmd("FileType", {
  pattern = "zane",
  -- A missing parser must not stop the buffer from opening.
  callback = function(args) pcall(vim.treesitter.start, args.buf, "zane") end,
})
