"""A small portable lexical expression algebra, shared by all backends."""
from __future__ import annotations

import json


def quoted(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


# Escape only what is special somewhere in the regex dialects the editors use
# (Rust regex, Oniguruma, fancy-regex): `&`, `-` and `~` start set operations
# inside Rust classes. Control characters get their named escapes rather than
# a backslash before the raw character, which not every dialect accepts.
REGEX_SPECIAL = set("\\^$.|?*+()[]{}&-~")


def regex_char(char: str) -> str:
    named = {"\n": "\\n", "\r": "\\r", "\t": "\\t"}
    if char in named:
        return named[char]
    if ord(char) < 0x20 or ord(char) == 0x7F:
        return f"\\x{ord(char):02x}"
    return "\\" + char if char in REGEX_SPECIAL else char


def regex_literal(text: str) -> str:
    return "".join(regex_char(c) for c in text)


def render(expr, definitions: dict, backend: str, stack=()) -> str:
    if isinstance(expr, str):
        return quoted(expr) if backend == "sedlex" else regex_literal(expr)
    if not isinstance(expr, dict) or len(expr) != 1:
        raise ValueError(f"invalid lexical expression: {expr!r}")
    op, value = next(iter(expr.items()))
    child = lambda e: render(e, definitions, backend, stack)
    if op == "ref":
        if value in stack:
            raise ValueError(f"recursive lexical expression: {value}")
        if value not in definitions:
            raise ValueError(f"undefined lexical expression: {value}")
        return render(definitions[value], definitions, backend, (*stack, value))
    if op in ("seq", "choice"):
        if not isinstance(value, list) or not value:
            raise ValueError(f"{op} requires a nonempty list")
        parts = [child(e) for e in value]
        if backend == "sedlex":
            return "(" + (", " if op == "seq" else " | ").join(parts) + ")"
        return "(?:" + ("" if op == "seq" else "|").join(parts) + ")"
    if op in ("star", "plus", "optional"):
        part = child(value)
        if backend == "sedlex":
            return {"star": "Star", "plus": "Plus", "optional": "Opt"}[op] + " (" + part + ")"
        return "(?:" + part + ")" + {"star": "*", "plus": "+", "optional": "?"}[op]
    if op == "unicode":
        properties = {"alphabetic": "Alphabetic", "lowercase": "Lowercase", "uppercase": "Uppercase"}
        if value not in properties:
            raise ValueError(f"unsupported Unicode property: {value}")
        return value if backend == "sedlex" else "\\p{" + properties[value] + "}"
    if op == "range":
        if len(value) != 2 or any(len(v) != 1 for v in value):
            raise ValueError("range requires two characters")
        if backend == "sedlex":
            return ocaml_char(value[0]) + ".." + ocaml_char(value[1])
        return "[" + regex_char(value[0]) + "-" + regex_char(value[1]) + "]"
    if op == "not":
        if not value or any(len(v) != 1 for v in value):
            raise ValueError("not requires a nonempty character list")
        if backend == "sedlex":
            return "Compl (" + " | ".join(ocaml_char(v) for v in value) + ")"
        return "[^" + "".join(regex_char(v) for v in value) + "]"
    if op == "any" and value is True:
        return "any" if backend == "sedlex" else "[\\s\\S]"
    raise ValueError(f"unknown lexical operator: {op}")


def ocaml_char(value: str) -> str:
    escaped = {"'": "\\'", "\\": "\\\\", "\n": "\\n", "\r": "\\r", "\t": "\\t"}.get(value, value)
    return "'" + escaped + "'"


def lexer(spec: dict) -> str:
    lines = ["(* Generated by tools.grammar; edit grammar/lexicon.coda. *)", "open Sedlexing", "open Parser", "", "exception Lexing_error", "", "let rec token buf =", "  match%sedlex buf with"]
    definitions = spec["expressions"]
    for trivia in spec["trivia"]:
        lines.append(f"  | {render(trivia['pattern'], definitions, 'sedlex')} -> token buf")
    # Sedlex chooses the longest match, then the first rule. Put literals before
    # identifiers so reserved words win ties, without stealing keyword prefixes.
    for token in sorted(spec["tokens"], key=lambda t: "pattern" in t):
        name = token["name"]
        if token.get("eof"):
            pattern, action = "eof", name
        elif "literal" in token:
            pattern, action = quoted(token["literal"]), name
        else:
            pattern = render(token["pattern"], definitions, "sedlex")
            action = name + " (Utf8.lexeme buf)"
            if token.get("value") == "unquote":
                action = "let s = Utf8.lexeme buf in " + name + " (String.sub s 1 (String.length s - 2))"
        lines.append(f"  | {pattern} -> {action}")
    return "\n".join([*lines, "  | _ -> raise Lexing_error", ""])


def sublime(spec: dict) -> str:
    # JSON strings are also valid YAML quoted scalars.
    lines = ["%YAML 1.2", "---", "# Generated by tools.grammar; edit grammar/lexicon.coda.", "name: Zane", "file_extensions: " + json.dumps(spec["extensions"]), "scope: source." + spec["language"], "contexts:", "  main:"]
    definitions = spec["expressions"]
    for trivia in spec["trivia"]:
        if "scope" in trivia:
            lines += ["    - match: " + quoted(render(trivia["pattern"], definitions, "regex")), "      scope: " + trivia["scope"] + ".zane"]
    # An explicit string context keeps an unfinished string highlighted while
    # editing; comment/keyword rules cannot run inside it.
    string = next(t for t in spec["tokens"] if t.get("value") == "unquote")
    lines += ["    - match: " + quoted('"'), "      push: string"]
    for token in sorted(spec["tokens"], key=lambda t: ("pattern" in t, -t.get("highlight_priority", 0), -len(t.get("literal", "")))):
        if token.get("eof") or token == string:
            continue
        if "literal" in token:
            pattern = regex_literal(token["literal"])
            if token["literal"][0].isalpha():
                # Zane's identifier continuation uses Alphabetic and ASCII
                # digits, not \w; it does not allow internal underscores.
                pattern = r"(?<![\p{Alphabetic}0-9_])" + pattern + r"(?![\p{Alphabetic}0-9])"
        else:
            pattern = render(token["pattern"], definitions, "regex")
        lines += ["    - match: " + quoted(pattern), "      scope: " + token["scope"] + ".zane"]
    lines += ["  string:", "    - meta_scope: " + string["scope"] + ".zane", "    - match: " + quoted(r"\\[\s\S]"), "      scope: constant.character.escape.zane", "    - match: " + quoted('"'), "      pop: true"]
    return "\n".join([*lines, ""])
