"""Read Menhir's action-erased, expanded grammar, not arbitrary OCaml text."""
from __future__ import annotations

from dataclasses import dataclass
import re

from .lexical import quoted


@dataclass(frozen=True)
class Production:
    symbols: tuple[str, ...]
    precedence: str | None = None


def generate(template: str, spec: dict) -> str:
    marker = "(* @generated-tokens *)"
    if template.count(marker) != 1:
        raise ValueError("syntax.mly must contain exactly one generated-tokens marker")
    if re.search(r"^%token\b", template, re.M):
        raise ValueError("token declarations belong in lexicon.coda")
    require_symbolic_terminals(template)
    declarations = []
    for token in spec["tokens"]:
        typ = f"<{token['type']}> " if "type" in token else ""
        alias = token.get('literal', token.get('example', '<eof>'))
        declarations.append("%token " + typ + token["name"] + " " + quoted(alias))
    return "(* Generated by tools.grammar; edit grammar/syntax.mly and lexicon.coda. *)\n" + template.replace(marker, "\n".join(declarations))


def keep_inline_rules(template: str, names) -> str:
    """Turn the named `%inline` rules into ordinary ones.

    Only the Tree-sitter translation reads the result, so the editor tree gets
    a node for each of them while the compiler grammar stays as written.
    """
    for name in names:
        if not re.fullmatch(r"[a-z_][A-Za-z0-9_]*", name):
            raise ValueError(f"invalid kept inline rule name: {name!r}")
        pattern = re.compile(r"^%inline[ \t]+" + re.escape(name) + r"[ \t]*:", re.M)
        if len(pattern.findall(template)) != 1:
            raise ValueError(f"kept inline rule {name} must be one unparameterized %inline rule")
        template = pattern.sub(name + ":", template)
    return template


def require_symbolic_terminals(template: str) -> None:
    """Do not duplicate lexical spellings in productions.

    Comments and OCaml actions can contain strings, braces and nested comments.
    This scanner only enforces the symbolic-terminal convention; Menhir remains
    responsible for parsing the grammar itself.
    """
    sections = template.split('%%', 1)
    if len(sections) != 2:
        raise ValueError('syntax.mly is missing its grammar section')
    body = sections[1]
    i, action_depth = 0, 0
    while i < len(body):
        if body.startswith('(*', i):
            depth = 1
            i += 2
            while depth and i < len(body):
                if body.startswith('(*', i):
                    depth += 1
                    i += 2
                elif body.startswith('*)', i):
                    depth -= 1
                    i += 2
                else:
                    i += 1
            if depth:
                raise ValueError('unterminated grammar comment')
        elif body.startswith('/*', i):
            end = body.find('*/', i + 2)
            if end == -1:
                raise ValueError('unterminated grammar comment')
            i = end + 2
        elif body[i] == '"':
            if not action_depth:
                raise ValueError('use symbolic token names in productions, not quoted aliases')
            i += 1
            while i < len(body) and body[i] != '"':
                i += 2 if body[i] == '\\' else 1
            if i == len(body):
                raise ValueError('unterminated action string')
            i += 1
        elif body[i] == "'" and action_depth and (char := re.match(r"'(?:\\.|[^'\\])'", body[i:])):
            i += len(char[0])
        else:
            if body[i] == '{':
                action_depth += 1
            elif body[i] == '}':
                action_depth -= 1
                if action_depth < 0:
                    raise ValueError('unbalanced action braces')
            i += 1
    if action_depth:
        raise ValueError('unbalanced action braces')


def read_expanded(text: str):
    sections = text.split("%%")
    if len(sections) not in (2, 3) or len(sections) == 3 and sections[2].strip():
        raise ValueError("unexpected expanded grammar sections")
    header, body = sections[:2]
    precedence = {}
    for level, match in enumerate(re.finditer(r"^%(left|right|nonassoc)\s+([^\n]+)", header, re.M), 1):
        assoc, tokens = match.groups()
        for token in tokens.split():
            precedence[token] = level, assoc
    starts = re.findall(r"^%start(?:\s+<[^>]+>)?\s+(\w+)\s*$", header, re.M)
    if len(starts) != 1:
        raise ValueError("exactly one start symbol is supported")
    start = starts[0]
    rules = {}
    # --only-preprocess-uu expands aliases, parameterized rules and %inline,
    # removes actions/bindings, and gives helper symbols identifier-safe names.
    # Standard-library helpers carry simple @name attributes. They are
    # metadata, not productions. Reject other attributes rather than silently
    # skipping arbitrary OCaml expressions with a regex.
    body = re.sub(r"\[@name\s+[A-Za-z_][A-Za-z_0-9]*\]", "", body)
    lexemes = re.findall(r"%prec|[A-Za-z_][A-Za-z_0-9]*|\{\}|[|:]|\S", body)
    i = 0
    while i < len(lexemes):
        name = lexemes[i]
        if not re.fullmatch(r"[A-Za-z_][A-Za-z_0-9]*", name) or lexemes[i + 1:i + 2] != [":"]:
            raise ValueError(f"unexpected expanded grammar near {lexemes[i:i+8]}")
        i += 2
        productions = []
        while i < len(lexemes):
            if lexemes[i] == "|":
                i += 1
            symbols = []
            prec = None
            while i < len(lexemes) and lexemes[i] != "{}":
                value = lexemes[i]
                if value == "%prec":
                    prec = lexemes[i + 1]
                    i += 2
                    continue
                if not re.fullmatch(r"[A-Za-z_][A-Za-z_0-9]*", value):
                    raise ValueError(f"unsupported expanded grammar symbol: {value}")
                symbols.append(value)
                i += 1
            if i == len(lexemes):
                raise ValueError("unterminated expanded production")
            i += 1
            # Menhir versions can print %prec after the erased action.
            if lexemes[i:i + 1] == ["%prec"]:
                prec = lexemes[i + 1]
                i += 2
            productions.append(Production(tuple(symbols), prec))
            if i == len(lexemes) or lexemes[i] != "|":
                break
        if name in rules:
            raise ValueError(f"duplicate expanded rule: {name}")
        rules[name] = productions
    return start, rules, precedence
