-- Generated by tools.grammar.
vim.filetype.add({ extension = { @EXTENSIONS@ } })

-- (#zane-bound-by? @name "type" ...) holds when an enclosing node has a child
-- of one of the given types whose first named child spells the captured name.
-- Zane forbids a local from shadowing a parameter (docs/design/semantics.md
-- D14), so a name that matches an enclosing binder refers to that binder.
vim.treesitter.query.add_predicate("zane-bound-by?", function(match, _, source, predicate)
  local types = {}
  for i = 3, #predicate do
    types[predicate[i]] = true
  end
  for _, node in ipairs(match[predicate[2]] or {}) do
    local name = vim.treesitter.get_node_text(node, source)
    local bound = false
    local scope = node:parent()
    -- The root only holds declarations, never a binder, so stop below it.
    while scope and scope:parent() and not bound do
      for child in scope:iter_children() do
        local binder = types[child:type()] and child:named_child(0)
        if binder and vim.treesitter.get_node_text(binder, source) == name then
          bound = true
          break
        end
      end
      scope = scope:parent()
    end
    if not bound then
      return false
    end
  end
  return true
end, { force = true })

vim.api.nvim_create_autocmd("FileType", {
  pattern = "zane",
  -- A missing parser must not stop the buffer from opening.
  callback = function(args) pcall(vim.treesitter.start, args.buf, "zane") end,
})
