"""Translate expanded productions into a Tree-sitter grammar.

Tree-sitter forbids empty non-start rules. Nullable symbols are represented by
optional references to their nonempty language; wholly empty helpers disappear.
"""
from __future__ import annotations

from .lexical import render, quoted
from . import keywords


def call(name: str, parts: list[str]) -> str:
    if len(parts) == 1:
        return parts[0]
    return name + "(" + ", ".join(parts) + ")"


def generate(spec, start, rules, precedence, overlay, conflicts=()):
    tokens = {t["name"]: t for t in spec["tokens"]}
    unknown = {s for ps in rules.values() for p in ps for s in p.symbols} - tokens.keys() - rules.keys()
    if unknown:
        raise ValueError(f"undefined grammar symbols: {sorted(unknown)}")
    for name, productions in rules.items():
        for p in productions:
            for i, s in enumerate(p.symbols):
                if tokens.get(s, {}).get('eof') and (name != start or i != len(p.symbols) - 1):
                    raise ValueError('EOF is supported only at the end of a start production')
    nullable = set()
    while True:
        new = {n for n, ps in rules.items() if any(all(s in nullable or tokens.get(s, {}).get('eof') for s in p.symbols) for p in ps)}
        if new <= nullable:
            break
        nullable |= new
    productive = set()
    while True:
        new = {n for n, ps in rules.items() if any(all(s in productive or s in nullable or s in tokens for s in p.symbols) and any(s in productive or s in tokens and not tokens[s].get('eof') for s in p.symbols) for p in ps)}
        if new <= productive:
            break
        productive |= new

    # Keep the start node public, compiler helper nodes private. Leaf tokens
    # are public and stable so highlight queries survive helper renumbering.
    public = set(overlay.get('public_rules', [])) | set(overlay.get('kept_inline_rules', []))
    if public - productive:
        raise ValueError(f"unknown public rules: {sorted(public - productive)}")
    names = {name: ("source_file" if name == start else name if name in public else "_" + name) for name in productive | {start}}
    leaf_names = {t["node"] for t in tokens.values() if "node" in t}
    if len(names.values()) != len(set(names.values())) or leaf_names & set(names.values()):
        raise ValueError("Tree-sitter node name collision")

    def symbol(s):
        if s in tokens:
            t = tokens[s]
            return quoted(t['literal']) if 'literal' in t else '$.' + t['node']
        return '$.' + names[s]

    lines = ["// Generated by tools.grammar; edit grammar/, then regenerate.", "module.exports = grammar({", "  name: " + quoted(spec["language"]) + ","]
    extras = []
    for trivia in spec['trivia']:
        if 'capture' in trivia:
            extras.append('$.' + trivia['name'])
        else:
            extras.append('new RustRegex(' + quoted(render(trivia['pattern'], spec['expressions'], 'regex')) + ')')
    lines.append("  extras: $ => [" + ", ".join(extras) + "],")
    declarations = []
    for group in conflicts:
        if not group or any(n not in names.values() for n in group):
            raise ValueError(f"invalid Tree-sitter conflict: {group}")
        declarations.append('[' + ', '.join('$.' + n for n in group) + ']')
    lines.append("  conflicts: $ => [" + ", ".join(declarations) + "],")
    lines.append("  rules: {")
    for name in [start, *sorted(productive - {start})]:
        alternatives = []
        for p in rules[name]:
            syms = [s for s in p.symbols if not tokens.get(s, {}).get('eof') and (s in tokens or s in productive)]
            if not syms:
                continue
            candidates = []
            if all(s in nullable for s in syms):
                # Choose the first nonempty child, omitting earlier empty ones.
                for i, s in enumerate(syms):
                    candidates.append([symbol(s), *['optional(' + symbol(x) + ')' for x in syms[i+1:]]])
            else:
                candidates.append(['optional(' + symbol(s) + ')' if s in nullable else symbol(s) for s in syms])
            prec_token = p.precedence
            if prec_token is None:
                # Menhir uses the rightmost terminal, even if that terminal
                # has no declared precedence.
                prec_token = next((s for s in reversed(p.symbols) if s in tokens), None)
            for parts in candidates:
                result = call('seq', parts)
                if prec_token in precedence:
                    level, assoc = precedence[prec_token]
                    fn = {'left': 'prec.left', 'right': 'prec.right', 'nonassoc': 'prec'}[assoc]
                    result = f'{fn}({level}, {result})'
                if result not in alternatives:
                    alternatives.append(result)
        if name == start and name in nullable:
            alternatives.append('seq()')
        if not alternatives:
            raise ValueError(f'no nonempty alternatives for {name}')
        lines.append('    ' + names[name] + ': $ => ' + call('choice', alternatives) + ',')
    for t in tokens.values():
        if 'node' in t:
            lines.append('    ' + t['node'] + ': $ => new RustRegex(' + quoted(keywords.pattern(t, spec)) + '),')
    for trivia in spec['trivia']:
        if 'capture' in trivia:
            lines.append('    ' + trivia['name'] + ': $ => new RustRegex(' + quoted(render(trivia['pattern'], spec['expressions'], 'regex')) + '),')
    lines += ['  },', '});', '']
    queries = ['; Generated by tools.grammar; edit grammar/lexicon.coda and tree-sitter.coda.']
    for t in [*tokens.values(), *spec['trivia']]:
        if 'capture' not in t:
            continue
        node = '(' + t['node'] + ')' if 'node' in t else '(' + t['name'] + ')' if 'pattern' in t else quoted(t['literal'])
        queries.append(node + ' @' + t['capture'])
    queries.extend(overlay.get('highlights', []))
    return '\n'.join(lines), '\n'.join([*queries, ''])


def binder_containers(start, rules, overlay, binders):
    """Visible node types that can have one of `binders` as a direct child.

    Hidden rules flatten into their parent, so a binder under a hidden helper
    is a child of the nearest visible ancestor. Neovim's zane-bound?
    predicate only scans these nodes for binders.
    """
    visible = {start} | set(overlay.get('public_rules', [])) | set(overlay.get('kept_inline_rules', []))
    unknown = set(binders) - (visible & rules.keys())
    if unknown:
        raise ValueError(f"binders must be visible rules: {sorted(unknown)}")
    # children[r]: the visible rules that appear as r's direct children.
    children = {r: set() for r in rules}
    while True:
        changed = False
        for r, productions in rules.items():
            for p in productions:
                for s in p.symbols:
                    if s not in rules:
                        continue
                    found = {s} if s in visible else children[s]
                    if not found <= children[r]:
                        children[r] |= found
                        changed = True
        if not changed:
            break
    return sorted(("source_file" if r == start else r) for r in visible & rules.keys() if children[r] & set(binders))
