// src/grammar/parser.cc
// *** DO NOT EDIT BY HAND ***
// automatically generated by gramanl, from src/grammar/parser.gr

// GLR source location information is enabled

#include "parser.h"     // ZaneParser
#include "parsetables.h" // ParseTables
#include "srcloc.h"      // SourceLoc

#include <assert.h>      // assert
#include <iostream>      // std::cout
#include <stdlib.h>      // abort

static char const *termNames[] = {
  "TOK_EOF",  // 0
  "TOK_LPAREN",  // 1
  "TOK_RPAREN",  // 2
  "TOK_LCURLY",  // 3
  "TOK_RCURLY",  // 4
  "TOK_COMMA",  // 5
  "TOK_COLON",  // 6
  "TOK_EQUAL",  // 7
  "TOK_DOLLAR",  // 8
  "TOK_THIN_ARROW",  // 9
  "TOK_THICK_ARROW",  // 10
  "TOK_AT",  // 11
  "TOK_MUT",  // 12
  "TOK_THIS",  // 13
  "TOK_STRING",  // 14
  "TOK_IDENT",  // 15
  "TOK_INT",  // 16
  "TOK_FLOAT",  // 17
  "TOK_PLUS",  // 18
  "TOK_MINUS",  // 19
  "TOK_STAR",  // 20
  "TOK_SLASH",  // 21
  "TOK_TILDE",  // 22
  "TOK_LINEBREAK",  // 23
  "TOK_ERROR",  // 24
};

string ZaneParser::terminalDescription(int termId, SemanticValue sval)
{
  return stringc << termNames[termId]
                 << "(" << (sval % 100000) << ")";
}


static char const *nontermNames[] = {
  "empty",  // 0
  "__EarlyStartSymbol",  // 1
  "may_break",  // 2
  "package",  // 3
  "global_scope",  // 4
  "declaration",  // 5
  "variable_decl",  // 6
  "function_decl",  // 7
  "method_decl",  // 8
  "parameters",  // 9
  "parameter_list",  // 10
  "method_parameters",  // 11
  "method_parameter_seq",  // 12
  "parameter",  // 13
  "type_list",  // 14
  "type_list_ne",  // 15
  "type_expr",  // 16
  "name_type",  // 17
  "function_type",  // 18
  "method_type",  // 19
  "arrow_body",  // 20
  "function_body",  // 21
  "scope",  // 22
  "statements",  // 23
  "function_call",  // 24
  "statement",  // 25
  "value_expr",  // 26
  "parenthized_value",  // 27
  "arguments",  // 28
  "argument_list",  // 29
};

string ZaneParser::nonterminalDescription(int nontermId, SemanticValue sval)
{
  return stringc << nontermNames[nontermId]
                 << "(" << (sval % 100000) << ")";
}


char const *ZaneParser::terminalName(int termId)
{
  return termNames[termId];
}

char const *ZaneParser::nonterminalName(int nontermId)
{
  return nontermNames[nontermId];
}

// ------------------- actions ------------------
// [0] __EarlyStartSymbol[int] -> top:may_break TOK_EOF
inline int ZaneParser::action0___EarlyStartSymbol(SourceLoc loc, int top)
#line 1 "<init>"
{ return top;  }
#line 106 "src/grammar/parser.cc"

// [1] may_break[int] -> empty
inline int ZaneParser::action1_may_break(SourceLoc loc)
#line 117 "src/grammar/parser.gr"
{ return 0;  }
#line 112 "src/grammar/parser.cc"

// [2] may_break[int] -> TOK_LINEBREAK
inline int ZaneParser::action2_may_break(SourceLoc loc)
#line 118 "src/grammar/parser.gr"
{ return 0;  }
#line 118 "src/grammar/parser.cc"

// [3] package[ast::nodes::Package*] -> may_break declarations:global_scope may_break
inline ast::nodes::Package* ZaneParser::action3_package(SourceLoc loc, std::vector<ast::nodes::Declaration>* declarations)
#line 124 "src/grammar/parser.gr"
{
		return new ast::nodes::Package(grammarSupport::takeValue(declarations));
	 }
#line 126 "src/grammar/parser.cc"

// [4] global_scope[std::vector<ast::nodes::Declaration>*] -> empty
inline std::vector<ast::nodes::Declaration>* ZaneParser::action4_global_scope(SourceLoc loc)
#line 132 "src/grammar/parser.gr"
{
		return new std::vector<ast::nodes::Declaration>();
	 }
#line 134 "src/grammar/parser.cc"

// [5] global_scope[std::vector<ast::nodes::Declaration>*] -> declaration:declaration
inline std::vector<ast::nodes::Declaration>* ZaneParser::action5_global_scope(SourceLoc loc, ast::nodes::Declaration* declaration)
#line 135 "src/grammar/parser.gr"
{
		auto* list = new std::vector<ast::nodes::Declaration>();
		list->push_back(grammarSupport::takeValue(declaration));
		return list;
	 }
#line 144 "src/grammar/parser.cc"

// [6] global_scope[std::vector<ast::nodes::Declaration>*] -> declarations:global_scope TOK_LINEBREAK declaration:declaration
inline std::vector<ast::nodes::Declaration>* ZaneParser::action6_global_scope(SourceLoc loc, std::vector<ast::nodes::Declaration>* declarations, ast::nodes::Declaration* declaration)
#line 140 "src/grammar/parser.gr"
{
		declarations->push_back(grammarSupport::takeValue(declaration));
		return declarations;
	 }
#line 153 "src/grammar/parser.cc"

// [7] declaration[ast::nodes::Declaration*] -> function:function_decl
inline ast::nodes::Declaration* ZaneParser::action7_declaration(SourceLoc loc, ast::nodes::FunctionDecl* function)
#line 149 "src/grammar/parser.gr"
{
		return new ast::nodes::Declaration(grammarSupport::takeValue(function));
	 }
#line 161 "src/grammar/parser.cc"

// [8] declaration[ast::nodes::Declaration*] -> method:method_decl
inline ast::nodes::Declaration* ZaneParser::action8_declaration(SourceLoc loc, ast::nodes::MethodDecl* method)
#line 152 "src/grammar/parser.gr"
{
		return new ast::nodes::Declaration(grammarSupport::takeValue(method));
	 }
#line 169 "src/grammar/parser.cc"

// [9] variable_decl[ast::nodes::VariableDecl*] -> name:TOK_IDENT type:type_expr = value:value_expr
inline ast::nodes::VariableDecl* ZaneParser::action9_variable_decl(SourceLoc loc, std::string* name, ast::nodes::TypeExpression* type, ast::nodes::ValueExpr* value)
#line 160 "src/grammar/parser.gr"
{
		return new ast::nodes::VariableDecl(
			grammarSupport::takeString(name),
			grammarSupport::takeValue(type),
			grammarSupport::takePtr(value)
		);
	 }
#line 181 "src/grammar/parser.cc"

// [10] function_decl[ast::nodes::FunctionDecl*] -> return_type:type_expr name:TOK_IDENT ( params:parameters ) body:function_body
inline ast::nodes::FunctionDecl* ZaneParser::action10_function_decl(SourceLoc loc, ast::nodes::TypeExpression* return_type, std::string* name, std::vector<ast::nodes::Parameter>* params, grammarSupport::FunctionBody* body)
#line 172 "src/grammar/parser.gr"
{
		return new ast::nodes::FunctionDecl(
			grammarSupport::takeString(name),
			grammarSupport::takeValue(params),
			grammarSupport::takeValue(return_type),
			grammarSupport::takeValue(body)
		);
	 }
#line 194 "src/grammar/parser.cc"

// [11] method_decl[ast::nodes::MethodDecl*] -> return_type:type_expr name:TOK_IDENT ( params:method_parameters ) body:function_body
inline ast::nodes::MethodDecl* ZaneParser::action11_method_decl(SourceLoc loc, ast::nodes::TypeExpression* return_type, std::string* name, std::vector<ast::nodes::Parameter>* params, grammarSupport::FunctionBody* body)
#line 185 "src/grammar/parser.gr"
{
		return new ast::nodes::MethodDecl(
			grammarSupport::takeString(name),
			grammarSupport::takeValue(params),
			grammarSupport::takeValue(return_type),
			grammarSupport::takeValue(body),
			false
		);
	 }
#line 208 "src/grammar/parser.cc"

// [12] method_decl[ast::nodes::MethodDecl*] -> return_type:type_expr name:TOK_IDENT ( params:method_parameters ) mut body:function_body
inline ast::nodes::MethodDecl* ZaneParser::action12_method_decl(SourceLoc loc, ast::nodes::TypeExpression* return_type, std::string* name, std::vector<ast::nodes::Parameter>* params, grammarSupport::FunctionBody* body)
#line 194 "src/grammar/parser.gr"
{
		return new ast::nodes::MethodDecl(
			grammarSupport::takeString(name),
			grammarSupport::takeValue(params),
			grammarSupport::takeValue(return_type),
			grammarSupport::takeValue(body),
			true
		);
	 }
#line 222 "src/grammar/parser.cc"

// [13] parameters[std::vector<ast::nodes::Parameter>*] -> empty
inline std::vector<ast::nodes::Parameter>* ZaneParser::action13_parameters(SourceLoc loc)
#line 208 "src/grammar/parser.gr"
{
		return new std::vector<ast::nodes::Parameter>();
	 }
#line 230 "src/grammar/parser.cc"

// [14] parameters[std::vector<ast::nodes::Parameter>*] -> list:parameter_list
inline std::vector<ast::nodes::Parameter>* ZaneParser::action14_parameters(SourceLoc loc, std::vector<ast::nodes::Parameter>* list)
#line 211 "src/grammar/parser.gr"
{
		return list;
	 }
#line 238 "src/grammar/parser.cc"

// [15] parameter_list[std::vector<ast::nodes::Parameter>*] -> parameter:parameter
inline std::vector<ast::nodes::Parameter>* ZaneParser::action15_parameter_list(SourceLoc loc, ast::nodes::Parameter* parameter)
#line 219 "src/grammar/parser.gr"
{
		auto* list = new std::vector<ast::nodes::Parameter>();
		list->push_back(grammarSupport::takeValue(parameter));
		return list;
	 }
#line 248 "src/grammar/parser.cc"

// [16] parameter_list[std::vector<ast::nodes::Parameter>*] -> list:parameter_list , parameter:parameter
inline std::vector<ast::nodes::Parameter>* ZaneParser::action16_parameter_list(SourceLoc loc, std::vector<ast::nodes::Parameter>* list, ast::nodes::Parameter* parameter)
#line 224 "src/grammar/parser.gr"
{
		list->push_back(grammarSupport::takeValue(parameter));
		return list;
	 }
#line 257 "src/grammar/parser.cc"

// [17] method_parameters[std::vector<ast::nodes::Parameter>*] -> list:method_parameter_seq
inline std::vector<ast::nodes::Parameter>* ZaneParser::action17_method_parameters(SourceLoc loc, std::vector<ast::nodes::Parameter>* list)
#line 233 "src/grammar/parser.gr"
{
		return list;
	 }
#line 265 "src/grammar/parser.cc"

// [18] method_parameter_seq[std::vector<ast::nodes::Parameter>*] -> this type:type_expr
inline std::vector<ast::nodes::Parameter>* ZaneParser::action18_method_parameter_seq(SourceLoc loc, ast::nodes::TypeExpression* type)
#line 241 "src/grammar/parser.gr"
{
		auto* list = new std::vector<ast::nodes::Parameter>();
		list->push_back(ast::nodes::Parameter(grammarSupport::takePtr(type), "this"));
		return list;
	 }
#line 275 "src/grammar/parser.cc"

// [19] method_parameter_seq[std::vector<ast::nodes::Parameter>*] -> list:method_parameter_seq , parameter:parameter
inline std::vector<ast::nodes::Parameter>* ZaneParser::action19_method_parameter_seq(SourceLoc loc, std::vector<ast::nodes::Parameter>* list, ast::nodes::Parameter* parameter)
#line 246 "src/grammar/parser.gr"
{
		list->push_back(grammarSupport::takeValue(parameter));
		return list;
	 }
#line 284 "src/grammar/parser.cc"

// [20] parameter[ast::nodes::Parameter*] -> name:TOK_IDENT type:type_expr
inline ast::nodes::Parameter* ZaneParser::action20_parameter(SourceLoc loc, std::string* name, ast::nodes::TypeExpression* type)
#line 255 "src/grammar/parser.gr"
{
		return new ast::nodes::Parameter(
			grammarSupport::takePtr(type),
			grammarSupport::takeString(name)
		);
	 }
#line 295 "src/grammar/parser.cc"

// [21] type_list[std::vector<std::unique_ptr<ast::nodes::TypeExpression>>*] -> empty
inline std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* ZaneParser::action21_type_list(SourceLoc loc)
#line 266 "src/grammar/parser.gr"
{
		return new std::vector<std::unique_ptr<ast::nodes::TypeExpression>>();
	 }
#line 303 "src/grammar/parser.cc"

// [22] type_list[std::vector<std::unique_ptr<ast::nodes::TypeExpression>>*] -> list:type_list_ne
inline std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* ZaneParser::action22_type_list(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* list)
#line 269 "src/grammar/parser.gr"
{
		return list;
	 }
#line 311 "src/grammar/parser.cc"

// [23] type_list_ne[std::vector<std::unique_ptr<ast::nodes::TypeExpression>>*] -> expr:type_expr
inline std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* ZaneParser::action23_type_list_ne(SourceLoc loc, ast::nodes::TypeExpression* expr)
#line 277 "src/grammar/parser.gr"
{
		auto* list = new std::vector<std::unique_ptr<ast::nodes::TypeExpression>>();
		list->push_back(grammarSupport::takePtr(expr));
		return list;
	 }
#line 321 "src/grammar/parser.cc"

// [24] type_list_ne[std::vector<std::unique_ptr<ast::nodes::TypeExpression>>*] -> list:type_list_ne , expr:type_expr
inline std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* ZaneParser::action24_type_list_ne(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* list, ast::nodes::TypeExpression* expr)
#line 282 "src/grammar/parser.gr"
{
		list->push_back(grammarSupport::takePtr(expr));
		return list;
	 }
#line 330 "src/grammar/parser.cc"

// [25] type_expr[ast::nodes::TypeExpression*] -> name:name_type
inline ast::nodes::TypeExpression* ZaneParser::action25_type_expr(SourceLoc loc, ast::nodes::NameType* name)
#line 291 "src/grammar/parser.gr"
{
		return new ast::nodes::TypeExpression(grammarSupport::takeValue(name));
	 }
#line 338 "src/grammar/parser.cc"

// [26] type_expr[ast::nodes::TypeExpression*] -> function:function_type
inline ast::nodes::TypeExpression* ZaneParser::action26_type_expr(SourceLoc loc, ast::nodes::FunctionType* function)
#line 294 "src/grammar/parser.gr"
{
		return new ast::nodes::TypeExpression(grammarSupport::takeValue(function));
	 }
#line 346 "src/grammar/parser.cc"

// [27] type_expr[ast::nodes::TypeExpression*] -> method:method_type
inline ast::nodes::TypeExpression* ZaneParser::action27_type_expr(SourceLoc loc, ast::nodes::MethodType* method)
#line 297 "src/grammar/parser.gr"
{
		return new ast::nodes::TypeExpression(grammarSupport::takeValue(method));
	 }
#line 354 "src/grammar/parser.cc"

// [28] name_type[ast::nodes::NameType*] -> identifier:TOK_IDENT
inline ast::nodes::NameType* ZaneParser::action28_name_type(SourceLoc loc, std::string* identifier)
#line 305 "src/grammar/parser.gr"
{
		return new ast::nodes::NameType(
			grammarSupport::takeString(identifier),
			std::vector<std::unique_ptr<ast::nodes::TypeExpression>>()
		);
	 }
#line 365 "src/grammar/parser.cc"

// [29] function_type[ast::nodes::FunctionType*] -> ( params:type_list ) -> return_type:type_expr
inline ast::nodes::FunctionType* ZaneParser::action29_function_type(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* params, ast::nodes::TypeExpression* return_type)
#line 316 "src/grammar/parser.gr"
{
		return new ast::nodes::FunctionType(
			grammarSupport::takeValue(params),
			grammarSupport::takePtr(return_type)
		);
	 }
#line 376 "src/grammar/parser.cc"

// [30] method_type[ast::nodes::MethodType*] -> ( this params:type_list_ne ) -> return_type:type_expr
inline ast::nodes::MethodType* ZaneParser::action30_method_type(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* params, ast::nodes::TypeExpression* return_type)
#line 327 "src/grammar/parser.gr"
{
		return new ast::nodes::MethodType(
			grammarSupport::takeValue(params),
			grammarSupport::takePtr(return_type),
			false
		);
	 }
#line 388 "src/grammar/parser.cc"

// [31] method_type[ast::nodes::MethodType*] -> ( this params:type_list_ne ) mut -> return_type:type_expr
inline ast::nodes::MethodType* ZaneParser::action31_method_type(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* params, ast::nodes::TypeExpression* return_type)
#line 334 "src/grammar/parser.gr"
{
		return new ast::nodes::MethodType(
			grammarSupport::takeValue(params),
			grammarSupport::takePtr(return_type),
			true
		);
	 }
#line 400 "src/grammar/parser.cc"

// [32] arrow_body[ast::nodes::ArrowBody*] -> => value:value_expr
inline ast::nodes::ArrowBody* ZaneParser::action32_arrow_body(SourceLoc loc, ast::nodes::ValueExpr* value)
#line 346 "src/grammar/parser.gr"
{
		return new ast::nodes::ArrowBody(grammarSupport::takePtr(value));
	 }
#line 408 "src/grammar/parser.cc"

// [33] function_body[grammarSupport::FunctionBody*] -> body:arrow_body
inline grammarSupport::FunctionBody* ZaneParser::action33_function_body(SourceLoc loc, ast::nodes::ArrowBody* body)
#line 354 "src/grammar/parser.gr"
{
		return new grammarSupport::FunctionBody(grammarSupport::takeValue(body));
	 }
#line 416 "src/grammar/parser.cc"

// [34] function_body[grammarSupport::FunctionBody*] -> body:scope
inline grammarSupport::FunctionBody* ZaneParser::action34_function_body(SourceLoc loc, ast::nodes::Scope* body)
#line 357 "src/grammar/parser.gr"
{
		return new grammarSupport::FunctionBody(grammarSupport::takeValue(body));
	 }
#line 424 "src/grammar/parser.cc"

// [35] scope[ast::nodes::Scope*] -> { TOK_LINEBREAK statements:statements TOK_LINEBREAK }
inline ast::nodes::Scope* ZaneParser::action35_scope(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::Statement>>* statements)
#line 365 "src/grammar/parser.gr"
{
		return new ast::nodes::Scope(grammarSupport::takeValue(statements));
	 }
#line 432 "src/grammar/parser.cc"

// [36] statements[std::vector<std::unique_ptr<ast::nodes::Statement>>*] -> empty
inline std::vector<std::unique_ptr<ast::nodes::Statement>>* ZaneParser::action36_statements(SourceLoc loc)
#line 373 "src/grammar/parser.gr"
{
		return new std::vector<std::unique_ptr<ast::nodes::Statement>>();
	 }
#line 440 "src/grammar/parser.cc"

// [37] statements[std::vector<std::unique_ptr<ast::nodes::Statement>>*] -> list:statements TOK_LINEBREAK statement:statement
inline std::vector<std::unique_ptr<ast::nodes::Statement>>* ZaneParser::action37_statements(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::Statement>>* list, ast::nodes::Statement* statement)
#line 376 "src/grammar/parser.gr"
{
		list->push_back(grammarSupport::takePtr(statement));
		return list;
	 }
#line 449 "src/grammar/parser.cc"

// [38] function_call[ast::nodes::FunctionCall*] -> callee:value_expr ( args:arguments )
inline ast::nodes::FunctionCall* ZaneParser::action38_function_call(SourceLoc loc, ast::nodes::ValueExpr* callee, std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* args)
#line 385 "src/grammar/parser.gr"
{
		return new ast::nodes::FunctionCall(
			std::make_unique<ast::nodes::ValueExpr>(grammarSupport::takeValue(callee)),
			grammarSupport::takeValue(args)
		);
	 }
#line 460 "src/grammar/parser.cc"

// [39] statement[ast::nodes::Statement*] -> call:function_call
inline ast::nodes::Statement* ZaneParser::action39_statement(SourceLoc loc, ast::nodes::FunctionCall* call)
#line 396 "src/grammar/parser.gr"
{
		return new ast::nodes::Statement(grammarSupport::takeValue(call));
	 }
#line 468 "src/grammar/parser.cc"

// [40] statement[ast::nodes::Statement*] -> declaration:variable_decl
inline ast::nodes::Statement* ZaneParser::action40_statement(SourceLoc loc, ast::nodes::VariableDecl* declaration)
#line 399 "src/grammar/parser.gr"
{
		return new ast::nodes::Statement(grammarSupport::takeValue(declaration));
	 }
#line 476 "src/grammar/parser.cc"

// [41] value_expr[ast::nodes::ValueExpr*] -> identifier:TOK_IDENT
inline ast::nodes::ValueExpr* ZaneParser::action41_value_expr(SourceLoc loc, std::string* identifier)
#line 407 "src/grammar/parser.gr"
{
		return new ast::nodes::ValueExpr(ast::nodes::ValueSymbol(grammarSupport::takeString(identifier)));
	 }
#line 484 "src/grammar/parser.cc"

// [42] value_expr[ast::nodes::ValueExpr*] -> package:TOK_IDENT $ identifier:TOK_IDENT
inline ast::nodes::ValueExpr* ZaneParser::action42_value_expr(SourceLoc loc, std::string* package, std::string* identifier)
#line 410 "src/grammar/parser.gr"
{
		return new ast::nodes::ValueExpr(
			ast::nodes::PackageValueSymbol(
				grammarSupport::takeString(identifier),
				grammarSupport::takeString(package)
			)
		);
	 }
#line 497 "src/grammar/parser.cc"

// [43] value_expr[ast::nodes::ValueExpr*] -> @ package:TOK_IDENT $ identifier:TOK_IDENT
inline ast::nodes::ValueExpr* ZaneParser::action43_value_expr(SourceLoc loc, std::string* package, std::string* identifier)
#line 418 "src/grammar/parser.gr"
{
		return new ast::nodes::ValueExpr(
			ast::nodes::IntrinsicValueSymbol(
				grammarSupport::takeString(identifier),
				grammarSupport::takeString(package)
			)
		);
	 }
#line 510 "src/grammar/parser.cc"

// [44] value_expr[ast::nodes::ValueExpr*] -> integer:TOK_INT
inline ast::nodes::ValueExpr* ZaneParser::action44_value_expr(SourceLoc loc, std::string* integer)
#line 426 "src/grammar/parser.gr"
{
		return new ast::nodes::ValueExpr(ast::nodes::IntLiteral(grammarSupport::takeString(integer)));
	 }
#line 518 "src/grammar/parser.cc"

// [45] value_expr[ast::nodes::ValueExpr*] -> number:TOK_FLOAT
inline ast::nodes::ValueExpr* ZaneParser::action45_value_expr(SourceLoc loc, std::string* number)
#line 429 "src/grammar/parser.gr"
{
		return new ast::nodes::ValueExpr(ast::nodes::FloatLiteral(grammarSupport::takeString(number)));
	 }
#line 526 "src/grammar/parser.cc"

// [46] value_expr[ast::nodes::ValueExpr*] -> text:TOK_STRING
inline ast::nodes::ValueExpr* ZaneParser::action46_value_expr(SourceLoc loc, std::string* text)
#line 432 "src/grammar/parser.gr"
{
		return new ast::nodes::ValueExpr(ast::nodes::StringLiteral(grammarSupport::takeString(text)));
	 }
#line 534 "src/grammar/parser.cc"

// [47] value_expr[ast::nodes::ValueExpr*] -> value:parenthized_value
inline ast::nodes::ValueExpr* ZaneParser::action47_value_expr(SourceLoc loc, ast::nodes::ParenthizedValue* value)
#line 435 "src/grammar/parser.gr"
{
		return new ast::nodes::ValueExpr(grammarSupport::takeValue(value));
	 }
#line 542 "src/grammar/parser.cc"

// [48] value_expr[ast::nodes::ValueExpr*] -> call:function_call
inline ast::nodes::ValueExpr* ZaneParser::action48_value_expr(SourceLoc loc, ast::nodes::FunctionCall* call)
#line 438 "src/grammar/parser.gr"
{
		return new ast::nodes::ValueExpr(grammarSupport::takeValue(call));
	 }
#line 550 "src/grammar/parser.cc"

// [49] value_expr[ast::nodes::ValueExpr*] -> ~ expr:value_expr %prec(30)
inline ast::nodes::ValueExpr* ZaneParser::action49_value_expr(SourceLoc loc, ast::nodes::ValueExpr* expr)
#line 441 "src/grammar/parser.gr"
{
		return grammarSupport::makeFlip(expr);
	 }
#line 558 "src/grammar/parser.cc"

// [50] value_expr[ast::nodes::ValueExpr*] -> left:value_expr * right:value_expr %prec(20)
inline ast::nodes::ValueExpr* ZaneParser::action50_value_expr(SourceLoc loc, ast::nodes::ValueExpr* left, ast::nodes::ValueExpr* right)
#line 444 "src/grammar/parser.gr"
{
		return grammarSupport::makeBinary("*", left, right);
	 }
#line 566 "src/grammar/parser.cc"

// [51] value_expr[ast::nodes::ValueExpr*] -> left:value_expr / right:value_expr %prec(20)
inline ast::nodes::ValueExpr* ZaneParser::action51_value_expr(SourceLoc loc, ast::nodes::ValueExpr* left, ast::nodes::ValueExpr* right)
#line 447 "src/grammar/parser.gr"
{
		return grammarSupport::makeBinary("/", left, right);
	 }
#line 574 "src/grammar/parser.cc"

// [52] value_expr[ast::nodes::ValueExpr*] -> left:value_expr + right:value_expr %prec(10)
inline ast::nodes::ValueExpr* ZaneParser::action52_value_expr(SourceLoc loc, ast::nodes::ValueExpr* left, ast::nodes::ValueExpr* right)
#line 450 "src/grammar/parser.gr"
{
		return grammarSupport::makeBinary("+", left, right);
	 }
#line 582 "src/grammar/parser.cc"

// [53] value_expr[ast::nodes::ValueExpr*] -> left:value_expr - right:value_expr %prec(10)
inline ast::nodes::ValueExpr* ZaneParser::action53_value_expr(SourceLoc loc, ast::nodes::ValueExpr* left, ast::nodes::ValueExpr* right)
#line 453 "src/grammar/parser.gr"
{
		return grammarSupport::makeBinary("-", left, right);
	 }
#line 590 "src/grammar/parser.cc"

// [54] parenthized_value[ast::nodes::ParenthizedValue*] -> ( value:value_expr )
inline ast::nodes::ParenthizedValue* ZaneParser::action54_parenthized_value(SourceLoc loc, ast::nodes::ValueExpr* value)
#line 461 "src/grammar/parser.gr"
{
		return new ast::nodes::ParenthizedValue(grammarSupport::takePtr(value));
	 }
#line 598 "src/grammar/parser.cc"

// [55] arguments[std::vector<std::unique_ptr<ast::nodes::ValueExpr>>*] -> empty
inline std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* ZaneParser::action55_arguments(SourceLoc loc)
#line 469 "src/grammar/parser.gr"
{
		return new std::vector<std::unique_ptr<ast::nodes::ValueExpr>>();
	 }
#line 606 "src/grammar/parser.cc"

// [56] arguments[std::vector<std::unique_ptr<ast::nodes::ValueExpr>>*] -> list:argument_list
inline std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* ZaneParser::action56_arguments(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* list)
#line 472 "src/grammar/parser.gr"
{
		return list;
	 }
#line 614 "src/grammar/parser.cc"

// [57] argument_list[std::vector<std::unique_ptr<ast::nodes::ValueExpr>>*] -> value:value_expr
inline std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* ZaneParser::action57_argument_list(SourceLoc loc, ast::nodes::ValueExpr* value)
#line 480 "src/grammar/parser.gr"
{
		auto* list = new std::vector<std::unique_ptr<ast::nodes::ValueExpr>>();
		list->push_back(grammarSupport::takePtr(value));
		return list;
	 }
#line 624 "src/grammar/parser.cc"

// [58] argument_list[std::vector<std::unique_ptr<ast::nodes::ValueExpr>>*] -> list:argument_list , value:value_expr
inline std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* ZaneParser::action58_argument_list(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* list, ast::nodes::ValueExpr* value)
#line 485 "src/grammar/parser.gr"
{
		list->push_back(grammarSupport::takePtr(value));
		return list;
	 }
#line 633 "src/grammar/parser.cc"


/*static*/ SemanticValue ZaneParser::doReductionAction(
  ZaneParser *ths,
  int productionId, SemanticValue const *semanticValues,
  SourceLoc loc)
{
  switch (productionId) {
    case 0:
      return (SemanticValue)(ths->action0___EarlyStartSymbol(loc, (int)(semanticValues[0])));
    case 1:
      return (SemanticValue)(ths->action1_may_break(loc));
    case 2:
      return (SemanticValue)(ths->action2_may_break(loc));
    case 3:
      return (SemanticValue)(ths->action3_package(loc, (std::vector<ast::nodes::Declaration>*)(semanticValues[1])));
    case 4:
      return (SemanticValue)(ths->action4_global_scope(loc));
    case 5:
      return (SemanticValue)(ths->action5_global_scope(loc, (ast::nodes::Declaration*)(semanticValues[0])));
    case 6:
      return (SemanticValue)(ths->action6_global_scope(loc, (std::vector<ast::nodes::Declaration>*)(semanticValues[0]), (ast::nodes::Declaration*)(semanticValues[2])));
    case 7:
      return (SemanticValue)(ths->action7_declaration(loc, (ast::nodes::FunctionDecl*)(semanticValues[0])));
    case 8:
      return (SemanticValue)(ths->action8_declaration(loc, (ast::nodes::MethodDecl*)(semanticValues[0])));
    case 9:
      return (SemanticValue)(ths->action9_variable_decl(loc, (std::string*)(semanticValues[0]), (ast::nodes::TypeExpression*)(semanticValues[1]), (ast::nodes::ValueExpr*)(semanticValues[3])));
    case 10:
      return (SemanticValue)(ths->action10_function_decl(loc, (ast::nodes::TypeExpression*)(semanticValues[0]), (std::string*)(semanticValues[1]), (std::vector<ast::nodes::Parameter>*)(semanticValues[3]), (grammarSupport::FunctionBody*)(semanticValues[5])));
    case 11:
      return (SemanticValue)(ths->action11_method_decl(loc, (ast::nodes::TypeExpression*)(semanticValues[0]), (std::string*)(semanticValues[1]), (std::vector<ast::nodes::Parameter>*)(semanticValues[3]), (grammarSupport::FunctionBody*)(semanticValues[5])));
    case 12:
      return (SemanticValue)(ths->action12_method_decl(loc, (ast::nodes::TypeExpression*)(semanticValues[0]), (std::string*)(semanticValues[1]), (std::vector<ast::nodes::Parameter>*)(semanticValues[3]), (grammarSupport::FunctionBody*)(semanticValues[6])));
    case 13:
      return (SemanticValue)(ths->action13_parameters(loc));
    case 14:
      return (SemanticValue)(ths->action14_parameters(loc, (std::vector<ast::nodes::Parameter>*)(semanticValues[0])));
    case 15:
      return (SemanticValue)(ths->action15_parameter_list(loc, (ast::nodes::Parameter*)(semanticValues[0])));
    case 16:
      return (SemanticValue)(ths->action16_parameter_list(loc, (std::vector<ast::nodes::Parameter>*)(semanticValues[0]), (ast::nodes::Parameter*)(semanticValues[2])));
    case 17:
      return (SemanticValue)(ths->action17_method_parameters(loc, (std::vector<ast::nodes::Parameter>*)(semanticValues[0])));
    case 18:
      return (SemanticValue)(ths->action18_method_parameter_seq(loc, (ast::nodes::TypeExpression*)(semanticValues[1])));
    case 19:
      return (SemanticValue)(ths->action19_method_parameter_seq(loc, (std::vector<ast::nodes::Parameter>*)(semanticValues[0]), (ast::nodes::Parameter*)(semanticValues[2])));
    case 20:
      return (SemanticValue)(ths->action20_parameter(loc, (std::string*)(semanticValues[0]), (ast::nodes::TypeExpression*)(semanticValues[1])));
    case 21:
      return (SemanticValue)(ths->action21_type_list(loc));
    case 22:
      return (SemanticValue)(ths->action22_type_list(loc, (std::vector<std::unique_ptr<ast::nodes::TypeExpression>>*)(semanticValues[0])));
    case 23:
      return (SemanticValue)(ths->action23_type_list_ne(loc, (ast::nodes::TypeExpression*)(semanticValues[0])));
    case 24:
      return (SemanticValue)(ths->action24_type_list_ne(loc, (std::vector<std::unique_ptr<ast::nodes::TypeExpression>>*)(semanticValues[0]), (ast::nodes::TypeExpression*)(semanticValues[2])));
    case 25:
      return (SemanticValue)(ths->action25_type_expr(loc, (ast::nodes::NameType*)(semanticValues[0])));
    case 26:
      return (SemanticValue)(ths->action26_type_expr(loc, (ast::nodes::FunctionType*)(semanticValues[0])));
    case 27:
      return (SemanticValue)(ths->action27_type_expr(loc, (ast::nodes::MethodType*)(semanticValues[0])));
    case 28:
      return (SemanticValue)(ths->action28_name_type(loc, (std::string*)(semanticValues[0])));
    case 29:
      return (SemanticValue)(ths->action29_function_type(loc, (std::vector<std::unique_ptr<ast::nodes::TypeExpression>>*)(semanticValues[1]), (ast::nodes::TypeExpression*)(semanticValues[4])));
    case 30:
      return (SemanticValue)(ths->action30_method_type(loc, (std::vector<std::unique_ptr<ast::nodes::TypeExpression>>*)(semanticValues[2]), (ast::nodes::TypeExpression*)(semanticValues[5])));
    case 31:
      return (SemanticValue)(ths->action31_method_type(loc, (std::vector<std::unique_ptr<ast::nodes::TypeExpression>>*)(semanticValues[2]), (ast::nodes::TypeExpression*)(semanticValues[6])));
    case 32:
      return (SemanticValue)(ths->action32_arrow_body(loc, (ast::nodes::ValueExpr*)(semanticValues[1])));
    case 33:
      return (SemanticValue)(ths->action33_function_body(loc, (ast::nodes::ArrowBody*)(semanticValues[0])));
    case 34:
      return (SemanticValue)(ths->action34_function_body(loc, (ast::nodes::Scope*)(semanticValues[0])));
    case 35:
      return (SemanticValue)(ths->action35_scope(loc, (std::vector<std::unique_ptr<ast::nodes::Statement>>*)(semanticValues[2])));
    case 36:
      return (SemanticValue)(ths->action36_statements(loc));
    case 37:
      return (SemanticValue)(ths->action37_statements(loc, (std::vector<std::unique_ptr<ast::nodes::Statement>>*)(semanticValues[0]), (ast::nodes::Statement*)(semanticValues[2])));
    case 38:
      return (SemanticValue)(ths->action38_function_call(loc, (ast::nodes::ValueExpr*)(semanticValues[0]), (std::vector<std::unique_ptr<ast::nodes::ValueExpr>>*)(semanticValues[2])));
    case 39:
      return (SemanticValue)(ths->action39_statement(loc, (ast::nodes::FunctionCall*)(semanticValues[0])));
    case 40:
      return (SemanticValue)(ths->action40_statement(loc, (ast::nodes::VariableDecl*)(semanticValues[0])));
    case 41:
      return (SemanticValue)(ths->action41_value_expr(loc, (std::string*)(semanticValues[0])));
    case 42:
      return (SemanticValue)(ths->action42_value_expr(loc, (std::string*)(semanticValues[0]), (std::string*)(semanticValues[2])));
    case 43:
      return (SemanticValue)(ths->action43_value_expr(loc, (std::string*)(semanticValues[1]), (std::string*)(semanticValues[3])));
    case 44:
      return (SemanticValue)(ths->action44_value_expr(loc, (std::string*)(semanticValues[0])));
    case 45:
      return (SemanticValue)(ths->action45_value_expr(loc, (std::string*)(semanticValues[0])));
    case 46:
      return (SemanticValue)(ths->action46_value_expr(loc, (std::string*)(semanticValues[0])));
    case 47:
      return (SemanticValue)(ths->action47_value_expr(loc, (ast::nodes::ParenthizedValue*)(semanticValues[0])));
    case 48:
      return (SemanticValue)(ths->action48_value_expr(loc, (ast::nodes::FunctionCall*)(semanticValues[0])));
    case 49:
      return (SemanticValue)(ths->action49_value_expr(loc, (ast::nodes::ValueExpr*)(semanticValues[1])));
    case 50:
      return (SemanticValue)(ths->action50_value_expr(loc, (ast::nodes::ValueExpr*)(semanticValues[0]), (ast::nodes::ValueExpr*)(semanticValues[2])));
    case 51:
      return (SemanticValue)(ths->action51_value_expr(loc, (ast::nodes::ValueExpr*)(semanticValues[0]), (ast::nodes::ValueExpr*)(semanticValues[2])));
    case 52:
      return (SemanticValue)(ths->action52_value_expr(loc, (ast::nodes::ValueExpr*)(semanticValues[0]), (ast::nodes::ValueExpr*)(semanticValues[2])));
    case 53:
      return (SemanticValue)(ths->action53_value_expr(loc, (ast::nodes::ValueExpr*)(semanticValues[0]), (ast::nodes::ValueExpr*)(semanticValues[2])));
    case 54:
      return (SemanticValue)(ths->action54_parenthized_value(loc, (ast::nodes::ValueExpr*)(semanticValues[1])));
    case 55:
      return (SemanticValue)(ths->action55_arguments(loc));
    case 56:
      return (SemanticValue)(ths->action56_arguments(loc, (std::vector<std::unique_ptr<ast::nodes::ValueExpr>>*)(semanticValues[0])));
    case 57:
      return (SemanticValue)(ths->action57_argument_list(loc, (ast::nodes::ValueExpr*)(semanticValues[0])));
    case 58:
      return (SemanticValue)(ths->action58_argument_list(loc, (std::vector<std::unique_ptr<ast::nodes::ValueExpr>>*)(semanticValues[0]), (ast::nodes::ValueExpr*)(semanticValues[2])));
    default:
      assert(!"invalid production code");
      return (SemanticValue)0;   // silence warning
  }
}

UserActions::ReductionActionFunc ZaneParser::getReductionAction()
{
  return (ReductionActionFunc)&ZaneParser::doReductionAction;
}


// ---------------- dup/del/merge/keep nonterminals ---------------

inline int ZaneParser::dup_may_break(int p) 
#line 115 "src/grammar/parser.gr"
{return p; }
#line 777 "src/grammar/parser.cc"

inline void ZaneParser::del_may_break(int p) 
#line 116 "src/grammar/parser.gr"
{ }
#line 782 "src/grammar/parser.cc"

inline ast::nodes::Package* ZaneParser::dup_package(ast::nodes::Package* p) 
#line 122 "src/grammar/parser.gr"
{return p; }
#line 787 "src/grammar/parser.cc"

inline void ZaneParser::del_package(ast::nodes::Package* p) 
#line 123 "src/grammar/parser.gr"
{ }
#line 792 "src/grammar/parser.cc"

inline std::vector<ast::nodes::Declaration>* ZaneParser::dup_global_scope(std::vector<ast::nodes::Declaration>* p) 
#line 130 "src/grammar/parser.gr"
{return p; }
#line 797 "src/grammar/parser.cc"

inline void ZaneParser::del_global_scope(std::vector<ast::nodes::Declaration>* p) 
#line 131 "src/grammar/parser.gr"
{ }
#line 802 "src/grammar/parser.cc"

inline ast::nodes::Declaration* ZaneParser::dup_declaration(ast::nodes::Declaration* p) 
#line 147 "src/grammar/parser.gr"
{return p; }
#line 807 "src/grammar/parser.cc"

inline void ZaneParser::del_declaration(ast::nodes::Declaration* p) 
#line 148 "src/grammar/parser.gr"
{ }
#line 812 "src/grammar/parser.cc"

inline ast::nodes::VariableDecl* ZaneParser::dup_variable_decl(ast::nodes::VariableDecl* p) 
#line 158 "src/grammar/parser.gr"
{return p; }
#line 817 "src/grammar/parser.cc"

inline void ZaneParser::del_variable_decl(ast::nodes::VariableDecl* p) 
#line 159 "src/grammar/parser.gr"
{ }
#line 822 "src/grammar/parser.cc"

inline ast::nodes::FunctionDecl* ZaneParser::dup_function_decl(ast::nodes::FunctionDecl* p) 
#line 170 "src/grammar/parser.gr"
{return p; }
#line 827 "src/grammar/parser.cc"

inline void ZaneParser::del_function_decl(ast::nodes::FunctionDecl* p) 
#line 171 "src/grammar/parser.gr"
{ }
#line 832 "src/grammar/parser.cc"

inline ast::nodes::MethodDecl* ZaneParser::dup_method_decl(ast::nodes::MethodDecl* p) 
#line 183 "src/grammar/parser.gr"
{return p; }
#line 837 "src/grammar/parser.cc"

inline void ZaneParser::del_method_decl(ast::nodes::MethodDecl* p) 
#line 184 "src/grammar/parser.gr"
{ }
#line 842 "src/grammar/parser.cc"

inline std::vector<ast::nodes::Parameter>* ZaneParser::dup_parameters(std::vector<ast::nodes::Parameter>* p) 
#line 206 "src/grammar/parser.gr"
{return p; }
#line 847 "src/grammar/parser.cc"

inline void ZaneParser::del_parameters(std::vector<ast::nodes::Parameter>* p) 
#line 207 "src/grammar/parser.gr"
{ }
#line 852 "src/grammar/parser.cc"

inline std::vector<ast::nodes::Parameter>* ZaneParser::dup_parameter_list(std::vector<ast::nodes::Parameter>* p) 
#line 217 "src/grammar/parser.gr"
{return p; }
#line 857 "src/grammar/parser.cc"

inline void ZaneParser::del_parameter_list(std::vector<ast::nodes::Parameter>* p) 
#line 218 "src/grammar/parser.gr"
{ }
#line 862 "src/grammar/parser.cc"

inline std::vector<ast::nodes::Parameter>* ZaneParser::dup_method_parameters(std::vector<ast::nodes::Parameter>* p) 
#line 231 "src/grammar/parser.gr"
{return p; }
#line 867 "src/grammar/parser.cc"

inline void ZaneParser::del_method_parameters(std::vector<ast::nodes::Parameter>* p) 
#line 232 "src/grammar/parser.gr"
{ }
#line 872 "src/grammar/parser.cc"

inline std::vector<ast::nodes::Parameter>* ZaneParser::dup_method_parameter_seq(std::vector<ast::nodes::Parameter>* p) 
#line 239 "src/grammar/parser.gr"
{return p; }
#line 877 "src/grammar/parser.cc"

inline void ZaneParser::del_method_parameter_seq(std::vector<ast::nodes::Parameter>* p) 
#line 240 "src/grammar/parser.gr"
{ }
#line 882 "src/grammar/parser.cc"

inline ast::nodes::Parameter* ZaneParser::dup_parameter(ast::nodes::Parameter* p) 
#line 253 "src/grammar/parser.gr"
{return p; }
#line 887 "src/grammar/parser.cc"

inline void ZaneParser::del_parameter(ast::nodes::Parameter* p) 
#line 254 "src/grammar/parser.gr"
{ }
#line 892 "src/grammar/parser.cc"

inline std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* ZaneParser::dup_type_list(std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* p) 
#line 264 "src/grammar/parser.gr"
{return p; }
#line 897 "src/grammar/parser.cc"

inline void ZaneParser::del_type_list(std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* p) 
#line 265 "src/grammar/parser.gr"
{ }
#line 902 "src/grammar/parser.cc"

inline std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* ZaneParser::dup_type_list_ne(std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* p) 
#line 275 "src/grammar/parser.gr"
{return p; }
#line 907 "src/grammar/parser.cc"

inline void ZaneParser::del_type_list_ne(std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* p) 
#line 276 "src/grammar/parser.gr"
{ }
#line 912 "src/grammar/parser.cc"

inline ast::nodes::TypeExpression* ZaneParser::dup_type_expr(ast::nodes::TypeExpression* p) 
#line 289 "src/grammar/parser.gr"
{return p; }
#line 917 "src/grammar/parser.cc"

inline void ZaneParser::del_type_expr(ast::nodes::TypeExpression* p) 
#line 290 "src/grammar/parser.gr"
{ }
#line 922 "src/grammar/parser.cc"

inline ast::nodes::NameType* ZaneParser::dup_name_type(ast::nodes::NameType* p) 
#line 303 "src/grammar/parser.gr"
{return p; }
#line 927 "src/grammar/parser.cc"

inline void ZaneParser::del_name_type(ast::nodes::NameType* p) 
#line 304 "src/grammar/parser.gr"
{ }
#line 932 "src/grammar/parser.cc"

inline ast::nodes::FunctionType* ZaneParser::dup_function_type(ast::nodes::FunctionType* p) 
#line 314 "src/grammar/parser.gr"
{return p; }
#line 937 "src/grammar/parser.cc"

inline void ZaneParser::del_function_type(ast::nodes::FunctionType* p) 
#line 315 "src/grammar/parser.gr"
{ }
#line 942 "src/grammar/parser.cc"

inline ast::nodes::MethodType* ZaneParser::dup_method_type(ast::nodes::MethodType* p) 
#line 325 "src/grammar/parser.gr"
{return p; }
#line 947 "src/grammar/parser.cc"

inline void ZaneParser::del_method_type(ast::nodes::MethodType* p) 
#line 326 "src/grammar/parser.gr"
{ }
#line 952 "src/grammar/parser.cc"

inline ast::nodes::ArrowBody* ZaneParser::dup_arrow_body(ast::nodes::ArrowBody* p) 
#line 344 "src/grammar/parser.gr"
{return p; }
#line 957 "src/grammar/parser.cc"

inline void ZaneParser::del_arrow_body(ast::nodes::ArrowBody* p) 
#line 345 "src/grammar/parser.gr"
{ }
#line 962 "src/grammar/parser.cc"

inline grammarSupport::FunctionBody* ZaneParser::dup_function_body(grammarSupport::FunctionBody* p) 
#line 352 "src/grammar/parser.gr"
{return p; }
#line 967 "src/grammar/parser.cc"

inline void ZaneParser::del_function_body(grammarSupport::FunctionBody* p) 
#line 353 "src/grammar/parser.gr"
{ }
#line 972 "src/grammar/parser.cc"

inline ast::nodes::Scope* ZaneParser::dup_scope(ast::nodes::Scope* p) 
#line 363 "src/grammar/parser.gr"
{return p; }
#line 977 "src/grammar/parser.cc"

inline void ZaneParser::del_scope(ast::nodes::Scope* p) 
#line 364 "src/grammar/parser.gr"
{ }
#line 982 "src/grammar/parser.cc"

inline std::vector<std::unique_ptr<ast::nodes::Statement>>* ZaneParser::dup_statements(std::vector<std::unique_ptr<ast::nodes::Statement>>* p) 
#line 371 "src/grammar/parser.gr"
{return p; }
#line 987 "src/grammar/parser.cc"

inline void ZaneParser::del_statements(std::vector<std::unique_ptr<ast::nodes::Statement>>* p) 
#line 372 "src/grammar/parser.gr"
{ }
#line 992 "src/grammar/parser.cc"

inline ast::nodes::FunctionCall* ZaneParser::dup_function_call(ast::nodes::FunctionCall* p) 
#line 383 "src/grammar/parser.gr"
{return p; }
#line 997 "src/grammar/parser.cc"

inline void ZaneParser::del_function_call(ast::nodes::FunctionCall* p) 
#line 384 "src/grammar/parser.gr"
{ }
#line 1002 "src/grammar/parser.cc"

inline ast::nodes::Statement* ZaneParser::dup_statement(ast::nodes::Statement* p) 
#line 394 "src/grammar/parser.gr"
{return p; }
#line 1007 "src/grammar/parser.cc"

inline void ZaneParser::del_statement(ast::nodes::Statement* p) 
#line 395 "src/grammar/parser.gr"
{ }
#line 1012 "src/grammar/parser.cc"

inline ast::nodes::ValueExpr* ZaneParser::dup_value_expr(ast::nodes::ValueExpr* p) 
#line 405 "src/grammar/parser.gr"
{return p; }
#line 1017 "src/grammar/parser.cc"

inline void ZaneParser::del_value_expr(ast::nodes::ValueExpr* p) 
#line 406 "src/grammar/parser.gr"
{ }
#line 1022 "src/grammar/parser.cc"

inline ast::nodes::ParenthizedValue* ZaneParser::dup_parenthized_value(ast::nodes::ParenthizedValue* p) 
#line 459 "src/grammar/parser.gr"
{return p; }
#line 1027 "src/grammar/parser.cc"

inline void ZaneParser::del_parenthized_value(ast::nodes::ParenthizedValue* p) 
#line 460 "src/grammar/parser.gr"
{ }
#line 1032 "src/grammar/parser.cc"

inline std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* ZaneParser::dup_arguments(std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* p) 
#line 467 "src/grammar/parser.gr"
{return p; }
#line 1037 "src/grammar/parser.cc"

inline void ZaneParser::del_arguments(std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* p) 
#line 468 "src/grammar/parser.gr"
{ }
#line 1042 "src/grammar/parser.cc"

inline std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* ZaneParser::dup_argument_list(std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* p) 
#line 478 "src/grammar/parser.gr"
{return p; }
#line 1047 "src/grammar/parser.cc"

inline void ZaneParser::del_argument_list(std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* p) 
#line 479 "src/grammar/parser.gr"
{ }
#line 1052 "src/grammar/parser.cc"

SemanticValue ZaneParser::duplicateNontermValue(int nontermId, SemanticValue sval)
{
  switch (nontermId) {
    case 2:
      return (SemanticValue)dup_may_break((int)sval);
    case 3:
      return (SemanticValue)dup_package((ast::nodes::Package*)sval);
    case 4:
      return (SemanticValue)dup_global_scope((std::vector<ast::nodes::Declaration>*)sval);
    case 5:
      return (SemanticValue)dup_declaration((ast::nodes::Declaration*)sval);
    case 6:
      return (SemanticValue)dup_variable_decl((ast::nodes::VariableDecl*)sval);
    case 7:
      return (SemanticValue)dup_function_decl((ast::nodes::FunctionDecl*)sval);
    case 8:
      return (SemanticValue)dup_method_decl((ast::nodes::MethodDecl*)sval);
    case 9:
      return (SemanticValue)dup_parameters((std::vector<ast::nodes::Parameter>*)sval);
    case 10:
      return (SemanticValue)dup_parameter_list((std::vector<ast::nodes::Parameter>*)sval);
    case 11:
      return (SemanticValue)dup_method_parameters((std::vector<ast::nodes::Parameter>*)sval);
    case 12:
      return (SemanticValue)dup_method_parameter_seq((std::vector<ast::nodes::Parameter>*)sval);
    case 13:
      return (SemanticValue)dup_parameter((ast::nodes::Parameter*)sval);
    case 14:
      return (SemanticValue)dup_type_list((std::vector<std::unique_ptr<ast::nodes::TypeExpression>>*)sval);
    case 15:
      return (SemanticValue)dup_type_list_ne((std::vector<std::unique_ptr<ast::nodes::TypeExpression>>*)sval);
    case 16:
      return (SemanticValue)dup_type_expr((ast::nodes::TypeExpression*)sval);
    case 17:
      return (SemanticValue)dup_name_type((ast::nodes::NameType*)sval);
    case 18:
      return (SemanticValue)dup_function_type((ast::nodes::FunctionType*)sval);
    case 19:
      return (SemanticValue)dup_method_type((ast::nodes::MethodType*)sval);
    case 20:
      return (SemanticValue)dup_arrow_body((ast::nodes::ArrowBody*)sval);
    case 21:
      return (SemanticValue)dup_function_body((grammarSupport::FunctionBody*)sval);
    case 22:
      return (SemanticValue)dup_scope((ast::nodes::Scope*)sval);
    case 23:
      return (SemanticValue)dup_statements((std::vector<std::unique_ptr<ast::nodes::Statement>>*)sval);
    case 24:
      return (SemanticValue)dup_function_call((ast::nodes::FunctionCall*)sval);
    case 25:
      return (SemanticValue)dup_statement((ast::nodes::Statement*)sval);
    case 26:
      return (SemanticValue)dup_value_expr((ast::nodes::ValueExpr*)sval);
    case 27:
      return (SemanticValue)dup_parenthized_value((ast::nodes::ParenthizedValue*)sval);
    case 28:
      return (SemanticValue)dup_arguments((std::vector<std::unique_ptr<ast::nodes::ValueExpr>>*)sval);
    case 29:
      return (SemanticValue)dup_argument_list((std::vector<std::unique_ptr<ast::nodes::ValueExpr>>*)sval);
    default:
      return (SemanticValue)0;
  }
}

void ZaneParser::deallocateNontermValue(int nontermId, SemanticValue sval)
{
  switch (nontermId) {
    case 2:
      del_may_break((int)sval);
      return;
    case 3:
      del_package((ast::nodes::Package*)sval);
      return;
    case 4:
      del_global_scope((std::vector<ast::nodes::Declaration>*)sval);
      return;
    case 5:
      del_declaration((ast::nodes::Declaration*)sval);
      return;
    case 6:
      del_variable_decl((ast::nodes::VariableDecl*)sval);
      return;
    case 7:
      del_function_decl((ast::nodes::FunctionDecl*)sval);
      return;
    case 8:
      del_method_decl((ast::nodes::MethodDecl*)sval);
      return;
    case 9:
      del_parameters((std::vector<ast::nodes::Parameter>*)sval);
      return;
    case 10:
      del_parameter_list((std::vector<ast::nodes::Parameter>*)sval);
      return;
    case 11:
      del_method_parameters((std::vector<ast::nodes::Parameter>*)sval);
      return;
    case 12:
      del_method_parameter_seq((std::vector<ast::nodes::Parameter>*)sval);
      return;
    case 13:
      del_parameter((ast::nodes::Parameter*)sval);
      return;
    case 14:
      del_type_list((std::vector<std::unique_ptr<ast::nodes::TypeExpression>>*)sval);
      return;
    case 15:
      del_type_list_ne((std::vector<std::unique_ptr<ast::nodes::TypeExpression>>*)sval);
      return;
    case 16:
      del_type_expr((ast::nodes::TypeExpression*)sval);
      return;
    case 17:
      del_name_type((ast::nodes::NameType*)sval);
      return;
    case 18:
      del_function_type((ast::nodes::FunctionType*)sval);
      return;
    case 19:
      del_method_type((ast::nodes::MethodType*)sval);
      return;
    case 20:
      del_arrow_body((ast::nodes::ArrowBody*)sval);
      return;
    case 21:
      del_function_body((grammarSupport::FunctionBody*)sval);
      return;
    case 22:
      del_scope((ast::nodes::Scope*)sval);
      return;
    case 23:
      del_statements((std::vector<std::unique_ptr<ast::nodes::Statement>>*)sval);
      return;
    case 24:
      del_function_call((ast::nodes::FunctionCall*)sval);
      return;
    case 25:
      del_statement((ast::nodes::Statement*)sval);
      return;
    case 26:
      del_value_expr((ast::nodes::ValueExpr*)sval);
      return;
    case 27:
      del_parenthized_value((ast::nodes::ParenthizedValue*)sval);
      return;
    case 28:
      del_arguments((std::vector<std::unique_ptr<ast::nodes::ValueExpr>>*)sval);
      return;
    case 29:
      del_argument_list((std::vector<std::unique_ptr<ast::nodes::ValueExpr>>*)sval);
      return;
    default:
      std::cout << "WARNING: there is no action to deallocate nonterm "
           << nontermNames[nontermId] << std::endl;
  }
}

SemanticValue ZaneParser::mergeAlternativeParses(int nontermId, SemanticValue left,
                                           SemanticValue right,  SourceLoc loc)
{
  switch (nontermId) {
    default:
      std::cout << toString(loc) 
           << ": error: there is no action to merge nonterm "
           << nontermNames[nontermId] << std::endl;
      abort();
  }
}

bool ZaneParser::keepNontermValue(int nontermId, SemanticValue sval)
{
  switch (nontermId) {
    default:
      return true;
  }
}


// ---------------- dup/del/classify terminals ---------------
inline std::string* ZaneParser::dup_TOK_STRING(std::string* s) 
#line 91 "src/grammar/parser.gr"
{return new std::string(*s); }
#line 1236 "src/grammar/parser.cc"

inline void ZaneParser::del_TOK_STRING(std::string* s) 
#line 92 "src/grammar/parser.gr"
{delete s; }
#line 1241 "src/grammar/parser.cc"

inline std::string* ZaneParser::dup_TOK_IDENT(std::string* s) 
#line 95 "src/grammar/parser.gr"
{return new std::string(*s); }
#line 1246 "src/grammar/parser.cc"

inline void ZaneParser::del_TOK_IDENT(std::string* s) 
#line 96 "src/grammar/parser.gr"
{delete s; }
#line 1251 "src/grammar/parser.cc"

inline std::string* ZaneParser::dup_TOK_INT(std::string* s) 
#line 99 "src/grammar/parser.gr"
{return new std::string(*s); }
#line 1256 "src/grammar/parser.cc"

inline void ZaneParser::del_TOK_INT(std::string* s) 
#line 100 "src/grammar/parser.gr"
{delete s; }
#line 1261 "src/grammar/parser.cc"

inline std::string* ZaneParser::dup_TOK_FLOAT(std::string* s) 
#line 103 "src/grammar/parser.gr"
{return new std::string(*s); }
#line 1266 "src/grammar/parser.cc"

inline void ZaneParser::del_TOK_FLOAT(std::string* s) 
#line 104 "src/grammar/parser.gr"
{delete s; }
#line 1271 "src/grammar/parser.cc"

SemanticValue ZaneParser::duplicateTerminalValue(int termId, SemanticValue sval)
{
  switch (termId) {
    case 0:
      return sval;
    case 1:
      return sval;
    case 2:
      return sval;
    case 3:
      return sval;
    case 4:
      return sval;
    case 5:
      return sval;
    case 6:
      return sval;
    case 7:
      return sval;
    case 8:
      return sval;
    case 9:
      return sval;
    case 10:
      return sval;
    case 11:
      return sval;
    case 12:
      return sval;
    case 13:
      return sval;
    case 14:
      return (SemanticValue)dup_TOK_STRING((std::string*)sval);
    case 15:
      return (SemanticValue)dup_TOK_IDENT((std::string*)sval);
    case 16:
      return (SemanticValue)dup_TOK_INT((std::string*)sval);
    case 17:
      return (SemanticValue)dup_TOK_FLOAT((std::string*)sval);
    case 18:
      return sval;
    case 19:
      return sval;
    case 20:
      return sval;
    case 21:
      return sval;
    case 22:
      return sval;
    case 23:
      return sval;
    case 24:
      return sval;
    default:
      return (SemanticValue)0;
  }
}

void ZaneParser::deallocateTerminalValue(int termId, SemanticValue sval)
{
  switch (termId) {
    case 0:
      break;
    case 1:
      break;
    case 2:
      break;
    case 3:
      break;
    case 4:
      break;
    case 5:
      break;
    case 6:
      break;
    case 7:
      break;
    case 8:
      break;
    case 9:
      break;
    case 10:
      break;
    case 11:
      break;
    case 12:
      break;
    case 13:
      break;
    case 14:
      del_TOK_STRING((std::string*)sval);
      return;
    case 15:
      del_TOK_IDENT((std::string*)sval);
      return;
    case 16:
      del_TOK_INT((std::string*)sval);
      return;
    case 17:
      del_TOK_FLOAT((std::string*)sval);
      return;
    case 18:
      break;
    case 19:
      break;
    case 20:
      break;
    case 21:
      break;
    case 22:
      break;
    case 23:
      break;
    case 24:
      break;
    default:
      int arrayMin = 0;
      int arrayMax = 25;
      xassert(termId >= arrayMin && termId < arrayMax);
      std::cout << "WARNING: there is no action to deallocate terminal "
        << termNames[termId] << std::endl;
  }
}

/*static*/ int ZaneParser::reclassifyToken(ZaneParser *ths, int oldTokenType, SemanticValue sval)
{
  switch (oldTokenType) {
    default:
      return oldTokenType;
  }
}

UserActions::ReclassifyFunc ZaneParser::getReclassifier()
{
  return (ReclassifyFunc)&ZaneParser::reclassifyToken;
}


// this makes a ParseTables from some literal data;
// the code is written by ParseTables::emitConstructionCode()
// in /build/source/src/elkhound/parsetables.cc
class ZaneParser_ParseTables : public ParseTables {
public:
  ZaneParser_ParseTables();
};

ZaneParser_ParseTables::ZaneParser_ParseTables()
  : ParseTables(false /*owning*/)
{
  numTerms = 25;
  numNonterms = 30;
  numStates = 4;
  numProds = 59;
  actionCols = 25;
  actionRows = 4;
  gotoCols = 30;
  gotoRows = 4;
  ambigTableSize = 0;
  startState = (StateId)0;
  finalProductionIndex = 0;
  bigProductionListSize = 0;
  errorBitsRowSize = 4;
  uniqueErrorRows = 0;

  // storage size: 200 bytes
  // rows: 4  cols: 25
  static ActionEntry const actionTable_static[100] = {
    /*0*/ -2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 
    /*1*/ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    /*2*/ -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    /*3*/ 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
  };
  actionTable = const_cast<ActionEntry*>(actionTable_static);

  // storage size: 240 bytes
  // rows: 4  cols: 30
  static GotoEntry const gotoTable_static[120] = {
    /*0*/ 65535, 65535, 3, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /*1*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /*2*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /*3*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
  };
  gotoTable = const_cast<GotoEntry*>(gotoTable_static);

  // storage size: 236 bytes
  static ParseTables::ProdInfo const prodInfo_static[59] = {
    /*0*/ {2,1}, {0,2}, {1,2}, {3,3}, {0,4}, {1,4}, {3,4}, {1,5}, {1,5}, {4,6}, {6,7}, {6,8}, {7,8}, {0,9}, {1,9}, {1,10}, 
    /*1*/ {3,10}, {1,11}, {2,12}, {3,12}, {2,13}, {0,14}, {1,14}, {1,15}, {3,15}, {1,16}, {1,16}, {1,16}, {1,17}, {5,18}, {6,19}, {7,19}, 
    /*2*/ {2,20}, {1,21}, {1,21}, {5,22}, {0,23}, {3,23}, {4,24}, {1,25}, {1,25}, {1,26}, {3,26}, {4,26}, {1,26}, {1,26}, {1,26}, {1,26}, 
    /*3*/ {1,26}, {2,26}, {3,26}, {3,26}, {3,26}, {3,26}, {3,27}, {0,28}, {1,28}, {1,29}, {3,29}, 
  };
  prodInfo = const_cast<ParseTables::ProdInfo*>(prodInfo_static);

  static SymbolId const stateSymbol_static[4] = {
    /*0*/ 0, 1, 24, -3, 
  };
  stateSymbol = const_cast<SymbolId*>(stateSymbol_static);

  ActionEntry *ambigTable_static = NULL;
  ambigTable = const_cast<ActionEntry*>(ambigTable_static);

  // storage size: 60 bytes
  static NtIndex const nontermOrder_static[30] = {
    /*0*/ 22, 21, 28, 29, 27, 20, 18, 17, 16, 26, 15, 14, 13, 12, 25, 11, 
    /*1*/ 10, 9, 8, 7, 5, 6, 4, 24, 1, 19, 2, 0, 23, 3, 
  };
  nontermOrder = const_cast<NtIndex*>(nontermOrder_static);

  ErrorBitsEntry *errorBits_static = NULL;
  errorBits = const_cast<ErrorBitsEntry*>(errorBits_static);

  errorBitsPointers = NULL;

  TermIndex *actionIndexMap_static = NULL;
  actionIndexMap = const_cast<TermIndex*>(actionIndexMap_static);

  actionRowPointers = NULL;

  NtIndex *gotoIndexMap_static = NULL;
  gotoIndexMap = const_cast<NtIndex*>(gotoIndexMap_static);

  gotoRowPointers = NULL;

  firstWithTerminal = NULL;
  firstWithNonterminal = NULL;
  bigProductionList = NULL;
  productionsForState = NULL;
  ambigStateTable = NULL;
}


ParseTables *ZaneParser::makeTables()
{
  return new ZaneParser_ParseTables;
}

