// src/grammar/parser.cc
// *** DO NOT EDIT BY HAND ***
// automatically generated by gramanl, from src/grammar/parser.gr

// GLR source location information is enabled

#include "parser.h"     // ZaneParser
#include "parsetables.h" // ParseTables
#include "srcloc.h"      // SourceLoc

#include <assert.h>      // assert
#include <iostream>      // std::cout
#include <stdlib.h>      // abort

static char const *termNames[] = {
  "TOK_EOF",  // 0
  "TOK_LPAREN",  // 1
  "TOK_RPAREN",  // 2
  "TOK_LCURLY",  // 3
  "TOK_RCURLY",  // 4
  "TOK_COMMA",  // 5
  "TOK_COLON",  // 6
  "TOK_EQUAL",  // 7
  "TOK_DOLLAR",  // 8
  "TOK_THIN_ARROW",  // 9
  "TOK_THICK_ARROW",  // 10
  "TOK_AT",  // 11
  "TOK_MUT",  // 12
  "TOK_THIS",  // 13
  "TOK_STRING",  // 14
  "TOK_IDENT",  // 15
  "TOK_INT",  // 16
  "TOK_FLOAT",  // 17
  "TOK_PLUS",  // 18
  "TOK_MINUS",  // 19
  "TOK_STAR",  // 20
  "TOK_SLASH",  // 21
  "TOK_TILDE",  // 22
  "TOK_ERROR",  // 23
};

string ZaneParser::terminalDescription(int termId, SemanticValue sval)
{
  return stringc << termNames[termId]
                 << "(" << (sval % 100000) << ")";
}


static char const *nontermNames[] = {
  "empty",  // 0
  "__EarlyStartSymbol",  // 1
  "package",  // 2
  "global_scope",  // 3
  "declaration",  // 4
  "variable_decl",  // 5
  "function_decl",  // 6
  "method_decl",  // 7
  "parameters",  // 8
  "parameter_list",  // 9
  "method_parameters",  // 10
  "method_parameter_seq",  // 11
  "parameter",  // 12
  "type_list",  // 13
  "type_list_ne",  // 14
  "type_expr",  // 15
  "name_type",  // 16
  "function_type",  // 17
  "method_type",  // 18
  "arrow_body",  // 19
  "function_body",  // 20
  "scope",  // 21
  "statements",  // 22
  "statement",  // 23
  "statement_function_call",  // 24
  "value_expr",  // 25
  "additive_expr",  // 26
  "multiplicative_expr",  // 27
  "unary_expr",  // 28
  "postfix_expr",  // 29
  "call_expr",  // 30
  "primary_expr",  // 31
  "parenthized_value",  // 32
  "arguments",  // 33
  "argument_list",  // 34
};

string ZaneParser::nonterminalDescription(int nontermId, SemanticValue sval)
{
  return stringc << nontermNames[nontermId]
                 << "(" << (sval % 100000) << ")";
}


char const *ZaneParser::terminalName(int termId)
{
  return termNames[termId];
}

char const *ZaneParser::nonterminalName(int nontermId)
{
  return nontermNames[nontermId];
}

// ------------------- actions ------------------
// [0] __EarlyStartSymbol[ast::nodes::Package*] -> top:package TOK_EOF
inline ast::nodes::Package* ZaneParser::action0___EarlyStartSymbol(SourceLoc loc, ast::nodes::Package* top)
#line 1 "<init>"
{ return top;  }
#line 110 "src/grammar/parser.cc"

// [1] package[ast::nodes::Package*] -> declarations:global_scope
inline ast::nodes::Package* ZaneParser::action1_package(SourceLoc loc, std::vector<ast::nodes::Declaration>* declarations)
#line 125 "src/grammar/parser.gr"
{
		return new ast::nodes::Package(grammar_support::take_value(declarations));
	 }
#line 118 "src/grammar/parser.cc"

// [2] global_scope[std::vector<ast::nodes::Declaration>*] -> empty
inline std::vector<ast::nodes::Declaration>* ZaneParser::action2_global_scope(SourceLoc loc)
#line 133 "src/grammar/parser.gr"
{
		return new std::vector<ast::nodes::Declaration>();
	 }
#line 126 "src/grammar/parser.cc"

// [3] global_scope[std::vector<ast::nodes::Declaration>*] -> declarations:global_scope declaration:declaration
inline std::vector<ast::nodes::Declaration>* ZaneParser::action3_global_scope(SourceLoc loc, std::vector<ast::nodes::Declaration>* declarations, ast::nodes::Declaration* declaration)
#line 136 "src/grammar/parser.gr"
{
		declarations->push_back(grammar_support::take_value(declaration));
		return declarations;
	 }
#line 135 "src/grammar/parser.cc"

// [4] declaration[ast::nodes::Declaration*] -> function:function_decl
inline ast::nodes::Declaration* ZaneParser::action4_declaration(SourceLoc loc, ast::nodes::FunctionDecl* function)
#line 145 "src/grammar/parser.gr"
{
		return new ast::nodes::Declaration(grammar_support::take_value(function));
	 }
#line 143 "src/grammar/parser.cc"

// [5] declaration[ast::nodes::Declaration*] -> method:method_decl
inline ast::nodes::Declaration* ZaneParser::action5_declaration(SourceLoc loc, ast::nodes::MethodDecl* method)
#line 148 "src/grammar/parser.gr"
{
		return new ast::nodes::Declaration(grammar_support::take_value(method));
	 }
#line 151 "src/grammar/parser.cc"

// [6] variable_decl[ast::nodes::VariableDecl*] -> name:TOK_IDENT type:type_expr = value:value_expr
inline ast::nodes::VariableDecl* ZaneParser::action6_variable_decl(SourceLoc loc, std::string* name, ast::nodes::TypeExpression* type, ast::nodes::ValueExpr* value)
#line 156 "src/grammar/parser.gr"
{
		return new ast::nodes::VariableDecl(
			grammar_support::take_string(name),
			grammar_support::take_value(type),
			grammar_support::take_ptr(value)
		);
	 }
#line 163 "src/grammar/parser.cc"

// [7] function_decl[ast::nodes::FunctionDecl*] -> return_type:type_expr name:TOK_IDENT ( params:parameters ) body:function_body
inline ast::nodes::FunctionDecl* ZaneParser::action7_function_decl(SourceLoc loc, ast::nodes::TypeExpression* return_type, std::string* name, std::vector<ast::nodes::Parameter>* params, grammar_support::FunctionBodyValue* body)
#line 168 "src/grammar/parser.gr"
{
		return new ast::nodes::FunctionDecl(
			grammar_support::take_string(name),
			grammar_support::take_value(params),
			grammar_support::take_value(return_type),
			grammar_support::take_value(body).value
		);
	 }
#line 176 "src/grammar/parser.cc"

// [8] method_decl[ast::nodes::MethodDecl*] -> return_type:type_expr name:TOK_IDENT ( params:method_parameters ) body:function_body
inline ast::nodes::MethodDecl* ZaneParser::action8_method_decl(SourceLoc loc, ast::nodes::TypeExpression* return_type, std::string* name, std::vector<ast::nodes::Parameter>* params, grammar_support::FunctionBodyValue* body)
#line 181 "src/grammar/parser.gr"
{
		return new ast::nodes::MethodDecl(
			grammar_support::take_string(name),
			grammar_support::take_value(params),
			grammar_support::take_value(return_type),
			grammar_support::take_value(body).value,
			false
		);
	 }
#line 190 "src/grammar/parser.cc"

// [9] method_decl[ast::nodes::MethodDecl*] -> return_type:type_expr name:TOK_IDENT ( params:method_parameters ) mut body:function_body
inline ast::nodes::MethodDecl* ZaneParser::action9_method_decl(SourceLoc loc, ast::nodes::TypeExpression* return_type, std::string* name, std::vector<ast::nodes::Parameter>* params, grammar_support::FunctionBodyValue* body)
#line 190 "src/grammar/parser.gr"
{
		return new ast::nodes::MethodDecl(
			grammar_support::take_string(name),
			grammar_support::take_value(params),
			grammar_support::take_value(return_type),
			grammar_support::take_value(body).value,
			true
		);
	 }
#line 204 "src/grammar/parser.cc"

// [10] parameters[std::vector<ast::nodes::Parameter>*] -> empty
inline std::vector<ast::nodes::Parameter>* ZaneParser::action10_parameters(SourceLoc loc)
#line 204 "src/grammar/parser.gr"
{
		return new std::vector<ast::nodes::Parameter>();
	 }
#line 212 "src/grammar/parser.cc"

// [11] parameters[std::vector<ast::nodes::Parameter>*] -> list:parameter_list
inline std::vector<ast::nodes::Parameter>* ZaneParser::action11_parameters(SourceLoc loc, std::vector<ast::nodes::Parameter>* list)
#line 207 "src/grammar/parser.gr"
{
		return list;
	 }
#line 220 "src/grammar/parser.cc"

// [12] parameter_list[std::vector<ast::nodes::Parameter>*] -> parameter:parameter
inline std::vector<ast::nodes::Parameter>* ZaneParser::action12_parameter_list(SourceLoc loc, ast::nodes::Parameter* parameter)
#line 215 "src/grammar/parser.gr"
{
		auto* list = new std::vector<ast::nodes::Parameter>();
		list->push_back(grammar_support::take_value(parameter));
		return list;
	 }
#line 230 "src/grammar/parser.cc"

// [13] parameter_list[std::vector<ast::nodes::Parameter>*] -> list:parameter_list , parameter:parameter
inline std::vector<ast::nodes::Parameter>* ZaneParser::action13_parameter_list(SourceLoc loc, std::vector<ast::nodes::Parameter>* list, ast::nodes::Parameter* parameter)
#line 220 "src/grammar/parser.gr"
{
		list->push_back(grammar_support::take_value(parameter));
		return list;
	 }
#line 239 "src/grammar/parser.cc"

// [14] method_parameters[std::vector<ast::nodes::Parameter>*] -> list:method_parameter_seq
inline std::vector<ast::nodes::Parameter>* ZaneParser::action14_method_parameters(SourceLoc loc, std::vector<ast::nodes::Parameter>* list)
#line 229 "src/grammar/parser.gr"
{
		return list;
	 }
#line 247 "src/grammar/parser.cc"

// [15] method_parameter_seq[std::vector<ast::nodes::Parameter>*] -> this type:type_expr
inline std::vector<ast::nodes::Parameter>* ZaneParser::action15_method_parameter_seq(SourceLoc loc, ast::nodes::TypeExpression* type)
#line 237 "src/grammar/parser.gr"
{
		auto* list = new std::vector<ast::nodes::Parameter>();
		list->push_back(ast::nodes::Parameter(grammar_support::take_ptr(type), "this"));
		return list;
	 }
#line 257 "src/grammar/parser.cc"

// [16] method_parameter_seq[std::vector<ast::nodes::Parameter>*] -> list:method_parameter_seq , parameter:parameter
inline std::vector<ast::nodes::Parameter>* ZaneParser::action16_method_parameter_seq(SourceLoc loc, std::vector<ast::nodes::Parameter>* list, ast::nodes::Parameter* parameter)
#line 242 "src/grammar/parser.gr"
{
		list->push_back(grammar_support::take_value(parameter));
		return list;
	 }
#line 266 "src/grammar/parser.cc"

// [17] parameter[ast::nodes::Parameter*] -> name:TOK_IDENT type:type_expr
inline ast::nodes::Parameter* ZaneParser::action17_parameter(SourceLoc loc, std::string* name, ast::nodes::TypeExpression* type)
#line 251 "src/grammar/parser.gr"
{
		return new ast::nodes::Parameter(
			grammar_support::take_ptr(type),
			grammar_support::take_string(name)
		);
	 }
#line 277 "src/grammar/parser.cc"

// [18] type_list[std::vector<std::unique_ptr<ast::nodes::TypeExpression>>*] -> empty
inline std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* ZaneParser::action18_type_list(SourceLoc loc)
#line 262 "src/grammar/parser.gr"
{
		return new std::vector<std::unique_ptr<ast::nodes::TypeExpression>>();
	 }
#line 285 "src/grammar/parser.cc"

// [19] type_list[std::vector<std::unique_ptr<ast::nodes::TypeExpression>>*] -> list:type_list_ne
inline std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* ZaneParser::action19_type_list(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* list)
#line 265 "src/grammar/parser.gr"
{
		return list;
	 }
#line 293 "src/grammar/parser.cc"

// [20] type_list_ne[std::vector<std::unique_ptr<ast::nodes::TypeExpression>>*] -> expr:type_expr
inline std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* ZaneParser::action20_type_list_ne(SourceLoc loc, ast::nodes::TypeExpression* expr)
#line 273 "src/grammar/parser.gr"
{
		auto* list = new std::vector<std::unique_ptr<ast::nodes::TypeExpression>>();
		list->push_back(grammar_support::take_ptr(expr));
		return list;
	 }
#line 303 "src/grammar/parser.cc"

// [21] type_list_ne[std::vector<std::unique_ptr<ast::nodes::TypeExpression>>*] -> list:type_list_ne , expr:type_expr
inline std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* ZaneParser::action21_type_list_ne(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* list, ast::nodes::TypeExpression* expr)
#line 278 "src/grammar/parser.gr"
{
		list->push_back(grammar_support::take_ptr(expr));
		return list;
	 }
#line 312 "src/grammar/parser.cc"

// [22] type_expr[ast::nodes::TypeExpression*] -> name:name_type
inline ast::nodes::TypeExpression* ZaneParser::action22_type_expr(SourceLoc loc, ast::nodes::NameType* name)
#line 287 "src/grammar/parser.gr"
{
		return new ast::nodes::TypeExpression(grammar_support::take_value(name));
	 }
#line 320 "src/grammar/parser.cc"

// [23] type_expr[ast::nodes::TypeExpression*] -> function:function_type
inline ast::nodes::TypeExpression* ZaneParser::action23_type_expr(SourceLoc loc, ast::nodes::FunctionType* function)
#line 290 "src/grammar/parser.gr"
{
		return new ast::nodes::TypeExpression(grammar_support::take_value(function));
	 }
#line 328 "src/grammar/parser.cc"

// [24] type_expr[ast::nodes::TypeExpression*] -> method:method_type
inline ast::nodes::TypeExpression* ZaneParser::action24_type_expr(SourceLoc loc, ast::nodes::MethodType* method)
#line 293 "src/grammar/parser.gr"
{
		return new ast::nodes::TypeExpression(grammar_support::take_value(method));
	 }
#line 336 "src/grammar/parser.cc"

// [25] name_type[ast::nodes::NameType*] -> identifier:TOK_IDENT
inline ast::nodes::NameType* ZaneParser::action25_name_type(SourceLoc loc, std::string* identifier)
#line 301 "src/grammar/parser.gr"
{
		return new ast::nodes::NameType(
			grammar_support::take_string(identifier),
			std::vector<std::unique_ptr<ast::nodes::TypeExpression>>()
		);
	 }
#line 347 "src/grammar/parser.cc"

// [26] function_type[ast::nodes::FunctionType*] -> ( params:type_list ) -> return_type:type_expr
inline ast::nodes::FunctionType* ZaneParser::action26_function_type(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* params, ast::nodes::TypeExpression* return_type)
#line 312 "src/grammar/parser.gr"
{
		return new ast::nodes::FunctionType(
			grammar_support::take_value(params),
			grammar_support::take_ptr(return_type)
		);
	 }
#line 358 "src/grammar/parser.cc"

// [27] method_type[ast::nodes::MethodType*] -> ( this params:type_list_ne ) -> return_type:type_expr
inline ast::nodes::MethodType* ZaneParser::action27_method_type(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* params, ast::nodes::TypeExpression* return_type)
#line 323 "src/grammar/parser.gr"
{
		return new ast::nodes::MethodType(
			grammar_support::take_value(params),
			grammar_support::take_ptr(return_type),
			false
		);
	 }
#line 370 "src/grammar/parser.cc"

// [28] method_type[ast::nodes::MethodType*] -> ( this params:type_list_ne ) mut -> return_type:type_expr
inline ast::nodes::MethodType* ZaneParser::action28_method_type(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* params, ast::nodes::TypeExpression* return_type)
#line 330 "src/grammar/parser.gr"
{
		return new ast::nodes::MethodType(
			grammar_support::take_value(params),
			grammar_support::take_ptr(return_type),
			true
		);
	 }
#line 382 "src/grammar/parser.cc"

// [29] arrow_body[ast::nodes::ArrowBody*] -> => value:value_expr
inline ast::nodes::ArrowBody* ZaneParser::action29_arrow_body(SourceLoc loc, ast::nodes::ValueExpr* value)
#line 342 "src/grammar/parser.gr"
{
		return new ast::nodes::ArrowBody(grammar_support::take_ptr(value));
	 }
#line 390 "src/grammar/parser.cc"

// [30] function_body[grammar_support::FunctionBodyValue*] -> body:arrow_body
inline grammar_support::FunctionBodyValue* ZaneParser::action30_function_body(SourceLoc loc, ast::nodes::ArrowBody* body)
#line 350 "src/grammar/parser.gr"
{
		return new grammar_support::FunctionBodyValue(grammar_support::take_value(body));
	 }
#line 398 "src/grammar/parser.cc"

// [31] function_body[grammar_support::FunctionBodyValue*] -> body:scope
inline grammar_support::FunctionBodyValue* ZaneParser::action31_function_body(SourceLoc loc, ast::nodes::Scope* body)
#line 353 "src/grammar/parser.gr"
{
		return new grammar_support::FunctionBodyValue(grammar_support::take_value(body));
	 }
#line 406 "src/grammar/parser.cc"

// [32] scope[ast::nodes::Scope*] -> { statements:statements }
inline ast::nodes::Scope* ZaneParser::action32_scope(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::Statement>>* statements)
#line 361 "src/grammar/parser.gr"
{
		return new ast::nodes::Scope(grammar_support::take_value(statements));
	 }
#line 414 "src/grammar/parser.cc"

// [33] statements[std::vector<std::unique_ptr<ast::nodes::Statement>>*] -> empty
inline std::vector<std::unique_ptr<ast::nodes::Statement>>* ZaneParser::action33_statements(SourceLoc loc)
#line 369 "src/grammar/parser.gr"
{
		return new std::vector<std::unique_ptr<ast::nodes::Statement>>();
	 }
#line 422 "src/grammar/parser.cc"

// [34] statements[std::vector<std::unique_ptr<ast::nodes::Statement>>*] -> list:statements statement:statement
inline std::vector<std::unique_ptr<ast::nodes::Statement>>* ZaneParser::action34_statements(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::Statement>>* list, ast::nodes::Statement* statement)
#line 372 "src/grammar/parser.gr"
{
		list->push_back(grammar_support::take_ptr(statement));
		return list;
	 }
#line 431 "src/grammar/parser.cc"

// [35] statement[ast::nodes::Statement*] -> call:statement_function_call
inline ast::nodes::Statement* ZaneParser::action35_statement(SourceLoc loc, ast::nodes::FunctionCall* call)
#line 381 "src/grammar/parser.gr"
{
		return new ast::nodes::Statement(grammar_support::take_value(call));
	 }
#line 439 "src/grammar/parser.cc"

// [36] statement[ast::nodes::Statement*] -> declaration:variable_decl
inline ast::nodes::Statement* ZaneParser::action36_statement(SourceLoc loc, ast::nodes::VariableDecl* declaration)
#line 384 "src/grammar/parser.gr"
{
		return new ast::nodes::Statement(grammar_support::take_value(declaration));
	 }
#line 447 "src/grammar/parser.cc"

// [37] statement_function_call[ast::nodes::FunctionCall*] -> call:call_expr
inline ast::nodes::FunctionCall* ZaneParser::action37_statement_function_call(SourceLoc loc, ast::nodes::FunctionCall* call)
#line 392 "src/grammar/parser.gr"
{
		return call;
	 }
#line 455 "src/grammar/parser.cc"

// [38] value_expr[ast::nodes::ValueExpr*] -> expr:additive_expr
inline ast::nodes::ValueExpr* ZaneParser::action38_value_expr(SourceLoc loc, ast::nodes::ValueExpr* expr)
#line 400 "src/grammar/parser.gr"
{
		return expr;
	 }
#line 463 "src/grammar/parser.cc"

// [39] additive_expr[ast::nodes::ValueExpr*] -> expr:multiplicative_expr
inline ast::nodes::ValueExpr* ZaneParser::action39_additive_expr(SourceLoc loc, ast::nodes::ValueExpr* expr)
#line 408 "src/grammar/parser.gr"
{
		return expr;
	 }
#line 471 "src/grammar/parser.cc"

// [40] additive_expr[ast::nodes::ValueExpr*] -> left:additive_expr + right:multiplicative_expr %prec(10)
inline ast::nodes::ValueExpr* ZaneParser::action40_additive_expr(SourceLoc loc, ast::nodes::ValueExpr* left, ast::nodes::ValueExpr* right)
#line 411 "src/grammar/parser.gr"
{
		return grammar_support::make_binary("+", left, right);
	 }
#line 479 "src/grammar/parser.cc"

// [41] additive_expr[ast::nodes::ValueExpr*] -> left:additive_expr - right:multiplicative_expr %prec(10)
inline ast::nodes::ValueExpr* ZaneParser::action41_additive_expr(SourceLoc loc, ast::nodes::ValueExpr* left, ast::nodes::ValueExpr* right)
#line 414 "src/grammar/parser.gr"
{
		return grammar_support::make_binary("-", left, right);
	 }
#line 487 "src/grammar/parser.cc"

// [42] multiplicative_expr[ast::nodes::ValueExpr*] -> expr:unary_expr
inline ast::nodes::ValueExpr* ZaneParser::action42_multiplicative_expr(SourceLoc loc, ast::nodes::ValueExpr* expr)
#line 422 "src/grammar/parser.gr"
{
		return expr;
	 }
#line 495 "src/grammar/parser.cc"

// [43] multiplicative_expr[ast::nodes::ValueExpr*] -> left:multiplicative_expr * right:unary_expr %prec(20)
inline ast::nodes::ValueExpr* ZaneParser::action43_multiplicative_expr(SourceLoc loc, ast::nodes::ValueExpr* left, ast::nodes::ValueExpr* right)
#line 425 "src/grammar/parser.gr"
{
		return grammar_support::make_binary("*", left, right);
	 }
#line 503 "src/grammar/parser.cc"

// [44] multiplicative_expr[ast::nodes::ValueExpr*] -> left:multiplicative_expr / right:unary_expr %prec(20)
inline ast::nodes::ValueExpr* ZaneParser::action44_multiplicative_expr(SourceLoc loc, ast::nodes::ValueExpr* left, ast::nodes::ValueExpr* right)
#line 428 "src/grammar/parser.gr"
{
		return grammar_support::make_binary("/", left, right);
	 }
#line 511 "src/grammar/parser.cc"

// [45] unary_expr[ast::nodes::ValueExpr*] -> expr:postfix_expr
inline ast::nodes::ValueExpr* ZaneParser::action45_unary_expr(SourceLoc loc, ast::nodes::ValueExpr* expr)
#line 436 "src/grammar/parser.gr"
{
		return expr;
	 }
#line 519 "src/grammar/parser.cc"

// [46] unary_expr[ast::nodes::ValueExpr*] -> ~ expr:unary_expr %prec(30)
inline ast::nodes::ValueExpr* ZaneParser::action46_unary_expr(SourceLoc loc, ast::nodes::ValueExpr* expr)
#line 439 "src/grammar/parser.gr"
{
		return grammar_support::make_flip(expr);
	 }
#line 527 "src/grammar/parser.cc"

// [47] postfix_expr[ast::nodes::ValueExpr*] -> expr:primary_expr
inline ast::nodes::ValueExpr* ZaneParser::action47_postfix_expr(SourceLoc loc, ast::nodes::ValueExpr* expr)
#line 447 "src/grammar/parser.gr"
{
		return expr;
	 }
#line 535 "src/grammar/parser.cc"

// [48] postfix_expr[ast::nodes::ValueExpr*] -> call:call_expr
inline ast::nodes::ValueExpr* ZaneParser::action48_postfix_expr(SourceLoc loc, ast::nodes::FunctionCall* call)
#line 450 "src/grammar/parser.gr"
{
		return grammar_support::wrap_call(call);
	 }
#line 543 "src/grammar/parser.cc"

// [49] call_expr[ast::nodes::FunctionCall*] -> callee:primary_expr ( args:arguments )
inline ast::nodes::FunctionCall* ZaneParser::action49_call_expr(SourceLoc loc, ast::nodes::ValueExpr* callee, std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* args)
#line 458 "src/grammar/parser.gr"
{
		return new ast::nodes::FunctionCall(
			grammar_support::take_ptr(callee),
			grammar_support::take_value(args)
		);
	 }
#line 554 "src/grammar/parser.cc"

// [50] call_expr[ast::nodes::FunctionCall*] -> callee:call_expr ( args:arguments )
inline ast::nodes::FunctionCall* ZaneParser::action50_call_expr(SourceLoc loc, ast::nodes::FunctionCall* callee, std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* args)
#line 464 "src/grammar/parser.gr"
{
		return new ast::nodes::FunctionCall(
			std::make_unique<ast::nodes::ValueExpr>(grammar_support::take_value(callee)),
			grammar_support::take_value(args)
		);
	 }
#line 565 "src/grammar/parser.cc"

// [51] primary_expr[ast::nodes::ValueExpr*] -> identifier:TOK_IDENT
inline ast::nodes::ValueExpr* ZaneParser::action51_primary_expr(SourceLoc loc, std::string* identifier)
#line 475 "src/grammar/parser.gr"
{
		return new ast::nodes::ValueExpr(ast::nodes::ValueSymbol(grammar_support::take_string(identifier)));
	 }
#line 573 "src/grammar/parser.cc"

// [52] primary_expr[ast::nodes::ValueExpr*] -> package:TOK_IDENT $ identifier:TOK_IDENT
inline ast::nodes::ValueExpr* ZaneParser::action52_primary_expr(SourceLoc loc, std::string* package, std::string* identifier)
#line 478 "src/grammar/parser.gr"
{
		return new ast::nodes::ValueExpr(
			ast::nodes::PackageValueSymbol(
				grammar_support::take_string(identifier),
				grammar_support::take_string(package)
			)
		);
	 }
#line 586 "src/grammar/parser.cc"

// [53] primary_expr[ast::nodes::ValueExpr*] -> @ package:TOK_IDENT $ identifier:TOK_IDENT
inline ast::nodes::ValueExpr* ZaneParser::action53_primary_expr(SourceLoc loc, std::string* package, std::string* identifier)
#line 486 "src/grammar/parser.gr"
{
		return new ast::nodes::ValueExpr(
			ast::nodes::IntrinsicValueSymbol(
				grammar_support::take_string(identifier),
				grammar_support::take_string(package)
			)
		);
	 }
#line 599 "src/grammar/parser.cc"

// [54] primary_expr[ast::nodes::ValueExpr*] -> integer:TOK_INT
inline ast::nodes::ValueExpr* ZaneParser::action54_primary_expr(SourceLoc loc, std::string* integer)
#line 494 "src/grammar/parser.gr"
{
		return new ast::nodes::ValueExpr(ast::nodes::IntLiteral(grammar_support::take_string(integer)));
	 }
#line 607 "src/grammar/parser.cc"

// [55] primary_expr[ast::nodes::ValueExpr*] -> number:TOK_FLOAT
inline ast::nodes::ValueExpr* ZaneParser::action55_primary_expr(SourceLoc loc, std::string* number)
#line 497 "src/grammar/parser.gr"
{
		return new ast::nodes::ValueExpr(ast::nodes::FloatLiteral(grammar_support::take_string(number)));
	 }
#line 615 "src/grammar/parser.cc"

// [56] primary_expr[ast::nodes::ValueExpr*] -> text:TOK_STRING
inline ast::nodes::ValueExpr* ZaneParser::action56_primary_expr(SourceLoc loc, std::string* text)
#line 500 "src/grammar/parser.gr"
{
		return new ast::nodes::ValueExpr(ast::nodes::StringLiteral(grammar_support::take_string(text)));
	 }
#line 623 "src/grammar/parser.cc"

// [57] primary_expr[ast::nodes::ValueExpr*] -> value:parenthized_value
inline ast::nodes::ValueExpr* ZaneParser::action57_primary_expr(SourceLoc loc, ast::nodes::ParenthizedValue* value)
#line 503 "src/grammar/parser.gr"
{
		return grammar_support::wrap_parenthesized(value);
	 }
#line 631 "src/grammar/parser.cc"

// [58] parenthized_value[ast::nodes::ParenthizedValue*] -> ( value:value_expr )
inline ast::nodes::ParenthizedValue* ZaneParser::action58_parenthized_value(SourceLoc loc, ast::nodes::ValueExpr* value)
#line 511 "src/grammar/parser.gr"
{
		return new ast::nodes::ParenthizedValue(grammar_support::take_ptr(value));
	 }
#line 639 "src/grammar/parser.cc"

// [59] arguments[std::vector<std::unique_ptr<ast::nodes::ValueExpr>>*] -> empty
inline std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* ZaneParser::action59_arguments(SourceLoc loc)
#line 519 "src/grammar/parser.gr"
{
		return new std::vector<std::unique_ptr<ast::nodes::ValueExpr>>();
	 }
#line 647 "src/grammar/parser.cc"

// [60] arguments[std::vector<std::unique_ptr<ast::nodes::ValueExpr>>*] -> list:argument_list
inline std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* ZaneParser::action60_arguments(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* list)
#line 522 "src/grammar/parser.gr"
{
		return list;
	 }
#line 655 "src/grammar/parser.cc"

// [61] argument_list[std::vector<std::unique_ptr<ast::nodes::ValueExpr>>*] -> value:value_expr
inline std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* ZaneParser::action61_argument_list(SourceLoc loc, ast::nodes::ValueExpr* value)
#line 530 "src/grammar/parser.gr"
{
		auto* list = new std::vector<std::unique_ptr<ast::nodes::ValueExpr>>();
		list->push_back(grammar_support::take_ptr(value));
		return list;
	 }
#line 665 "src/grammar/parser.cc"

// [62] argument_list[std::vector<std::unique_ptr<ast::nodes::ValueExpr>>*] -> list:argument_list , value:value_expr
inline std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* ZaneParser::action62_argument_list(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* list, ast::nodes::ValueExpr* value)
#line 535 "src/grammar/parser.gr"
{
		list->push_back(grammar_support::take_ptr(value));
		return list;
	 }
#line 674 "src/grammar/parser.cc"


/*static*/ SemanticValue ZaneParser::doReductionAction(
  ZaneParser *ths,
  int productionId, SemanticValue const *semanticValues,
  SourceLoc loc)
{
  switch (productionId) {
    case 0:
      return (SemanticValue)(ths->action0___EarlyStartSymbol(loc, (ast::nodes::Package*)(semanticValues[0])));
    case 1:
      return (SemanticValue)(ths->action1_package(loc, (std::vector<ast::nodes::Declaration>*)(semanticValues[0])));
    case 2:
      return (SemanticValue)(ths->action2_global_scope(loc));
    case 3:
      return (SemanticValue)(ths->action3_global_scope(loc, (std::vector<ast::nodes::Declaration>*)(semanticValues[0]), (ast::nodes::Declaration*)(semanticValues[1])));
    case 4:
      return (SemanticValue)(ths->action4_declaration(loc, (ast::nodes::FunctionDecl*)(semanticValues[0])));
    case 5:
      return (SemanticValue)(ths->action5_declaration(loc, (ast::nodes::MethodDecl*)(semanticValues[0])));
    case 6:
      return (SemanticValue)(ths->action6_variable_decl(loc, (std::string*)(semanticValues[0]), (ast::nodes::TypeExpression*)(semanticValues[1]), (ast::nodes::ValueExpr*)(semanticValues[3])));
    case 7:
      return (SemanticValue)(ths->action7_function_decl(loc, (ast::nodes::TypeExpression*)(semanticValues[0]), (std::string*)(semanticValues[1]), (std::vector<ast::nodes::Parameter>*)(semanticValues[3]), (grammar_support::FunctionBodyValue*)(semanticValues[5])));
    case 8:
      return (SemanticValue)(ths->action8_method_decl(loc, (ast::nodes::TypeExpression*)(semanticValues[0]), (std::string*)(semanticValues[1]), (std::vector<ast::nodes::Parameter>*)(semanticValues[3]), (grammar_support::FunctionBodyValue*)(semanticValues[5])));
    case 9:
      return (SemanticValue)(ths->action9_method_decl(loc, (ast::nodes::TypeExpression*)(semanticValues[0]), (std::string*)(semanticValues[1]), (std::vector<ast::nodes::Parameter>*)(semanticValues[3]), (grammar_support::FunctionBodyValue*)(semanticValues[6])));
    case 10:
      return (SemanticValue)(ths->action10_parameters(loc));
    case 11:
      return (SemanticValue)(ths->action11_parameters(loc, (std::vector<ast::nodes::Parameter>*)(semanticValues[0])));
    case 12:
      return (SemanticValue)(ths->action12_parameter_list(loc, (ast::nodes::Parameter*)(semanticValues[0])));
    case 13:
      return (SemanticValue)(ths->action13_parameter_list(loc, (std::vector<ast::nodes::Parameter>*)(semanticValues[0]), (ast::nodes::Parameter*)(semanticValues[2])));
    case 14:
      return (SemanticValue)(ths->action14_method_parameters(loc, (std::vector<ast::nodes::Parameter>*)(semanticValues[0])));
    case 15:
      return (SemanticValue)(ths->action15_method_parameter_seq(loc, (ast::nodes::TypeExpression*)(semanticValues[1])));
    case 16:
      return (SemanticValue)(ths->action16_method_parameter_seq(loc, (std::vector<ast::nodes::Parameter>*)(semanticValues[0]), (ast::nodes::Parameter*)(semanticValues[2])));
    case 17:
      return (SemanticValue)(ths->action17_parameter(loc, (std::string*)(semanticValues[0]), (ast::nodes::TypeExpression*)(semanticValues[1])));
    case 18:
      return (SemanticValue)(ths->action18_type_list(loc));
    case 19:
      return (SemanticValue)(ths->action19_type_list(loc, (std::vector<std::unique_ptr<ast::nodes::TypeExpression>>*)(semanticValues[0])));
    case 20:
      return (SemanticValue)(ths->action20_type_list_ne(loc, (ast::nodes::TypeExpression*)(semanticValues[0])));
    case 21:
      return (SemanticValue)(ths->action21_type_list_ne(loc, (std::vector<std::unique_ptr<ast::nodes::TypeExpression>>*)(semanticValues[0]), (ast::nodes::TypeExpression*)(semanticValues[2])));
    case 22:
      return (SemanticValue)(ths->action22_type_expr(loc, (ast::nodes::NameType*)(semanticValues[0])));
    case 23:
      return (SemanticValue)(ths->action23_type_expr(loc, (ast::nodes::FunctionType*)(semanticValues[0])));
    case 24:
      return (SemanticValue)(ths->action24_type_expr(loc, (ast::nodes::MethodType*)(semanticValues[0])));
    case 25:
      return (SemanticValue)(ths->action25_name_type(loc, (std::string*)(semanticValues[0])));
    case 26:
      return (SemanticValue)(ths->action26_function_type(loc, (std::vector<std::unique_ptr<ast::nodes::TypeExpression>>*)(semanticValues[1]), (ast::nodes::TypeExpression*)(semanticValues[4])));
    case 27:
      return (SemanticValue)(ths->action27_method_type(loc, (std::vector<std::unique_ptr<ast::nodes::TypeExpression>>*)(semanticValues[2]), (ast::nodes::TypeExpression*)(semanticValues[5])));
    case 28:
      return (SemanticValue)(ths->action28_method_type(loc, (std::vector<std::unique_ptr<ast::nodes::TypeExpression>>*)(semanticValues[2]), (ast::nodes::TypeExpression*)(semanticValues[6])));
    case 29:
      return (SemanticValue)(ths->action29_arrow_body(loc, (ast::nodes::ValueExpr*)(semanticValues[1])));
    case 30:
      return (SemanticValue)(ths->action30_function_body(loc, (ast::nodes::ArrowBody*)(semanticValues[0])));
    case 31:
      return (SemanticValue)(ths->action31_function_body(loc, (ast::nodes::Scope*)(semanticValues[0])));
    case 32:
      return (SemanticValue)(ths->action32_scope(loc, (std::vector<std::unique_ptr<ast::nodes::Statement>>*)(semanticValues[1])));
    case 33:
      return (SemanticValue)(ths->action33_statements(loc));
    case 34:
      return (SemanticValue)(ths->action34_statements(loc, (std::vector<std::unique_ptr<ast::nodes::Statement>>*)(semanticValues[0]), (ast::nodes::Statement*)(semanticValues[1])));
    case 35:
      return (SemanticValue)(ths->action35_statement(loc, (ast::nodes::FunctionCall*)(semanticValues[0])));
    case 36:
      return (SemanticValue)(ths->action36_statement(loc, (ast::nodes::VariableDecl*)(semanticValues[0])));
    case 37:
      return (SemanticValue)(ths->action37_statement_function_call(loc, (ast::nodes::FunctionCall*)(semanticValues[0])));
    case 38:
      return (SemanticValue)(ths->action38_value_expr(loc, (ast::nodes::ValueExpr*)(semanticValues[0])));
    case 39:
      return (SemanticValue)(ths->action39_additive_expr(loc, (ast::nodes::ValueExpr*)(semanticValues[0])));
    case 40:
      return (SemanticValue)(ths->action40_additive_expr(loc, (ast::nodes::ValueExpr*)(semanticValues[0]), (ast::nodes::ValueExpr*)(semanticValues[2])));
    case 41:
      return (SemanticValue)(ths->action41_additive_expr(loc, (ast::nodes::ValueExpr*)(semanticValues[0]), (ast::nodes::ValueExpr*)(semanticValues[2])));
    case 42:
      return (SemanticValue)(ths->action42_multiplicative_expr(loc, (ast::nodes::ValueExpr*)(semanticValues[0])));
    case 43:
      return (SemanticValue)(ths->action43_multiplicative_expr(loc, (ast::nodes::ValueExpr*)(semanticValues[0]), (ast::nodes::ValueExpr*)(semanticValues[2])));
    case 44:
      return (SemanticValue)(ths->action44_multiplicative_expr(loc, (ast::nodes::ValueExpr*)(semanticValues[0]), (ast::nodes::ValueExpr*)(semanticValues[2])));
    case 45:
      return (SemanticValue)(ths->action45_unary_expr(loc, (ast::nodes::ValueExpr*)(semanticValues[0])));
    case 46:
      return (SemanticValue)(ths->action46_unary_expr(loc, (ast::nodes::ValueExpr*)(semanticValues[1])));
    case 47:
      return (SemanticValue)(ths->action47_postfix_expr(loc, (ast::nodes::ValueExpr*)(semanticValues[0])));
    case 48:
      return (SemanticValue)(ths->action48_postfix_expr(loc, (ast::nodes::FunctionCall*)(semanticValues[0])));
    case 49:
      return (SemanticValue)(ths->action49_call_expr(loc, (ast::nodes::ValueExpr*)(semanticValues[0]), (std::vector<std::unique_ptr<ast::nodes::ValueExpr>>*)(semanticValues[2])));
    case 50:
      return (SemanticValue)(ths->action50_call_expr(loc, (ast::nodes::FunctionCall*)(semanticValues[0]), (std::vector<std::unique_ptr<ast::nodes::ValueExpr>>*)(semanticValues[2])));
    case 51:
      return (SemanticValue)(ths->action51_primary_expr(loc, (std::string*)(semanticValues[0])));
    case 52:
      return (SemanticValue)(ths->action52_primary_expr(loc, (std::string*)(semanticValues[0]), (std::string*)(semanticValues[2])));
    case 53:
      return (SemanticValue)(ths->action53_primary_expr(loc, (std::string*)(semanticValues[1]), (std::string*)(semanticValues[3])));
    case 54:
      return (SemanticValue)(ths->action54_primary_expr(loc, (std::string*)(semanticValues[0])));
    case 55:
      return (SemanticValue)(ths->action55_primary_expr(loc, (std::string*)(semanticValues[0])));
    case 56:
      return (SemanticValue)(ths->action56_primary_expr(loc, (std::string*)(semanticValues[0])));
    case 57:
      return (SemanticValue)(ths->action57_primary_expr(loc, (ast::nodes::ParenthizedValue*)(semanticValues[0])));
    case 58:
      return (SemanticValue)(ths->action58_parenthized_value(loc, (ast::nodes::ValueExpr*)(semanticValues[1])));
    case 59:
      return (SemanticValue)(ths->action59_arguments(loc));
    case 60:
      return (SemanticValue)(ths->action60_arguments(loc, (std::vector<std::unique_ptr<ast::nodes::ValueExpr>>*)(semanticValues[0])));
    case 61:
      return (SemanticValue)(ths->action61_argument_list(loc, (ast::nodes::ValueExpr*)(semanticValues[0])));
    case 62:
      return (SemanticValue)(ths->action62_argument_list(loc, (std::vector<std::unique_ptr<ast::nodes::ValueExpr>>*)(semanticValues[0]), (ast::nodes::ValueExpr*)(semanticValues[2])));
    default:
      assert(!"invalid production code");
      return (SemanticValue)0;   // silence warning
  }
}

UserActions::ReductionActionFunc ZaneParser::getReductionAction()
{
  return (ReductionActionFunc)&ZaneParser::doReductionAction;
}


// ---------------- dup/del/merge/keep nonterminals ---------------

inline ast::nodes::Package* ZaneParser::dup_package(ast::nodes::Package* p) 
#line 123 "src/grammar/parser.gr"
{return p; }
#line 826 "src/grammar/parser.cc"

inline void ZaneParser::del_package(ast::nodes::Package* p) 
#line 124 "src/grammar/parser.gr"
{ }
#line 831 "src/grammar/parser.cc"

inline std::vector<ast::nodes::Declaration>* ZaneParser::dup_global_scope(std::vector<ast::nodes::Declaration>* p) 
#line 131 "src/grammar/parser.gr"
{return p; }
#line 836 "src/grammar/parser.cc"

inline void ZaneParser::del_global_scope(std::vector<ast::nodes::Declaration>* p) 
#line 132 "src/grammar/parser.gr"
{ }
#line 841 "src/grammar/parser.cc"

inline ast::nodes::Declaration* ZaneParser::dup_declaration(ast::nodes::Declaration* p) 
#line 143 "src/grammar/parser.gr"
{return p; }
#line 846 "src/grammar/parser.cc"

inline void ZaneParser::del_declaration(ast::nodes::Declaration* p) 
#line 144 "src/grammar/parser.gr"
{ }
#line 851 "src/grammar/parser.cc"

inline ast::nodes::VariableDecl* ZaneParser::dup_variable_decl(ast::nodes::VariableDecl* p) 
#line 154 "src/grammar/parser.gr"
{return p; }
#line 856 "src/grammar/parser.cc"

inline void ZaneParser::del_variable_decl(ast::nodes::VariableDecl* p) 
#line 155 "src/grammar/parser.gr"
{ }
#line 861 "src/grammar/parser.cc"

inline ast::nodes::FunctionDecl* ZaneParser::dup_function_decl(ast::nodes::FunctionDecl* p) 
#line 166 "src/grammar/parser.gr"
{return p; }
#line 866 "src/grammar/parser.cc"

inline void ZaneParser::del_function_decl(ast::nodes::FunctionDecl* p) 
#line 167 "src/grammar/parser.gr"
{ }
#line 871 "src/grammar/parser.cc"

inline ast::nodes::MethodDecl* ZaneParser::dup_method_decl(ast::nodes::MethodDecl* p) 
#line 179 "src/grammar/parser.gr"
{return p; }
#line 876 "src/grammar/parser.cc"

inline void ZaneParser::del_method_decl(ast::nodes::MethodDecl* p) 
#line 180 "src/grammar/parser.gr"
{ }
#line 881 "src/grammar/parser.cc"

inline std::vector<ast::nodes::Parameter>* ZaneParser::dup_parameters(std::vector<ast::nodes::Parameter>* p) 
#line 202 "src/grammar/parser.gr"
{return p; }
#line 886 "src/grammar/parser.cc"

inline void ZaneParser::del_parameters(std::vector<ast::nodes::Parameter>* p) 
#line 203 "src/grammar/parser.gr"
{ }
#line 891 "src/grammar/parser.cc"

inline std::vector<ast::nodes::Parameter>* ZaneParser::dup_parameter_list(std::vector<ast::nodes::Parameter>* p) 
#line 213 "src/grammar/parser.gr"
{return p; }
#line 896 "src/grammar/parser.cc"

inline void ZaneParser::del_parameter_list(std::vector<ast::nodes::Parameter>* p) 
#line 214 "src/grammar/parser.gr"
{ }
#line 901 "src/grammar/parser.cc"

inline std::vector<ast::nodes::Parameter>* ZaneParser::dup_method_parameters(std::vector<ast::nodes::Parameter>* p) 
#line 227 "src/grammar/parser.gr"
{return p; }
#line 906 "src/grammar/parser.cc"

inline void ZaneParser::del_method_parameters(std::vector<ast::nodes::Parameter>* p) 
#line 228 "src/grammar/parser.gr"
{ }
#line 911 "src/grammar/parser.cc"

inline std::vector<ast::nodes::Parameter>* ZaneParser::dup_method_parameter_seq(std::vector<ast::nodes::Parameter>* p) 
#line 235 "src/grammar/parser.gr"
{return p; }
#line 916 "src/grammar/parser.cc"

inline void ZaneParser::del_method_parameter_seq(std::vector<ast::nodes::Parameter>* p) 
#line 236 "src/grammar/parser.gr"
{ }
#line 921 "src/grammar/parser.cc"

inline ast::nodes::Parameter* ZaneParser::dup_parameter(ast::nodes::Parameter* p) 
#line 249 "src/grammar/parser.gr"
{return p; }
#line 926 "src/grammar/parser.cc"

inline void ZaneParser::del_parameter(ast::nodes::Parameter* p) 
#line 250 "src/grammar/parser.gr"
{ }
#line 931 "src/grammar/parser.cc"

inline std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* ZaneParser::dup_type_list(std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* p) 
#line 260 "src/grammar/parser.gr"
{return p; }
#line 936 "src/grammar/parser.cc"

inline void ZaneParser::del_type_list(std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* p) 
#line 261 "src/grammar/parser.gr"
{ }
#line 941 "src/grammar/parser.cc"

inline std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* ZaneParser::dup_type_list_ne(std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* p) 
#line 271 "src/grammar/parser.gr"
{return p; }
#line 946 "src/grammar/parser.cc"

inline void ZaneParser::del_type_list_ne(std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* p) 
#line 272 "src/grammar/parser.gr"
{ }
#line 951 "src/grammar/parser.cc"

inline ast::nodes::TypeExpression* ZaneParser::dup_type_expr(ast::nodes::TypeExpression* p) 
#line 285 "src/grammar/parser.gr"
{return p; }
#line 956 "src/grammar/parser.cc"

inline void ZaneParser::del_type_expr(ast::nodes::TypeExpression* p) 
#line 286 "src/grammar/parser.gr"
{ }
#line 961 "src/grammar/parser.cc"

inline ast::nodes::NameType* ZaneParser::dup_name_type(ast::nodes::NameType* p) 
#line 299 "src/grammar/parser.gr"
{return p; }
#line 966 "src/grammar/parser.cc"

inline void ZaneParser::del_name_type(ast::nodes::NameType* p) 
#line 300 "src/grammar/parser.gr"
{ }
#line 971 "src/grammar/parser.cc"

inline ast::nodes::FunctionType* ZaneParser::dup_function_type(ast::nodes::FunctionType* p) 
#line 310 "src/grammar/parser.gr"
{return p; }
#line 976 "src/grammar/parser.cc"

inline void ZaneParser::del_function_type(ast::nodes::FunctionType* p) 
#line 311 "src/grammar/parser.gr"
{ }
#line 981 "src/grammar/parser.cc"

inline ast::nodes::MethodType* ZaneParser::dup_method_type(ast::nodes::MethodType* p) 
#line 321 "src/grammar/parser.gr"
{return p; }
#line 986 "src/grammar/parser.cc"

inline void ZaneParser::del_method_type(ast::nodes::MethodType* p) 
#line 322 "src/grammar/parser.gr"
{ }
#line 991 "src/grammar/parser.cc"

inline ast::nodes::ArrowBody* ZaneParser::dup_arrow_body(ast::nodes::ArrowBody* p) 
#line 340 "src/grammar/parser.gr"
{return p; }
#line 996 "src/grammar/parser.cc"

inline void ZaneParser::del_arrow_body(ast::nodes::ArrowBody* p) 
#line 341 "src/grammar/parser.gr"
{ }
#line 1001 "src/grammar/parser.cc"

inline grammar_support::FunctionBodyValue* ZaneParser::dup_function_body(grammar_support::FunctionBodyValue* p) 
#line 348 "src/grammar/parser.gr"
{return p; }
#line 1006 "src/grammar/parser.cc"

inline void ZaneParser::del_function_body(grammar_support::FunctionBodyValue* p) 
#line 349 "src/grammar/parser.gr"
{ }
#line 1011 "src/grammar/parser.cc"

inline ast::nodes::Scope* ZaneParser::dup_scope(ast::nodes::Scope* p) 
#line 359 "src/grammar/parser.gr"
{return p; }
#line 1016 "src/grammar/parser.cc"

inline void ZaneParser::del_scope(ast::nodes::Scope* p) 
#line 360 "src/grammar/parser.gr"
{ }
#line 1021 "src/grammar/parser.cc"

inline std::vector<std::unique_ptr<ast::nodes::Statement>>* ZaneParser::dup_statements(std::vector<std::unique_ptr<ast::nodes::Statement>>* p) 
#line 367 "src/grammar/parser.gr"
{return p; }
#line 1026 "src/grammar/parser.cc"

inline void ZaneParser::del_statements(std::vector<std::unique_ptr<ast::nodes::Statement>>* p) 
#line 368 "src/grammar/parser.gr"
{ }
#line 1031 "src/grammar/parser.cc"

inline ast::nodes::Statement* ZaneParser::dup_statement(ast::nodes::Statement* p) 
#line 379 "src/grammar/parser.gr"
{return p; }
#line 1036 "src/grammar/parser.cc"

inline void ZaneParser::del_statement(ast::nodes::Statement* p) 
#line 380 "src/grammar/parser.gr"
{ }
#line 1041 "src/grammar/parser.cc"

inline ast::nodes::FunctionCall* ZaneParser::dup_statement_function_call(ast::nodes::FunctionCall* p) 
#line 390 "src/grammar/parser.gr"
{return p; }
#line 1046 "src/grammar/parser.cc"

inline void ZaneParser::del_statement_function_call(ast::nodes::FunctionCall* p) 
#line 391 "src/grammar/parser.gr"
{ }
#line 1051 "src/grammar/parser.cc"

inline ast::nodes::ValueExpr* ZaneParser::dup_value_expr(ast::nodes::ValueExpr* p) 
#line 398 "src/grammar/parser.gr"
{return p; }
#line 1056 "src/grammar/parser.cc"

inline void ZaneParser::del_value_expr(ast::nodes::ValueExpr* p) 
#line 399 "src/grammar/parser.gr"
{ }
#line 1061 "src/grammar/parser.cc"

inline ast::nodes::ValueExpr* ZaneParser::dup_additive_expr(ast::nodes::ValueExpr* p) 
#line 406 "src/grammar/parser.gr"
{return p; }
#line 1066 "src/grammar/parser.cc"

inline void ZaneParser::del_additive_expr(ast::nodes::ValueExpr* p) 
#line 407 "src/grammar/parser.gr"
{ }
#line 1071 "src/grammar/parser.cc"

inline ast::nodes::ValueExpr* ZaneParser::dup_multiplicative_expr(ast::nodes::ValueExpr* p) 
#line 420 "src/grammar/parser.gr"
{return p; }
#line 1076 "src/grammar/parser.cc"

inline void ZaneParser::del_multiplicative_expr(ast::nodes::ValueExpr* p) 
#line 421 "src/grammar/parser.gr"
{ }
#line 1081 "src/grammar/parser.cc"

inline ast::nodes::ValueExpr* ZaneParser::dup_unary_expr(ast::nodes::ValueExpr* p) 
#line 434 "src/grammar/parser.gr"
{return p; }
#line 1086 "src/grammar/parser.cc"

inline void ZaneParser::del_unary_expr(ast::nodes::ValueExpr* p) 
#line 435 "src/grammar/parser.gr"
{ }
#line 1091 "src/grammar/parser.cc"

inline ast::nodes::ValueExpr* ZaneParser::dup_postfix_expr(ast::nodes::ValueExpr* p) 
#line 445 "src/grammar/parser.gr"
{return p; }
#line 1096 "src/grammar/parser.cc"

inline void ZaneParser::del_postfix_expr(ast::nodes::ValueExpr* p) 
#line 446 "src/grammar/parser.gr"
{ }
#line 1101 "src/grammar/parser.cc"

inline ast::nodes::FunctionCall* ZaneParser::dup_call_expr(ast::nodes::FunctionCall* p) 
#line 456 "src/grammar/parser.gr"
{return p; }
#line 1106 "src/grammar/parser.cc"

inline void ZaneParser::del_call_expr(ast::nodes::FunctionCall* p) 
#line 457 "src/grammar/parser.gr"
{ }
#line 1111 "src/grammar/parser.cc"

inline ast::nodes::ValueExpr* ZaneParser::dup_primary_expr(ast::nodes::ValueExpr* p) 
#line 473 "src/grammar/parser.gr"
{return p; }
#line 1116 "src/grammar/parser.cc"

inline void ZaneParser::del_primary_expr(ast::nodes::ValueExpr* p) 
#line 474 "src/grammar/parser.gr"
{ }
#line 1121 "src/grammar/parser.cc"

inline ast::nodes::ParenthizedValue* ZaneParser::dup_parenthized_value(ast::nodes::ParenthizedValue* p) 
#line 509 "src/grammar/parser.gr"
{return p; }
#line 1126 "src/grammar/parser.cc"

inline void ZaneParser::del_parenthized_value(ast::nodes::ParenthizedValue* p) 
#line 510 "src/grammar/parser.gr"
{ }
#line 1131 "src/grammar/parser.cc"

inline std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* ZaneParser::dup_arguments(std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* p) 
#line 517 "src/grammar/parser.gr"
{return p; }
#line 1136 "src/grammar/parser.cc"

inline void ZaneParser::del_arguments(std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* p) 
#line 518 "src/grammar/parser.gr"
{ }
#line 1141 "src/grammar/parser.cc"

inline std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* ZaneParser::dup_argument_list(std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* p) 
#line 528 "src/grammar/parser.gr"
{return p; }
#line 1146 "src/grammar/parser.cc"

inline void ZaneParser::del_argument_list(std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* p) 
#line 529 "src/grammar/parser.gr"
{ }
#line 1151 "src/grammar/parser.cc"

SemanticValue ZaneParser::duplicateNontermValue(int nontermId, SemanticValue sval)
{
  switch (nontermId) {
    case 2:
      return (SemanticValue)dup_package((ast::nodes::Package*)sval);
    case 3:
      return (SemanticValue)dup_global_scope((std::vector<ast::nodes::Declaration>*)sval);
    case 4:
      return (SemanticValue)dup_declaration((ast::nodes::Declaration*)sval);
    case 5:
      return (SemanticValue)dup_variable_decl((ast::nodes::VariableDecl*)sval);
    case 6:
      return (SemanticValue)dup_function_decl((ast::nodes::FunctionDecl*)sval);
    case 7:
      return (SemanticValue)dup_method_decl((ast::nodes::MethodDecl*)sval);
    case 8:
      return (SemanticValue)dup_parameters((std::vector<ast::nodes::Parameter>*)sval);
    case 9:
      return (SemanticValue)dup_parameter_list((std::vector<ast::nodes::Parameter>*)sval);
    case 10:
      return (SemanticValue)dup_method_parameters((std::vector<ast::nodes::Parameter>*)sval);
    case 11:
      return (SemanticValue)dup_method_parameter_seq((std::vector<ast::nodes::Parameter>*)sval);
    case 12:
      return (SemanticValue)dup_parameter((ast::nodes::Parameter*)sval);
    case 13:
      return (SemanticValue)dup_type_list((std::vector<std::unique_ptr<ast::nodes::TypeExpression>>*)sval);
    case 14:
      return (SemanticValue)dup_type_list_ne((std::vector<std::unique_ptr<ast::nodes::TypeExpression>>*)sval);
    case 15:
      return (SemanticValue)dup_type_expr((ast::nodes::TypeExpression*)sval);
    case 16:
      return (SemanticValue)dup_name_type((ast::nodes::NameType*)sval);
    case 17:
      return (SemanticValue)dup_function_type((ast::nodes::FunctionType*)sval);
    case 18:
      return (SemanticValue)dup_method_type((ast::nodes::MethodType*)sval);
    case 19:
      return (SemanticValue)dup_arrow_body((ast::nodes::ArrowBody*)sval);
    case 20:
      return (SemanticValue)dup_function_body((grammar_support::FunctionBodyValue*)sval);
    case 21:
      return (SemanticValue)dup_scope((ast::nodes::Scope*)sval);
    case 22:
      return (SemanticValue)dup_statements((std::vector<std::unique_ptr<ast::nodes::Statement>>*)sval);
    case 23:
      return (SemanticValue)dup_statement((ast::nodes::Statement*)sval);
    case 24:
      return (SemanticValue)dup_statement_function_call((ast::nodes::FunctionCall*)sval);
    case 25:
      return (SemanticValue)dup_value_expr((ast::nodes::ValueExpr*)sval);
    case 26:
      return (SemanticValue)dup_additive_expr((ast::nodes::ValueExpr*)sval);
    case 27:
      return (SemanticValue)dup_multiplicative_expr((ast::nodes::ValueExpr*)sval);
    case 28:
      return (SemanticValue)dup_unary_expr((ast::nodes::ValueExpr*)sval);
    case 29:
      return (SemanticValue)dup_postfix_expr((ast::nodes::ValueExpr*)sval);
    case 30:
      return (SemanticValue)dup_call_expr((ast::nodes::FunctionCall*)sval);
    case 31:
      return (SemanticValue)dup_primary_expr((ast::nodes::ValueExpr*)sval);
    case 32:
      return (SemanticValue)dup_parenthized_value((ast::nodes::ParenthizedValue*)sval);
    case 33:
      return (SemanticValue)dup_arguments((std::vector<std::unique_ptr<ast::nodes::ValueExpr>>*)sval);
    case 34:
      return (SemanticValue)dup_argument_list((std::vector<std::unique_ptr<ast::nodes::ValueExpr>>*)sval);
    default:
      return (SemanticValue)0;
  }
}

void ZaneParser::deallocateNontermValue(int nontermId, SemanticValue sval)
{
  switch (nontermId) {
    case 2:
      del_package((ast::nodes::Package*)sval);
      return;
    case 3:
      del_global_scope((std::vector<ast::nodes::Declaration>*)sval);
      return;
    case 4:
      del_declaration((ast::nodes::Declaration*)sval);
      return;
    case 5:
      del_variable_decl((ast::nodes::VariableDecl*)sval);
      return;
    case 6:
      del_function_decl((ast::nodes::FunctionDecl*)sval);
      return;
    case 7:
      del_method_decl((ast::nodes::MethodDecl*)sval);
      return;
    case 8:
      del_parameters((std::vector<ast::nodes::Parameter>*)sval);
      return;
    case 9:
      del_parameter_list((std::vector<ast::nodes::Parameter>*)sval);
      return;
    case 10:
      del_method_parameters((std::vector<ast::nodes::Parameter>*)sval);
      return;
    case 11:
      del_method_parameter_seq((std::vector<ast::nodes::Parameter>*)sval);
      return;
    case 12:
      del_parameter((ast::nodes::Parameter*)sval);
      return;
    case 13:
      del_type_list((std::vector<std::unique_ptr<ast::nodes::TypeExpression>>*)sval);
      return;
    case 14:
      del_type_list_ne((std::vector<std::unique_ptr<ast::nodes::TypeExpression>>*)sval);
      return;
    case 15:
      del_type_expr((ast::nodes::TypeExpression*)sval);
      return;
    case 16:
      del_name_type((ast::nodes::NameType*)sval);
      return;
    case 17:
      del_function_type((ast::nodes::FunctionType*)sval);
      return;
    case 18:
      del_method_type((ast::nodes::MethodType*)sval);
      return;
    case 19:
      del_arrow_body((ast::nodes::ArrowBody*)sval);
      return;
    case 20:
      del_function_body((grammar_support::FunctionBodyValue*)sval);
      return;
    case 21:
      del_scope((ast::nodes::Scope*)sval);
      return;
    case 22:
      del_statements((std::vector<std::unique_ptr<ast::nodes::Statement>>*)sval);
      return;
    case 23:
      del_statement((ast::nodes::Statement*)sval);
      return;
    case 24:
      del_statement_function_call((ast::nodes::FunctionCall*)sval);
      return;
    case 25:
      del_value_expr((ast::nodes::ValueExpr*)sval);
      return;
    case 26:
      del_additive_expr((ast::nodes::ValueExpr*)sval);
      return;
    case 27:
      del_multiplicative_expr((ast::nodes::ValueExpr*)sval);
      return;
    case 28:
      del_unary_expr((ast::nodes::ValueExpr*)sval);
      return;
    case 29:
      del_postfix_expr((ast::nodes::ValueExpr*)sval);
      return;
    case 30:
      del_call_expr((ast::nodes::FunctionCall*)sval);
      return;
    case 31:
      del_primary_expr((ast::nodes::ValueExpr*)sval);
      return;
    case 32:
      del_parenthized_value((ast::nodes::ParenthizedValue*)sval);
      return;
    case 33:
      del_arguments((std::vector<std::unique_ptr<ast::nodes::ValueExpr>>*)sval);
      return;
    case 34:
      del_argument_list((std::vector<std::unique_ptr<ast::nodes::ValueExpr>>*)sval);
      return;
    default:
      std::cout << "WARNING: there is no action to deallocate nonterm "
           << nontermNames[nontermId] << std::endl;
  }
}

SemanticValue ZaneParser::mergeAlternativeParses(int nontermId, SemanticValue left,
                                           SemanticValue right,  SourceLoc loc)
{
  switch (nontermId) {
    default:
      std::cout << toString(loc) 
           << ": error: there is no action to merge nonterm "
           << nontermNames[nontermId] << std::endl;
      abort();
  }
}

bool ZaneParser::keepNontermValue(int nontermId, SemanticValue sval)
{
  switch (nontermId) {
    default:
      return true;
  }
}


// ---------------- dup/del/classify terminals ---------------
inline std::string* ZaneParser::dup_TOK_STRING(std::string* s) 
#line 99 "src/grammar/parser.gr"
{return new std::string(*s); }
#line 1360 "src/grammar/parser.cc"

inline void ZaneParser::del_TOK_STRING(std::string* s) 
#line 100 "src/grammar/parser.gr"
{delete s; }
#line 1365 "src/grammar/parser.cc"

inline std::string* ZaneParser::dup_TOK_IDENT(std::string* s) 
#line 103 "src/grammar/parser.gr"
{return new std::string(*s); }
#line 1370 "src/grammar/parser.cc"

inline void ZaneParser::del_TOK_IDENT(std::string* s) 
#line 104 "src/grammar/parser.gr"
{delete s; }
#line 1375 "src/grammar/parser.cc"

inline std::string* ZaneParser::dup_TOK_INT(std::string* s) 
#line 107 "src/grammar/parser.gr"
{return new std::string(*s); }
#line 1380 "src/grammar/parser.cc"

inline void ZaneParser::del_TOK_INT(std::string* s) 
#line 108 "src/grammar/parser.gr"
{delete s; }
#line 1385 "src/grammar/parser.cc"

inline std::string* ZaneParser::dup_TOK_FLOAT(std::string* s) 
#line 111 "src/grammar/parser.gr"
{return new std::string(*s); }
#line 1390 "src/grammar/parser.cc"

inline void ZaneParser::del_TOK_FLOAT(std::string* s) 
#line 112 "src/grammar/parser.gr"
{delete s; }
#line 1395 "src/grammar/parser.cc"

SemanticValue ZaneParser::duplicateTerminalValue(int termId, SemanticValue sval)
{
  switch (termId) {
    case 0:
      return sval;
    case 1:
      return sval;
    case 2:
      return sval;
    case 3:
      return sval;
    case 4:
      return sval;
    case 5:
      return sval;
    case 6:
      return sval;
    case 7:
      return sval;
    case 8:
      return sval;
    case 9:
      return sval;
    case 10:
      return sval;
    case 11:
      return sval;
    case 12:
      return sval;
    case 13:
      return sval;
    case 14:
      return (SemanticValue)dup_TOK_STRING((std::string*)sval);
    case 15:
      return (SemanticValue)dup_TOK_IDENT((std::string*)sval);
    case 16:
      return (SemanticValue)dup_TOK_INT((std::string*)sval);
    case 17:
      return (SemanticValue)dup_TOK_FLOAT((std::string*)sval);
    case 18:
      return sval;
    case 19:
      return sval;
    case 20:
      return sval;
    case 21:
      return sval;
    case 22:
      return sval;
    case 23:
      return sval;
    default:
      return (SemanticValue)0;
  }
}

void ZaneParser::deallocateTerminalValue(int termId, SemanticValue sval)
{
  switch (termId) {
    case 0:
      break;
    case 1:
      break;
    case 2:
      break;
    case 3:
      break;
    case 4:
      break;
    case 5:
      break;
    case 6:
      break;
    case 7:
      break;
    case 8:
      break;
    case 9:
      break;
    case 10:
      break;
    case 11:
      break;
    case 12:
      break;
    case 13:
      break;
    case 14:
      del_TOK_STRING((std::string*)sval);
      return;
    case 15:
      del_TOK_IDENT((std::string*)sval);
      return;
    case 16:
      del_TOK_INT((std::string*)sval);
      return;
    case 17:
      del_TOK_FLOAT((std::string*)sval);
      return;
    case 18:
      break;
    case 19:
      break;
    case 20:
      break;
    case 21:
      break;
    case 22:
      break;
    case 23:
      break;
    default:
      int arrayMin = 0;
      int arrayMax = 24;
      xassert(termId >= arrayMin && termId < arrayMax);
      std::cout << "WARNING: there is no action to deallocate terminal "
        << termNames[termId] << std::endl;
  }
}

/*static*/ int ZaneParser::reclassifyToken(ZaneParser *ths, int oldTokenType, SemanticValue sval)
{
  switch (oldTokenType) {
    default:
      return oldTokenType;
  }
}

UserActions::ReclassifyFunc ZaneParser::getReclassifier()
{
  return (ReclassifyFunc)&ZaneParser::reclassifyToken;
}


// this makes a ParseTables from some literal data;
// the code is written by ParseTables::emitConstructionCode()
// in /build/source/src/elkhound/parsetables.cc
class ZaneParser_ParseTables : public ParseTables {
public:
  ZaneParser_ParseTables();
};

ZaneParser_ParseTables::ZaneParser_ParseTables()
  : ParseTables(false /*owning*/)
{
  numTerms = 24;
  numNonterms = 35;
  numStates = 106;
  numProds = 63;
  actionCols = 24;
  actionRows = 106;
  gotoCols = 35;
  gotoRows = 106;
  ambigTableSize = 12;
  startState = (StateId)0;
  finalProductionIndex = 0;
  bigProductionListSize = 0;
  errorBitsRowSize = 4;
  uniqueErrorRows = 0;

  // storage size: 5088 bytes
  // rows: 106  cols: 24
  static ActionEntry const actionTable_static[2544] = {
    /*  0*/ -3, -3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -3, 0, 0, 0, 0, 0, 0, 0, 0, 
    /*  1*/ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    /*  2*/ 0, 3, -19, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 31, 0, 39, 0, 0, 0, 0, 0, 0, 0, 0, 
    /*  3*/ 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 28, 0, 0, 33, 38, 42, 43, 0, 0, 0, 0, 48, 0, 
    /*  4*/ 0, 4, -60, 0, 0, 0, 0, 0, 0, 0, 0, 28, 0, 0, 33, 38, 42, 43, 0, 0, 0, 0, 48, 0, 
    /*  5*/ 0, 4, -60, 0, 0, 0, 0, 0, 0, 0, 0, 28, 0, 0, 33, 38, 42, 43, 0, 0, 0, 0, 48, 0, 
    /*  6*/ 0, 0, -11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 35, 0, 0, 0, 0, 0, 0, 0, 0, 
    /*  7*/ 0, 0, 0, 15, 0, 0, 0, 0, 0, 0, 27, 0, 29, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    /*  8*/ 0, 0, 0, 15, 0, 0, 0, 0, 0, 0, 27, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    /*  9*/ 0, 0, 0, 0, 0, 0, 0, 0, 0, 25, 0, 0, 30, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 10*/ 0, 0, 0, 0, 0, 0, 0, 0, 0, 26, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 11*/ -51, -51, -51, 0, -51, -51, 0, 0, 0, 0, 0, -51, 0, 0, -51, -51, -51, -51, -51, -51, -51, -51, 0, 0, 
    /* 12*/ -50, -50, -50, 0, -50, -50, 0, 0, 0, 0, 0, -50, 0, 0, -50, -50, -50, -50, -50, -50, -50, -50, 0, 0, 
    /* 13*/ -59, -59, -59, 0, -59, -59, 0, 0, 0, 0, 0, -59, 0, 0, -59, -59, -59, -59, -59, -59, -59, -59, 0, 0, 
    /* 14*/ 0, -34, 0, 0, -34, 0, 0, 0, 0, 0, 0, -34, 0, 0, -34, -34, -34, -34, 0, 0, 0, 0, 0, 0, 
    /* 15*/ -33, -33, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -33, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 16*/ 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 39, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 17*/ 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 28, 0, 0, 33, 38, 42, 43, 0, 0, 0, 0, 48, 0, 
    /* 18*/ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 35, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 19*/ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 35, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 20*/ 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 28, 0, 0, 33, 38, 42, 43, 0, 0, 0, 0, 48, 0, 
    /* 21*/ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 22*/ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 41, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 23*/ 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 39, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 24*/ 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 39, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 25*/ 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 39, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 26*/ 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 28, 0, 0, 33, 38, 42, 43, 0, 0, 0, 0, 48, 0, 
    /* 27*/ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 37, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 28*/ 0, 0, 0, 15, 0, 0, 0, 0, 0, 0, 27, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 29*/ 0, 0, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 30*/ 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 39, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 31*/ 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 39, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 32*/ -57, -57, -57, 0, -57, -57, 0, 0, 0, 0, 0, -57, 0, 0, -57, -57, -57, -57, -57, -57, -57, -57, 0, 0, 
    /* 33*/ 0, 107, 0, 0, 0, 0, 0, 0, 23, 0, 0, 0, 0, 0, 0, 39, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 34*/ 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 39, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 35*/ 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 36*/ 0, 0, 0, 0, 0, 0, 0, 0, 22, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 37*/ -52, -52, -52, 0, -52, -52, 0, 0, 23, 0, 0, -52, 0, 0, -52, -52, -52, -52, -52, -52, -52, -52, 0, 0, 
    /* 38*/ 0, 0, -26, 0, 0, -26, 0, -26, 0, 0, 0, 0, 0, 0, 0, -26, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 39*/ -54, -54, -54, 0, -54, -54, 0, 0, 0, 0, 0, -54, 0, 0, -54, -54, -54, -54, -54, -54, -54, -54, 0, 0, 
    /* 40*/ -53, -53, -53, 0, -53, -53, 0, 0, 0, 0, 0, -53, 0, 0, -53, -53, -53, -53, -53, -53, -53, -53, 0, 0, 
    /* 41*/ -55, -55, -55, 0, -55, -55, 0, 0, 0, 0, 0, -55, 0, 0, -55, -55, -55, -55, -55, -55, -55, -55, 0, 0, 
    /* 42*/ -56, -56, -56, 0, -56, -56, 0, 0, 0, 0, 0, -56, 0, 0, -56, -56, -56, -56, -56, -56, -56, -56, 0, 0, 
    /* 43*/ 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 28, 0, 0, 33, 38, 42, 43, 0, 0, 0, 0, 48, 0, 
    /* 44*/ 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 28, 0, 0, 33, 38, 42, 43, 0, 0, 0, 0, 48, 0, 
    /* 45*/ 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 28, 0, 0, 33, 38, 42, 43, 0, 0, 0, 0, 48, 0, 
    /* 46*/ 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 28, 0, 0, 33, 38, 42, 43, 0, 0, 0, 0, 48, 0, 
    /* 47*/ 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 28, 0, 0, 33, 38, 42, 43, 0, 0, 0, 0, 48, 0, 
    /* 48*/ 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 49*/ -2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 39, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 50*/ -4, -4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -4, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 51*/ 0, -37, 0, 0, -37, 0, 0, 0, 0, 0, 0, -37, 0, 0, -37, -37, -37, -37, 0, 0, 0, 0, 0, 0, 
    /* 52*/ -5, -5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -5, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 53*/ -6, -6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -6, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 54*/ 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 55*/ 0, 0, -12, 0, 0, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 56*/ 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 57*/ 0, 0, -15, 0, 0, 19, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 58*/ 0, 0, -14, 0, 0, -14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 59*/ 0, 0, -13, 0, 0, -13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 60*/ 0, 0, -17, 0, 0, -17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 61*/ 0, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 62*/ 0, 0, 10, 0, 0, 17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 63*/ 0, 0, -20, 0, 0, 17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 64*/ 0, 0, 0, 0, 0, 0, 0, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 65*/ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 36, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 66*/ 0, 0, -16, 0, 0, -16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 67*/ 0, 0, -18, 0, 0, -18, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 68*/ 0, 0, -22, 0, 0, -22, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 69*/ 0, 0, -21, 0, 0, -21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 70*/ 0, 0, -27, 0, 0, -27, 0, -27, 0, 0, 0, 0, 0, 0, 0, -27, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 71*/ 0, 0, -28, 0, 0, -28, 0, -28, 0, 0, 0, 0, 0, 0, 0, -28, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 72*/ 0, 0, -29, 0, 0, -29, 0, -29, 0, 0, 0, 0, 0, 0, 0, -29, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 73*/ 0, 0, -23, 0, 0, -23, 0, -23, 0, 0, 0, 0, 0, 0, 0, -23, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 74*/ 0, 0, -24, 0, 0, -24, 0, -24, 0, 0, 0, 0, 0, 0, 0, -24, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 75*/ 0, 0, -25, 0, 0, -25, 0, -25, 0, 0, 0, 0, 0, 0, 0, -25, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 76*/ -31, -31, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -31, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 77*/ -8, -8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -8, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 78*/ -9, -9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -9, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 79*/ -10, -10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -10, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 80*/ -32, -32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -32, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 81*/ 0, 4, 0, 0, 16, 0, 0, 0, 0, 0, 0, 28, 0, 0, 33, 34, 42, 43, 0, 0, 0, 0, 0, 0, 
    /* 82*/ 0, -35, 0, 0, -35, 0, 0, 0, 0, 0, 0, -35, 0, 0, -35, -35, -35, -35, 0, 0, 0, 0, 0, 0, 
    /* 83*/ 0, -36, 0, 0, -36, 0, 0, 0, 0, 0, 0, -36, 0, 0, -36, -36, -36, -36, 0, 0, 0, 0, 0, 0, 
    /* 84*/ 0, 0, 14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 85*/ 0, 0, -62, 0, 0, -62, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 86*/ 0, 0, -63, 0, 0, -63, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 87*/ 0, -7, 0, 0, -7, 0, 0, 0, 0, 0, 0, -7, 0, 0, -7, -7, -7, -7, 0, 0, 0, 0, 0, 0, 
    /* 88*/ -30, -30, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -30, 0, 0, 0, 0, 0, 0, 0, 0, 
    /* 89*/ -39, -39, -39, 0, -39, -39, 0, 0, 0, 0, 0, -39, 0, 0, -39, -39, -39, -39, 44, 45, 0, 0, 0, 0, 
    /* 90*/ -41, -41, -41, 0, -41, -41, 0, 0, 0, 0, 0, -41, 0, 0, -41, -41, -41, -41, -41, -41, 46, 47, 0, 0, 
    /* 91*/ -42, -42, -42, 0, -42, -42, 0, 0, 0, 0, 0, -42, 0, 0, -42, -42, -42, -42, -42, -42, 46, 47, 0, 0, 
    /* 92*/ -40, -40, -40, 0, -40, -40, 0, 0, 0, 0, 0, -40, 0, 0, -40, -40, -40, -40, -40, -40, 46, 47, 0, 0, 
    /* 93*/ -44, -44, -44, 0, -44, -44, 0, 0, 0, 0, 0, -44, 0, 0, -44, -44, -44, -44, -44, -44, -44, -44, 0, 0, 
    /* 94*/ -45, -45, -45, 0, -45, -45, 0, 0, 0, 0, 0, -45, 0, 0, -45, -45, -45, -45, -45, -45, -45, -45, 0, 0, 
    /* 95*/ -43, -43, -43, 0, -43, -43, 0, 0, 0, 0, 0, -43, 0, 0, -43, -43, -43, -43, -43, -43, -43, -43, 0, 0, 
    /* 96*/ -47, -47, -47, 0, -47, -47, 0, 0, 0, 0, 0, -47, 0, 0, -47, -47, -47, -47, -47, -47, -47, -47, 0, 0, 
    /* 97*/ -46, -46, -46, 0, -46, -46, 0, 0, 0, 0, 0, -46, 0, 0, -46, -46, -46, -46, -46, -46, -46, -46, 0, 0, 
    /* 98*/ 0, 110, 0, 0, -38, 0, 0, 0, 0, 0, 0, -38, 0, 0, -38, -38, -38, -38, 0, 0, 0, 0, 0, 0, 
    /* 99*/ -49, 113, -49, 0, -49, -49, 0, 0, 0, 0, 0, -49, 0, 0, -49, -49, -49, -49, -49, -49, -49, -49, 0, 0, 
    /*100*/ 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    /*101*/ -48, 116, -48, 0, -48, -48, 0, 0, 0, 0, 0, -48, 0, 0, -48, -48, -48, -48, -48, -48, -48, -48, 0, 0, 
    /*102*/ -58, -58, -58, 0, -58, -58, 0, 0, 0, 0, 0, -58, 0, 0, -58, -58, -58, -58, -58, -58, -58, -58, 0, 0, 
    /*103*/ 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    /*104*/ 0, 0, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    /*105*/ 0, 0, -61, 0, 0, 18, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
  };
  actionTable = const_cast<ActionEntry*>(actionTable_static);

  // storage size: 7420 bytes
  // rows: 106  cols: 35
  static GotoEntry const gotoTable_static[3710] = {
    /*  0*/ 65535, 65535, 48, 49, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /*  1*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /*  2*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 61, 63, 69, 73, 74, 75, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /*  3*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 84, 89, 92, 95, 97, 99, 101, 102, 65535, 65535, 
    /*  4*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 85, 89, 92, 95, 97, 99, 101, 102, 103, 105, 
    /*  5*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 85, 89, 92, 95, 97, 99, 101, 102, 104, 105, 
    /*  6*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 54, 55, 56, 57, 59, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /*  7*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 76, 78, 80, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /*  8*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 76, 77, 80, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /*  9*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 10*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 11*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 12*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 13*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 14*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 81, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 15*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 16*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 68, 73, 74, 75, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 17*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 86, 89, 92, 95, 97, 99, 101, 102, 65535, 65535, 
    /* 18*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 60, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 19*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 58, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 20*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 87, 89, 92, 95, 97, 99, 101, 102, 65535, 65535, 
    /* 21*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 22*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 23*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 72, 73, 74, 75, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 24*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 71, 73, 74, 75, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 25*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 70, 73, 74, 75, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 26*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 88, 89, 92, 95, 97, 99, 101, 102, 65535, 65535, 
    /* 27*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 28*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 76, 79, 80, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 29*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 30*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 62, 69, 73, 74, 75, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 31*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 66, 73, 74, 75, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 32*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 33*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 64, 73, 74, 75, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 34*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 67, 73, 74, 75, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 35*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 36*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 37*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 38*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 39*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 40*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 41*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 42*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 43*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 90, 95, 97, 99, 101, 102, 65535, 65535, 
    /* 44*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 91, 95, 97, 99, 101, 102, 65535, 65535, 
    /* 45*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 93, 97, 99, 101, 102, 65535, 65535, 
    /* 46*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 94, 97, 99, 101, 102, 65535, 65535, 
    /* 47*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 96, 97, 99, 101, 102, 65535, 65535, 
    /* 48*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 49*/ 65535, 65535, 65535, 65535, 50, 65535, 52, 53, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65, 73, 74, 75, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 50*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 51*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 52*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 53*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 54*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 55*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 56*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 57*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 58*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 59*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 60*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 61*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 62*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 63*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 64*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 65*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 66*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 67*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 68*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 69*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 70*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 71*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 72*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 73*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 74*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 75*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 76*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 77*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 78*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 79*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 80*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 81*/ 65535, 65535, 65535, 65535, 65535, 51, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 82, 83, 65535, 65535, 65535, 65535, 65535, 98, 100, 102, 65535, 65535, 
    /* 82*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 83*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 84*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 85*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 86*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 87*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 88*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 89*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 90*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 91*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 92*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 93*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 94*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 95*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 96*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 97*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 98*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /* 99*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /*100*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /*101*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /*102*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /*103*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /*104*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
    /*105*/ 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 
  };
  gotoTable = const_cast<GotoEntry*>(gotoTable_static);

  // storage size: 252 bytes
  static ParseTables::ProdInfo const prodInfo_static[63] = {
    /*0*/ {2,1}, {1,2}, {0,3}, {2,3}, {1,4}, {1,4}, {4,5}, {6,6}, {6,7}, {7,7}, {0,8}, {1,8}, {1,9}, {3,9}, {1,10}, {2,11}, 
    /*1*/ {3,11}, {2,12}, {0,13}, {1,13}, {1,14}, {3,14}, {1,15}, {1,15}, {1,15}, {1,16}, {5,17}, {6,18}, {7,18}, {2,19}, {1,20}, {1,20}, 
    /*2*/ {3,21}, {0,22}, {2,22}, {1,23}, {1,23}, {1,24}, {1,25}, {1,26}, {3,26}, {3,26}, {1,27}, {3,27}, {3,27}, {1,28}, {2,28}, {1,29}, 
    /*3*/ {1,29}, {4,30}, {4,30}, {1,31}, {3,31}, {4,31}, {1,31}, {1,31}, {1,31}, {1,31}, {3,32}, {0,33}, {1,33}, {1,34}, {3,34}, 
  };
  prodInfo = const_cast<ParseTables::ProdInfo*>(prodInfo_static);

  // storage size: 212 bytes
  static SymbolId const stateSymbol_static[106] = {
    /*0*/ 0, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 4, 5, 
    /*1*/ 6, 6, 6, 6, 8, 9, 9, 10, 10, 10, 11, 12, 13, 13, 14, 14, 
    /*2*/ 15, 16, 16, 16, 16, 16, 16, 16, 16, 17, 18, 19, 20, 21, 22, 23, 
    /*3*/ -3, -4, -5, -6, -7, -8, -9, -10, -11, -12, -13, -13, -13, -14, -15, -15, 
    /*4*/ -16, -16, -16, -16, -16, -16, -16, -16, -16, -17, -18, -19, -20, -21, -21, -21, 
    /*5*/ -22, -23, -24, -25, -26, -26, -26, -26, -26, -27, -28, -28, -28, -29, -29, -29, 
    /*6*/ -29, -30, -31, -31, -32, -32, -33, -34, -34, -35, 
  };
  stateSymbol = const_cast<SymbolId*>(stateSymbol_static);

  static ActionEntry const ambigTable_static[12] = {
    /*0*/ 2, 3, -52, 2, 5, -38, 2, 5, -49, 2, 6, -48, 
  };
  ambigTable = const_cast<ActionEntry*>(ambigTable_static);

  // storage size: 70 bytes
  static NtIndex const nontermOrder_static[35] = {
    /*0*/ 28, 27, 34, 33, 26, 24, 23, 22, 32, 21, 20, 19, 18, 31, 17, 16, 
    /*1*/ 15, 14, 13, 11, 12, 10, 30, 25, 9, 7, 6, 5, 4, 3, 2, 1, 
    /*2*/ 0, 29, 8, 
  };
  nontermOrder = const_cast<NtIndex*>(nontermOrder_static);

  ErrorBitsEntry *errorBits_static = NULL;
  errorBits = const_cast<ErrorBitsEntry*>(errorBits_static);

  errorBitsPointers = NULL;

  TermIndex *actionIndexMap_static = NULL;
  actionIndexMap = const_cast<TermIndex*>(actionIndexMap_static);

  actionRowPointers = NULL;

  NtIndex *gotoIndexMap_static = NULL;
  gotoIndexMap = const_cast<NtIndex*>(gotoIndexMap_static);

  gotoRowPointers = NULL;

  firstWithTerminal = NULL;
  firstWithNonterminal = NULL;
  bigProductionList = NULL;
  productionsForState = NULL;
  ambigStateTable = NULL;
}


ParseTables *ZaneParser::makeTables()
{
  return new ZaneParser_ParseTables;
}

