// src/grammar/parser.h
// *** DO NOT EDIT BY HAND ***
// automatically generated by elkhound, from src/grammar/parser.gr

#ifndef SRC_GRAMMAR_PARSER_H
#define SRC_GRAMMAR_PARSER_H

#include "useract.h"     // UserActions


#line 1 "src/grammar/parser.gr"

	#include "ast/.hpp"
	#include <memory>
	#include <string>
	#include <utility>
	#include <variant>
	#include <vector>

	namespace grammarSupport {

	using FunctionBody = std::variant<ast::nodes::Scope, ast::nodes::ArrowBody>;

	template <typename T>
	T takeValue(T* ptr) {
		T value = std::move(*ptr);
		delete ptr;
		return value;
	}

	template <typename T>
	std::unique_ptr<T> takePtr(T* ptr) {
		return std::unique_ptr<T>(ptr);
	}

	inline std::string takeString(std::string* ptr) {
		std::string value = std::move(*ptr);
		delete ptr;
		return value;
	}

	inline ast::nodes::ValueExpr* makeBinary(
		std::string op,
		ast::nodes::ValueExpr* left,
		ast::nodes::ValueExpr* right
	) {
		return new ast::nodes::ValueExpr(
			ast::nodes::OperatorCall(
				std::move(op),
				takePtr(left),
				takePtr(right)
			)
		);
	}

	inline ast::nodes::ValueExpr* makeFlip(ast::nodes::ValueExpr* value) {
		return new ast::nodes::ValueExpr(ast::nodes::OperatorFlipCall(takePtr(value)));
	}

	inline ast::nodes::ValueExpr* wrapCall(ast::nodes::FunctionCall* call) {
		return new ast::nodes::ValueExpr(takeValue(call));
	}

	} // namespace grammarSupport

#line 67 "src/grammar/parser.h"


// parser context class
class 
#line 58 "src/grammar/parser.gr"
 ZaneParser : public UserActions {
public:
	// generated parser hooks are added by Elkhound

#line 77 "src/grammar/parser.h"


private:
  USER_ACTION_FUNCTIONS      // see useract.h

  // declare the actual action function
  static SemanticValue doReductionAction(
    ZaneParser *ths,
    int productionId, SemanticValue const *semanticValues,
  SourceLoc loc);

  // declare the classifier function
  static int reclassifyToken(
    ZaneParser *ths,
    int oldTokenType, SemanticValue sval);

  int action0___EarlyStartSymbol(SourceLoc loc, int top);
  int action1_may_break(SourceLoc loc);
  int action2_may_break(SourceLoc loc);
  ast::nodes::Package* action3_package(SourceLoc loc, std::vector<ast::nodes::Declaration>* declarations);
  std::vector<ast::nodes::Declaration>* action4_global_scope(SourceLoc loc);
  std::vector<ast::nodes::Declaration>* action5_global_scope(SourceLoc loc, ast::nodes::Declaration* declaration);
  std::vector<ast::nodes::Declaration>* action6_global_scope(SourceLoc loc, std::vector<ast::nodes::Declaration>* declarations, ast::nodes::Declaration* declaration);
  ast::nodes::Declaration* action7_declaration(SourceLoc loc, ast::nodes::FunctionDecl* function);
  ast::nodes::Declaration* action8_declaration(SourceLoc loc, ast::nodes::MethodDecl* method);
  ast::nodes::VariableDecl* action9_variable_decl(SourceLoc loc, std::string* name, ast::nodes::TypeExpression* type, ast::nodes::ValueExpr* value);
  ast::nodes::FunctionDecl* action10_function_decl(SourceLoc loc, ast::nodes::TypeExpression* return_type, std::string* name, std::vector<ast::nodes::Parameter>* params, grammarSupport::FunctionBody* body);
  ast::nodes::MethodDecl* action11_method_decl(SourceLoc loc, ast::nodes::TypeExpression* return_type, std::string* name, std::vector<ast::nodes::Parameter>* params, grammarSupport::FunctionBody* body);
  ast::nodes::MethodDecl* action12_method_decl(SourceLoc loc, ast::nodes::TypeExpression* return_type, std::string* name, std::vector<ast::nodes::Parameter>* params, grammarSupport::FunctionBody* body);
  std::vector<ast::nodes::Parameter>* action13_parameters(SourceLoc loc);
  std::vector<ast::nodes::Parameter>* action14_parameters(SourceLoc loc, std::vector<ast::nodes::Parameter>* list);
  std::vector<ast::nodes::Parameter>* action15_parameter_list(SourceLoc loc, ast::nodes::Parameter* parameter);
  std::vector<ast::nodes::Parameter>* action16_parameter_list(SourceLoc loc, std::vector<ast::nodes::Parameter>* list, ast::nodes::Parameter* parameter);
  std::vector<ast::nodes::Parameter>* action17_method_parameters(SourceLoc loc, std::vector<ast::nodes::Parameter>* list);
  std::vector<ast::nodes::Parameter>* action18_method_parameter_seq(SourceLoc loc, ast::nodes::TypeExpression* type);
  std::vector<ast::nodes::Parameter>* action19_method_parameter_seq(SourceLoc loc, std::vector<ast::nodes::Parameter>* list, ast::nodes::Parameter* parameter);
  ast::nodes::Parameter* action20_parameter(SourceLoc loc, std::string* name, ast::nodes::TypeExpression* type);
  std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* action21_type_list(SourceLoc loc);
  std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* action22_type_list(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* list);
  std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* action23_type_list_ne(SourceLoc loc, ast::nodes::TypeExpression* expr);
  std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* action24_type_list_ne(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* list, ast::nodes::TypeExpression* expr);
  ast::nodes::TypeExpression* action25_type_expr(SourceLoc loc, ast::nodes::NameType* name);
  ast::nodes::TypeExpression* action26_type_expr(SourceLoc loc, ast::nodes::FunctionType* function);
  ast::nodes::TypeExpression* action27_type_expr(SourceLoc loc, ast::nodes::MethodType* method);
  ast::nodes::NameType* action28_name_type(SourceLoc loc, std::string* identifier);
  ast::nodes::FunctionType* action29_function_type(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* params, ast::nodes::TypeExpression* return_type);
  ast::nodes::MethodType* action30_method_type(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* params, ast::nodes::TypeExpression* return_type);
  ast::nodes::MethodType* action31_method_type(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* params, ast::nodes::TypeExpression* return_type);
  ast::nodes::ArrowBody* action32_arrow_body(SourceLoc loc, ast::nodes::ValueExpr* value);
  grammarSupport::FunctionBody* action33_function_body(SourceLoc loc, ast::nodes::ArrowBody* body);
  grammarSupport::FunctionBody* action34_function_body(SourceLoc loc, ast::nodes::Scope* body);
  ast::nodes::Scope* action35_scope(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::Statement>>* statements);
  std::vector<std::unique_ptr<ast::nodes::Statement>>* action36_statements(SourceLoc loc);
  std::vector<std::unique_ptr<ast::nodes::Statement>>* action37_statements(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::Statement>>* list, ast::nodes::Statement* statement);
  ast::nodes::FunctionCall* action38_function_call(SourceLoc loc, ast::nodes::ValueExpr* callee, std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* args);
  ast::nodes::Statement* action39_statement(SourceLoc loc, ast::nodes::FunctionCall* call);
  ast::nodes::Statement* action40_statement(SourceLoc loc, ast::nodes::VariableDecl* declaration);
  ast::nodes::ValueExpr* action41_value_expr(SourceLoc loc, std::string* identifier);
  ast::nodes::ValueExpr* action42_value_expr(SourceLoc loc, std::string* package, std::string* identifier);
  ast::nodes::ValueExpr* action43_value_expr(SourceLoc loc, std::string* package, std::string* identifier);
  ast::nodes::ValueExpr* action44_value_expr(SourceLoc loc, std::string* integer);
  ast::nodes::ValueExpr* action45_value_expr(SourceLoc loc, std::string* number);
  ast::nodes::ValueExpr* action46_value_expr(SourceLoc loc, std::string* text);
  ast::nodes::ValueExpr* action47_value_expr(SourceLoc loc, ast::nodes::ParenthizedValue* value);
  ast::nodes::ValueExpr* action48_value_expr(SourceLoc loc, ast::nodes::FunctionCall* call);
  ast::nodes::ValueExpr* action49_value_expr(SourceLoc loc, ast::nodes::ValueExpr* expr);
  ast::nodes::ValueExpr* action50_value_expr(SourceLoc loc, ast::nodes::ValueExpr* left, ast::nodes::ValueExpr* right);
  ast::nodes::ValueExpr* action51_value_expr(SourceLoc loc, ast::nodes::ValueExpr* left, ast::nodes::ValueExpr* right);
  ast::nodes::ValueExpr* action52_value_expr(SourceLoc loc, ast::nodes::ValueExpr* left, ast::nodes::ValueExpr* right);
  ast::nodes::ValueExpr* action53_value_expr(SourceLoc loc, ast::nodes::ValueExpr* left, ast::nodes::ValueExpr* right);
  ast::nodes::ParenthizedValue* action54_parenthized_value(SourceLoc loc, ast::nodes::ValueExpr* value);
  std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* action55_arguments(SourceLoc loc);
  std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* action56_arguments(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* list);
  std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* action57_argument_list(SourceLoc loc, ast::nodes::ValueExpr* value);
  std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* action58_argument_list(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* list, ast::nodes::ValueExpr* value);
  inline int dup_may_break(int p) ;
  inline void del_may_break(int p) ;
  inline ast::nodes::Package* dup_package(ast::nodes::Package* p) ;
  inline void del_package(ast::nodes::Package* p) ;
  inline std::vector<ast::nodes::Declaration>* dup_global_scope(std::vector<ast::nodes::Declaration>* p) ;
  inline void del_global_scope(std::vector<ast::nodes::Declaration>* p) ;
  inline ast::nodes::Declaration* dup_declaration(ast::nodes::Declaration* p) ;
  inline void del_declaration(ast::nodes::Declaration* p) ;
  inline ast::nodes::VariableDecl* dup_variable_decl(ast::nodes::VariableDecl* p) ;
  inline void del_variable_decl(ast::nodes::VariableDecl* p) ;
  inline ast::nodes::FunctionDecl* dup_function_decl(ast::nodes::FunctionDecl* p) ;
  inline void del_function_decl(ast::nodes::FunctionDecl* p) ;
  inline ast::nodes::MethodDecl* dup_method_decl(ast::nodes::MethodDecl* p) ;
  inline void del_method_decl(ast::nodes::MethodDecl* p) ;
  inline std::vector<ast::nodes::Parameter>* dup_parameters(std::vector<ast::nodes::Parameter>* p) ;
  inline void del_parameters(std::vector<ast::nodes::Parameter>* p) ;
  inline std::vector<ast::nodes::Parameter>* dup_parameter_list(std::vector<ast::nodes::Parameter>* p) ;
  inline void del_parameter_list(std::vector<ast::nodes::Parameter>* p) ;
  inline std::vector<ast::nodes::Parameter>* dup_method_parameters(std::vector<ast::nodes::Parameter>* p) ;
  inline void del_method_parameters(std::vector<ast::nodes::Parameter>* p) ;
  inline std::vector<ast::nodes::Parameter>* dup_method_parameter_seq(std::vector<ast::nodes::Parameter>* p) ;
  inline void del_method_parameter_seq(std::vector<ast::nodes::Parameter>* p) ;
  inline ast::nodes::Parameter* dup_parameter(ast::nodes::Parameter* p) ;
  inline void del_parameter(ast::nodes::Parameter* p) ;
  inline std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* dup_type_list(std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* p) ;
  inline void del_type_list(std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* p) ;
  inline std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* dup_type_list_ne(std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* p) ;
  inline void del_type_list_ne(std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* p) ;
  inline ast::nodes::TypeExpression* dup_type_expr(ast::nodes::TypeExpression* p) ;
  inline void del_type_expr(ast::nodes::TypeExpression* p) ;
  inline ast::nodes::NameType* dup_name_type(ast::nodes::NameType* p) ;
  inline void del_name_type(ast::nodes::NameType* p) ;
  inline ast::nodes::FunctionType* dup_function_type(ast::nodes::FunctionType* p) ;
  inline void del_function_type(ast::nodes::FunctionType* p) ;
  inline ast::nodes::MethodType* dup_method_type(ast::nodes::MethodType* p) ;
  inline void del_method_type(ast::nodes::MethodType* p) ;
  inline ast::nodes::ArrowBody* dup_arrow_body(ast::nodes::ArrowBody* p) ;
  inline void del_arrow_body(ast::nodes::ArrowBody* p) ;
  inline grammarSupport::FunctionBody* dup_function_body(grammarSupport::FunctionBody* p) ;
  inline void del_function_body(grammarSupport::FunctionBody* p) ;
  inline ast::nodes::Scope* dup_scope(ast::nodes::Scope* p) ;
  inline void del_scope(ast::nodes::Scope* p) ;
  inline std::vector<std::unique_ptr<ast::nodes::Statement>>* dup_statements(std::vector<std::unique_ptr<ast::nodes::Statement>>* p) ;
  inline void del_statements(std::vector<std::unique_ptr<ast::nodes::Statement>>* p) ;
  inline ast::nodes::FunctionCall* dup_function_call(ast::nodes::FunctionCall* p) ;
  inline void del_function_call(ast::nodes::FunctionCall* p) ;
  inline ast::nodes::Statement* dup_statement(ast::nodes::Statement* p) ;
  inline void del_statement(ast::nodes::Statement* p) ;
  inline ast::nodes::ValueExpr* dup_value_expr(ast::nodes::ValueExpr* p) ;
  inline void del_value_expr(ast::nodes::ValueExpr* p) ;
  inline ast::nodes::ParenthizedValue* dup_parenthized_value(ast::nodes::ParenthizedValue* p) ;
  inline void del_parenthized_value(ast::nodes::ParenthizedValue* p) ;
  inline std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* dup_arguments(std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* p) ;
  inline void del_arguments(std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* p) ;
  inline std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* dup_argument_list(std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* p) ;
  inline void del_argument_list(std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* p) ;
  inline std::string* dup_TOK_STRING(std::string* s) ;
  inline void del_TOK_STRING(std::string* s) ;
  inline std::string* dup_TOK_IDENT(std::string* s) ;
  inline void del_TOK_IDENT(std::string* s) ;
  inline std::string* dup_TOK_INT(std::string* s) ;
  inline void del_TOK_INT(std::string* s) ;
  inline std::string* dup_TOK_FLOAT(std::string* s) ;
  inline void del_TOK_FLOAT(std::string* s) ;

// the function which makes the parse tables
public:
  virtual ParseTables *makeTables();
};

#endif // SRC_GRAMMAR_PARSER_H
