// src/grammar/parser.h
// *** DO NOT EDIT BY HAND ***
// automatically generated by elkhound, from src/grammar/parser.gr

#ifndef SRC_GRAMMAR_PARSER_H
#define SRC_GRAMMAR_PARSER_H

#include "useract.h"     // UserActions


#line 1 "src/grammar/parser.gr"

	#include "ast/.hpp"
	#include <memory>
	#include <string>
	#include <utility>
	#include <variant>
	#include <vector>

	namespace grammar_support {

	struct FunctionBodyValue {
		std::variant<ast::nodes::Scope, ast::nodes::ArrowBody> value;

		explicit FunctionBodyValue(std::variant<ast::nodes::Scope, ast::nodes::ArrowBody> value)
		: value(std::move(value)) {}
	};

	template <typename T>
	T take_value(T* ptr) {
		T value = std::move(*ptr);
		delete ptr;
		return value;
	}

	template <typename T>
	std::unique_ptr<T> take_ptr(T* ptr) {
		return std::unique_ptr<T>(ptr);
	}

	inline std::string take_string(std::string* ptr) {
		std::string value = std::move(*ptr);
		delete ptr;
		return value;
	}

	inline ast::nodes::ValueExpr* make_binary(
		std::string op,
		ast::nodes::ValueExpr* left,
		ast::nodes::ValueExpr* right
	) {
		return new ast::nodes::ValueExpr(
			ast::nodes::OperatorCall(
				std::move(op),
				take_ptr(left),
				take_ptr(right)
			)
		);
	}

	inline ast::nodes::ValueExpr* make_flip(ast::nodes::ValueExpr* value) {
		return new ast::nodes::ValueExpr(ast::nodes::OperatorFlipCall(take_ptr(value)));
	}

	inline ast::nodes::ValueExpr* wrap_call(ast::nodes::FunctionCall* call) {
		return new ast::nodes::ValueExpr(take_value(call));
	}

	inline ast::nodes::ValueExpr* wrap_parenthesized(ast::nodes::ParenthizedValue* value) {
		return new ast::nodes::ValueExpr(take_value(value));
	}

	} // namespace grammar_support

#line 76 "src/grammar/parser.h"


// parser context class
class 
#line 67 "src/grammar/parser.gr"
 ZaneParser : public UserActions {
public:
	// generated parser hooks are added by Elkhound

#line 86 "src/grammar/parser.h"


private:
  USER_ACTION_FUNCTIONS      // see useract.h

  // declare the actual action function
  static SemanticValue doReductionAction(
    ZaneParser *ths,
    int productionId, SemanticValue const *semanticValues,
  SourceLoc loc);

  // declare the classifier function
  static int reclassifyToken(
    ZaneParser *ths,
    int oldTokenType, SemanticValue sval);

  ast::nodes::Package* action0___EarlyStartSymbol(SourceLoc loc, ast::nodes::Package* top);
  ast::nodes::Package* action1_package(SourceLoc loc, std::vector<ast::nodes::Declaration>* declarations);
  std::vector<ast::nodes::Declaration>* action2_global_scope(SourceLoc loc);
  std::vector<ast::nodes::Declaration>* action3_global_scope(SourceLoc loc, std::vector<ast::nodes::Declaration>* declarations, ast::nodes::Declaration* declaration);
  ast::nodes::Declaration* action4_declaration(SourceLoc loc, ast::nodes::FunctionDecl* function);
  ast::nodes::Declaration* action5_declaration(SourceLoc loc, ast::nodes::MethodDecl* method);
  ast::nodes::VariableDecl* action6_variable_decl(SourceLoc loc, std::string* name, ast::nodes::TypeExpression* type, ast::nodes::ValueExpr* value);
  ast::nodes::FunctionDecl* action7_function_decl(SourceLoc loc, ast::nodes::TypeExpression* return_type, std::string* name, std::vector<ast::nodes::Parameter>* params, grammar_support::FunctionBodyValue* body);
  ast::nodes::MethodDecl* action8_method_decl(SourceLoc loc, ast::nodes::TypeExpression* return_type, std::string* name, std::vector<ast::nodes::Parameter>* params, grammar_support::FunctionBodyValue* body);
  ast::nodes::MethodDecl* action9_method_decl(SourceLoc loc, ast::nodes::TypeExpression* return_type, std::string* name, std::vector<ast::nodes::Parameter>* params, grammar_support::FunctionBodyValue* body);
  std::vector<ast::nodes::Parameter>* action10_parameters(SourceLoc loc);
  std::vector<ast::nodes::Parameter>* action11_parameters(SourceLoc loc, std::vector<ast::nodes::Parameter>* list);
  std::vector<ast::nodes::Parameter>* action12_parameter_list(SourceLoc loc, ast::nodes::Parameter* parameter);
  std::vector<ast::nodes::Parameter>* action13_parameter_list(SourceLoc loc, std::vector<ast::nodes::Parameter>* list, ast::nodes::Parameter* parameter);
  std::vector<ast::nodes::Parameter>* action14_method_parameters(SourceLoc loc, std::vector<ast::nodes::Parameter>* list);
  std::vector<ast::nodes::Parameter>* action15_method_parameter_seq(SourceLoc loc, ast::nodes::TypeExpression* type);
  std::vector<ast::nodes::Parameter>* action16_method_parameter_seq(SourceLoc loc, std::vector<ast::nodes::Parameter>* list, ast::nodes::Parameter* parameter);
  ast::nodes::Parameter* action17_parameter(SourceLoc loc, std::string* name, ast::nodes::TypeExpression* type);
  std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* action18_type_list(SourceLoc loc);
  std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* action19_type_list(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* list);
  std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* action20_type_list_ne(SourceLoc loc, ast::nodes::TypeExpression* expr);
  std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* action21_type_list_ne(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* list, ast::nodes::TypeExpression* expr);
  ast::nodes::TypeExpression* action22_type_expr(SourceLoc loc, ast::nodes::NameType* name);
  ast::nodes::TypeExpression* action23_type_expr(SourceLoc loc, ast::nodes::FunctionType* function);
  ast::nodes::TypeExpression* action24_type_expr(SourceLoc loc, ast::nodes::MethodType* method);
  ast::nodes::NameType* action25_name_type(SourceLoc loc, std::string* identifier);
  ast::nodes::FunctionType* action26_function_type(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* params, ast::nodes::TypeExpression* return_type);
  ast::nodes::MethodType* action27_method_type(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* params, ast::nodes::TypeExpression* return_type);
  ast::nodes::MethodType* action28_method_type(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* params, ast::nodes::TypeExpression* return_type);
  ast::nodes::ArrowBody* action29_arrow_body(SourceLoc loc, ast::nodes::ValueExpr* value);
  grammar_support::FunctionBodyValue* action30_function_body(SourceLoc loc, ast::nodes::ArrowBody* body);
  grammar_support::FunctionBodyValue* action31_function_body(SourceLoc loc, ast::nodes::Scope* body);
  ast::nodes::Scope* action32_scope(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::Statement>>* statements);
  std::vector<std::unique_ptr<ast::nodes::Statement>>* action33_statements(SourceLoc loc);
  std::vector<std::unique_ptr<ast::nodes::Statement>>* action34_statements(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::Statement>>* list, ast::nodes::Statement* statement);
  ast::nodes::Statement* action35_statement(SourceLoc loc, ast::nodes::FunctionCall* call);
  ast::nodes::Statement* action36_statement(SourceLoc loc, ast::nodes::VariableDecl* declaration);
  ast::nodes::FunctionCall* action37_statement_function_call(SourceLoc loc, ast::nodes::FunctionCall* call);
  ast::nodes::ValueExpr* action38_value_expr(SourceLoc loc, ast::nodes::ValueExpr* expr);
  ast::nodes::ValueExpr* action39_additive_expr(SourceLoc loc, ast::nodes::ValueExpr* expr);
  ast::nodes::ValueExpr* action40_additive_expr(SourceLoc loc, ast::nodes::ValueExpr* left, ast::nodes::ValueExpr* right);
  ast::nodes::ValueExpr* action41_additive_expr(SourceLoc loc, ast::nodes::ValueExpr* left, ast::nodes::ValueExpr* right);
  ast::nodes::ValueExpr* action42_multiplicative_expr(SourceLoc loc, ast::nodes::ValueExpr* expr);
  ast::nodes::ValueExpr* action43_multiplicative_expr(SourceLoc loc, ast::nodes::ValueExpr* left, ast::nodes::ValueExpr* right);
  ast::nodes::ValueExpr* action44_multiplicative_expr(SourceLoc loc, ast::nodes::ValueExpr* left, ast::nodes::ValueExpr* right);
  ast::nodes::ValueExpr* action45_unary_expr(SourceLoc loc, ast::nodes::ValueExpr* expr);
  ast::nodes::ValueExpr* action46_unary_expr(SourceLoc loc, ast::nodes::ValueExpr* expr);
  ast::nodes::ValueExpr* action47_postfix_expr(SourceLoc loc, ast::nodes::ValueExpr* expr);
  ast::nodes::ValueExpr* action48_postfix_expr(SourceLoc loc, ast::nodes::FunctionCall* call);
  ast::nodes::FunctionCall* action49_call_expr(SourceLoc loc, ast::nodes::ValueExpr* callee, std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* args);
  ast::nodes::FunctionCall* action50_call_expr(SourceLoc loc, ast::nodes::FunctionCall* callee, std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* args);
  ast::nodes::ValueExpr* action51_primary_expr(SourceLoc loc, std::string* identifier);
  ast::nodes::ValueExpr* action52_primary_expr(SourceLoc loc, std::string* package, std::string* identifier);
  ast::nodes::ValueExpr* action53_primary_expr(SourceLoc loc, std::string* package, std::string* identifier);
  ast::nodes::ValueExpr* action54_primary_expr(SourceLoc loc, std::string* integer);
  ast::nodes::ValueExpr* action55_primary_expr(SourceLoc loc, std::string* number);
  ast::nodes::ValueExpr* action56_primary_expr(SourceLoc loc, std::string* text);
  ast::nodes::ValueExpr* action57_primary_expr(SourceLoc loc, ast::nodes::ParenthizedValue* value);
  ast::nodes::ParenthizedValue* action58_parenthized_value(SourceLoc loc, ast::nodes::ValueExpr* value);
  std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* action59_arguments(SourceLoc loc);
  std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* action60_arguments(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* list);
  std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* action61_argument_list(SourceLoc loc, ast::nodes::ValueExpr* value);
  std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* action62_argument_list(SourceLoc loc, std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* list, ast::nodes::ValueExpr* value);
  inline ast::nodes::Package* dup_package(ast::nodes::Package* p) ;
  inline void del_package(ast::nodes::Package* p) ;
  inline std::vector<ast::nodes::Declaration>* dup_global_scope(std::vector<ast::nodes::Declaration>* p) ;
  inline void del_global_scope(std::vector<ast::nodes::Declaration>* p) ;
  inline ast::nodes::Declaration* dup_declaration(ast::nodes::Declaration* p) ;
  inline void del_declaration(ast::nodes::Declaration* p) ;
  inline ast::nodes::VariableDecl* dup_variable_decl(ast::nodes::VariableDecl* p) ;
  inline void del_variable_decl(ast::nodes::VariableDecl* p) ;
  inline ast::nodes::FunctionDecl* dup_function_decl(ast::nodes::FunctionDecl* p) ;
  inline void del_function_decl(ast::nodes::FunctionDecl* p) ;
  inline ast::nodes::MethodDecl* dup_method_decl(ast::nodes::MethodDecl* p) ;
  inline void del_method_decl(ast::nodes::MethodDecl* p) ;
  inline std::vector<ast::nodes::Parameter>* dup_parameters(std::vector<ast::nodes::Parameter>* p) ;
  inline void del_parameters(std::vector<ast::nodes::Parameter>* p) ;
  inline std::vector<ast::nodes::Parameter>* dup_parameter_list(std::vector<ast::nodes::Parameter>* p) ;
  inline void del_parameter_list(std::vector<ast::nodes::Parameter>* p) ;
  inline std::vector<ast::nodes::Parameter>* dup_method_parameters(std::vector<ast::nodes::Parameter>* p) ;
  inline void del_method_parameters(std::vector<ast::nodes::Parameter>* p) ;
  inline std::vector<ast::nodes::Parameter>* dup_method_parameter_seq(std::vector<ast::nodes::Parameter>* p) ;
  inline void del_method_parameter_seq(std::vector<ast::nodes::Parameter>* p) ;
  inline ast::nodes::Parameter* dup_parameter(ast::nodes::Parameter* p) ;
  inline void del_parameter(ast::nodes::Parameter* p) ;
  inline std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* dup_type_list(std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* p) ;
  inline void del_type_list(std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* p) ;
  inline std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* dup_type_list_ne(std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* p) ;
  inline void del_type_list_ne(std::vector<std::unique_ptr<ast::nodes::TypeExpression>>* p) ;
  inline ast::nodes::TypeExpression* dup_type_expr(ast::nodes::TypeExpression* p) ;
  inline void del_type_expr(ast::nodes::TypeExpression* p) ;
  inline ast::nodes::NameType* dup_name_type(ast::nodes::NameType* p) ;
  inline void del_name_type(ast::nodes::NameType* p) ;
  inline ast::nodes::FunctionType* dup_function_type(ast::nodes::FunctionType* p) ;
  inline void del_function_type(ast::nodes::FunctionType* p) ;
  inline ast::nodes::MethodType* dup_method_type(ast::nodes::MethodType* p) ;
  inline void del_method_type(ast::nodes::MethodType* p) ;
  inline ast::nodes::ArrowBody* dup_arrow_body(ast::nodes::ArrowBody* p) ;
  inline void del_arrow_body(ast::nodes::ArrowBody* p) ;
  inline grammar_support::FunctionBodyValue* dup_function_body(grammar_support::FunctionBodyValue* p) ;
  inline void del_function_body(grammar_support::FunctionBodyValue* p) ;
  inline ast::nodes::Scope* dup_scope(ast::nodes::Scope* p) ;
  inline void del_scope(ast::nodes::Scope* p) ;
  inline std::vector<std::unique_ptr<ast::nodes::Statement>>* dup_statements(std::vector<std::unique_ptr<ast::nodes::Statement>>* p) ;
  inline void del_statements(std::vector<std::unique_ptr<ast::nodes::Statement>>* p) ;
  inline ast::nodes::Statement* dup_statement(ast::nodes::Statement* p) ;
  inline void del_statement(ast::nodes::Statement* p) ;
  inline ast::nodes::FunctionCall* dup_statement_function_call(ast::nodes::FunctionCall* p) ;
  inline void del_statement_function_call(ast::nodes::FunctionCall* p) ;
  inline ast::nodes::ValueExpr* dup_value_expr(ast::nodes::ValueExpr* p) ;
  inline void del_value_expr(ast::nodes::ValueExpr* p) ;
  inline ast::nodes::ValueExpr* dup_additive_expr(ast::nodes::ValueExpr* p) ;
  inline void del_additive_expr(ast::nodes::ValueExpr* p) ;
  inline ast::nodes::ValueExpr* dup_multiplicative_expr(ast::nodes::ValueExpr* p) ;
  inline void del_multiplicative_expr(ast::nodes::ValueExpr* p) ;
  inline ast::nodes::ValueExpr* dup_unary_expr(ast::nodes::ValueExpr* p) ;
  inline void del_unary_expr(ast::nodes::ValueExpr* p) ;
  inline ast::nodes::ValueExpr* dup_postfix_expr(ast::nodes::ValueExpr* p) ;
  inline void del_postfix_expr(ast::nodes::ValueExpr* p) ;
  inline ast::nodes::FunctionCall* dup_call_expr(ast::nodes::FunctionCall* p) ;
  inline void del_call_expr(ast::nodes::FunctionCall* p) ;
  inline ast::nodes::ValueExpr* dup_primary_expr(ast::nodes::ValueExpr* p) ;
  inline void del_primary_expr(ast::nodes::ValueExpr* p) ;
  inline ast::nodes::ParenthizedValue* dup_parenthized_value(ast::nodes::ParenthizedValue* p) ;
  inline void del_parenthized_value(ast::nodes::ParenthizedValue* p) ;
  inline std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* dup_arguments(std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* p) ;
  inline void del_arguments(std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* p) ;
  inline std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* dup_argument_list(std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* p) ;
  inline void del_argument_list(std::vector<std::unique_ptr<ast::nodes::ValueExpr>>* p) ;
  inline std::string* dup_TOK_STRING(std::string* s) ;
  inline void del_TOK_STRING(std::string* s) ;
  inline std::string* dup_TOK_IDENT(std::string* s) ;
  inline void del_TOK_IDENT(std::string* s) ;
  inline std::string* dup_TOK_INT(std::string* s) ;
  inline void del_TOK_INT(std::string* s) ;
  inline std::string* dup_TOK_FLOAT(std::string* s) ;
  inline void del_TOK_FLOAT(std::string* s) ;

// the function which makes the parse tables
public:
  virtual ParseTables *makeTables();
};

#endif // SRC_GRAMMAR_PARSER_H
