(* Generated by tools.grammar; edit grammar/lexicon.json. *)
open Sedlexing
open Parser

exception Lexing_error

let rec token buf =
  match%sedlex buf with
  | Plus ((" " | "\t" | "\r" | "\n")) -> token buf
  | ("///", Star (Compl ('\n' | '\r'))) -> token buf
  | ("//", Star (Compl ('\n' | '\r'))) -> token buf
  | "(" -> LPAREN
  | ")" -> RPAREN
  | "," -> COMMA
  | "{" -> LCURLY
  | "}" -> RCURLY
  | "[" -> LBRACKET
  | "]" -> RBRACKET
  | ":" -> COLON
  | ";" -> SEMICOLON
  | "." -> DOT
  | "=" -> EQUAL
  | "+" -> PLUS
  | "-" -> MINUS
  | "*" -> STAR
  | "/" -> SLASH
  | "$" -> DOLLAR
  | "#" -> HASH
  | "&" -> AMPERSAND
  | "@" -> AT
  | "!" -> EXCL
  | "?" -> QSTNMARK
  | "??" -> QSTNQSTN
  | "~" -> TILDE
  | "=>" -> THICK_ARROW
  | "==" -> EQEQ
  | "~=" -> NOTEQ
  | "<=" -> LESSEQ
  | ">=" -> MOREEQ
  | "<" -> LESS
  | ">" -> MORE
  | "'*" -> LOOSE_STAR
  | "'/" -> LOOSE_SLASH
  | "'+" -> LOOSE_PLUS
  | "'-" -> LOOSE_MINUS
  | "'==" -> LOOSE_EQEQ
  | "'~=" -> LOOSE_NOTEQ
  | "'<=" -> LOOSE_LESSEQ
  | "'>=" -> LOOSE_MOREEQ
  | "'<" -> LOOSE_LESS
  | "'>" -> LOOSE_MORE
  | "type" -> LTYPE
  | "alias" -> ALIAS
  | "Type" -> UTYPE
  | "struct" -> STRUCT
  | "variant" -> VARIANT
  | "enum" -> ENUM
  | "package" -> PACKAGE
  | "import" -> IMPORT
  | "as" -> AS
  | "implicit" -> IMPLICIT
  | "init" -> INIT
  | "match" -> MATCH
  | "spawn" -> SPAWN
  | "true" -> TRUE
  | "false" -> FALSE
  | "this" -> THIS
  | "mut" -> MUT
  | "abort" -> ABORT
  | "return" -> RETURN
  | "resolve" -> RESOLVE
  | eof -> EOF
  | (Plus ('0'..'9'), Star (("'", Plus ('0'..'9')))) -> INT (Utf8.lexeme buf)
  | ((Plus ('0'..'9'), Star (("'", Plus ('0'..'9')))), ".", Plus ('0'..'9')) -> DECIMAL (Utf8.lexeme buf)
  | ("\"", Star ((Compl ('"' | '\\') | ("\\", any))), "\"") -> let s = Utf8.lexeme buf in STRING (String.sub s 1 (String.length s - 2))
  | ((lowercase | ("_", lowercase)), Star ((alphabetic | '0'..'9'))) -> LIDENT (Utf8.lexeme buf)
  | ((uppercase | ("_", uppercase)), Star ((alphabetic | '0'..'9'))) -> UIDENT (Utf8.lexeme buf)
  | _ -> raise Lexing_error
